### ISSUE TITLE
Naive question

### ISSUE THREAD

**Issue by Cadene** [facebookresearch/flashlight#1]
Hi,

Thanks a lot for open sourcing this library :)
How is it different from Pytorch C++ API?

Thanks for your time

**Comment by eric-nok** [comment]
Can you expand a bit why ArrayFire was chosen, i.e., why this library was built? When might a user might prefer an ArrayFire-backed library over Torch/ATen and other alternatives?

**Comment by vineelpratap** [comment]
Hi,
 flashlight is a 1 year effort, we started the project before PyTorch C++ API existed and we wanted C++ first design for our project - [wav2letter](https://github.com/facebookresearch/wav2letter/). 

Here are a few reasons we chose Arrayfire 
- C++11 fully-featured tensor library.
- Easy to use API.
- Good documentation and active community.
- Works seamlessly on multiple devices - supports CPU, CUDA, OPENCL.
- And more importantly, has a JIT compiler for efficiency.

**Comment by yxchng** [comment]
@vineelpratap Can you elaborate more on the reasons? Is PyTorch C++ the negations of the reasons you stated, i.e.
- Not a C++11 fully-featured tensor library
- Bad to use API
- Bad documentation and inactive community
- Works bad on multiple devices
- Has no JIT compiler
It sounds so bad.

**Comment by vineelpratap** [comment]
As mentioned, there was no C++ API for PyTorch when we started the project and we found Arrayfire to be good Tensor library to be used in our projects.

**Comment by edgarriba** [comment]
wasn't Caffe2 already there by that time ? :D
Anyways, awesome library !
