### ISSUE TITLE
CachingMemoryManager logs/prints

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#122]
As today the CachingMemoryManager 
https://github.com/facebookresearch/flashlight/blob/master/flashlight/memory/managers/CachingMemoryManager.cpp
sometimes std cout (printInfo, ...) and sometimes std cerr.
Would you mind if I replace these with, for instance, FL logging (Logging.h) ?
Kind

**Comment by vineelpratap** [comment]
Please go ahead !
