### ISSUE TITLE
CachingMemoryManager::mallocWithRetry to rethrow if OOM

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#125]
Hello
As today 
CachingMemoryManager::mallocWithRetry()
throws a std runtime_error even when AF throws an OOM except :
 'ArrayFire Exception (Device out of memory:101)'

> try {
      signalMemoryCleanup();
      ++memoryInfo.stats_.totalNativeMallocs_;
      *ptr = this->deviceInterface->nativeAlloc(size);
    } catch (std::exception& ex) {
      // DEBUG: throw std::runtime_error doesn't work.
      std::cerr << "Unable to allocate memory with native alloc for size " +
              std::to_string(size) + " bytes with error '" + ex.what()
                << "'";
      throw std::runtime_error(ex.what());
    }

That makes OOM impossible/hard to catch at higher user level.

Would you mind if I modify slightly this method to (re)throw an AF OOM exception :

try {
..
} catch (af::exception & e) {
 throw;
}
Kind

**Comment by vineelpratap** [comment]
Yes, that make sense. Please make sure OOM errors,  please make sure the user can clearly figure out these things from the logs 
1. error is coming from out of memory
2. how much memory was requested for OOM to trigger.

**Comment by WilliamTambellini** [comment]
https://github.com/facebookresearch/flashlight/pull/129

**Comment by WilliamTambellini** [comment]
@vineelpratap I ve pushed the PR : rethrowing seems actually better and now allows to catch the af OOM exception at the user level. Could you please review it?
