### ISSUE TITLE
During compiling: make fails in Ubuntu 18.04.4 Desktop

### ISSUE THREAD

**Issue by marcoippolito** [facebookresearch/flashlight#127]
I'm trying to install and compile flashligt in Ubuntu 18.04.4 Desktop

cmake phase went fine:

    (base) marco@pc01:~/cpp/flashlight/build$ cmake .. -DCMAKE_BUILD_TYPE=Release  
    -DFLASHLIGHT_BACKEND=CPU -Wno-dev -DFL_BUILD_DISTRIBUTED=OFF
    -- The C compiler identification is GNU 9.3.0
    -- The CXX compiler identification is GNU 9.3.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- ArrayFire found (include: /usr/local/include, library: ArrayFire::afcpu)
    -- Could NOT find cereal (missing: cereal_INCLUDE_DIRS) 
    -- cereal NOT found. Will download from source
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_gf: not found
    -- Checking for [mkl_gf - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_intel: not found
    -- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - pthread - m]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
    --   Library mkl_gf: not found
    -- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
    --   Library mkl_intel: not found
    -- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_sequential - mkl_core - m]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_sequential - mkl_core - m]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_sequential - mkl_core - m]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_sequential - mkl_core - m]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_sequential - mkl_core - m]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_sequential - mkl_core - m]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_sequential - mkl_core - m]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_gf: not found
    -- Checking for [mkl_gf - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_intel: not found
    -- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - pthread - m]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
    --   Library mkl_gf: not found
    -- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
    --   Library mkl_intel: not found
    -- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
    --   Library mkl_intel: not found
    -- Checking for [mkl - guide - pthread - m]
    --   Library mkl: not found
    -- MKL not found
    -- Looking for sgemm_
    -- Looking for sgemm_ - not found
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Looking for sgemm_
    -- Looking for sgemm_ - found
    -- Found BLAS: /usr/lib/x86_64-linux-gnu/libopenblas.so  
    -- Attempting to build MKLDNN without MKL in current configuration.
    -- MKLDNN headers found in /usr/local/include
    -- Using MKLDNN library found in /usr/local/lib/libmkldnn.so
    -- MKL not found; trying to fall back to mklml library
    -- Using MKL-DNN without mklml headers
    -- mklml not found; trying to fall back to system BLAS library
    -- BLAS libraries found: /usr/lib/x86_64-linux-gnu/libopenblas.so
    -- MKLDNN found
    -- Will build flashlight contrib assets.
    -- Check if compiler accepts -pthread
    -- Check if compiler accepts -pthread - yes
    -- Gloo found
    -- NCCL not found
    -- MPI not found
    -- Found GTest: /usr/lib/libgtest.a (Required is at least version "1.10.0") 
    -- gtest found: (include: /usr/include, lib: /usr/lib/libgtest.a;/usr/lib/libgtest_main.a
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/marco/cpp/flashlight/build
    (base) marco@pc01:~/cpp/flashlight/build$ 

But the next phase fails with: 

    CMakeFiles/MemoryFrameworkTest.dir/memory/MemoryFrameworkTest.cpp.o: In function 
    `testing::internal::Assert(bool, char const*, int, std::__cxx11::basic_string<char, 
    std::char_traits<char>, std::allocator<char> > const&) [clone .part.0]':
    MemoryFrameworkTest.cpp:(.text+0x49f): undefined reference to 
    `testing::internal::GetFailureReporter()'

I put the entire output of make phase in a txt file, which I attach here.
[flashlightMakeErrors.txt](https://github.com/facebookresearch/flashlight/files/4655545/flashlightMakeErrors.txt)

gcc version 9.3.0 (Ubuntu 9.3.0-11ubuntu0~18.04.1)

I'm having the same problem if I run make with only 1 job. 
[flashlightMakeErrorsOneJobOnly.txt](https://github.com/facebookresearch/flashlight/files/4655845/flashlightMakeErrorsOneJobOnly.txt)

How to solve the problem?
Looking forward to your kind help.
Marco

**Comment by tlikhomanenko** [comment]
@avidov any idea?

**Comment by tlikhomanenko** [comment]
@marcoippolito, 

Could you try to install `gcc-5 g++-5` and try with it (example you can see here https://github.com/facebookresearch/flashlight/blob/master/.circleci/config.yml#L60)? So possibly some problems with the compiler version I guess.

**Comment by jacobkahn** [comment]
@marcoippolito This looks like a missing symbol from gtest. Make sure you’re using at least gtest 1.10.0 as per the [flashlight docs](https://fl.readthedocs.io/en/latest/). 

Please follow up if you’re still having problems.

**Comment by phtephanx** [comment]
My problem looks related.

I have build `googletest==1.10.0` from [source](https://github.com/google/googletest/releases/tag/release-1.10.0) and installed. 
Didn't figure out a waterproof way to double-check the version but in `usr/local/lib/cmake/GTest/GTestConfigVersion.cmake` it states `set(PACKAGE_VERSION "1.10.0")`

Error:

```
[ 56%] Linking CXX executable MemoryFrameworkTest
CMakeFiles/MemoryFrameworkTest.dir/memory/MemoryFrameworkTest.cpp.o: In function `(anonymous namespace)::MockTestMemoryManager::unlock(void*, bool)':
MemoryFrameworkTest.cpp:(.text+0x523): undefined reference to `testing::internal::UntypedFunctionMockerBase::SetOwnerAndName(void const*, char const*)'
MemoryFrameworkTest.cpp:(.text+0x53a): undefined reference to `testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith(void*)'
...
collect2: error: ld returned 1 exit status
tests/CMakeFiles/MemoryFrameworkTest.dir/build.make:2005: recipe for target 'tests/MemoryFrameworkTest' failed
```

**Comment by avidov** [comment]
Possibly you are missing the right gmock repository.

**Comment by phtephanx** [comment]
I installed `google-mock==`v1.8.0` but that didn't help.

**Comment by jacobkahn** [comment]
@phtephanx — Google Mock also has to be >= 1.10.0. gmock merged into the gtest repo as of 1.8.0 as far as I know. Installing from the [gtest repo](https://github.com/google/googletest) and building from source will include all gmock symbols.

**Comment by phtephanx** [comment]
What worked for me is to remove all `gtest` and `gmock` libs from my system folders and let `flashlight`'s build script build them locally. Build has successfully completed. 

Regarding the tests: "78% tests passed, 4 tests failed out of 18", but that's another story.

**Comment by jacobkahn** [comment]
Closing for now. @marcoippolito let me know if you're still having issues.
