### ISSUE TITLE
Compilation error with MSVC in MemoryManagerAdapter.cpp

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#130]
Hello
I know flashlight is not supposed to work and/or be supported at all under VisualStudio but this is just a compilation error that could allow at least to (partially) compile it : 

flashlight\memory\MemoryManagerAdapter.cpp(19): error C2236: unexpected token 'struct'. Did you forget a ';'?

This is because microsoft, in some of their headers (combaseapi.h, ...), defines 'interface' as 'struct':
 #define interface struct
A simple retouch is not to use the name 'interface' as an identifier, specially in MemoryManagerAdapter.cpp: for instance:
MemoryManagerAdapter::MemoryManagerAdapter(std::shared_ptr<MemoryManagerDeviceInterface> interface, ...
to 
MemoryManagerAdapter::MemoryManagerAdapter(std::shared_ptr<MemoryManagerDeviceInterface> intrf, ...

Kind

**Comment by WilliamTambellini** [comment]
https://stackoverflow.com/questions/59973219/c2236-unexpected-token-struct-did-you-forget-c2332-struct-missing

**Comment by vineelpratap** [comment]
Thanks for the suggestion. 
Do you mind sending PR since you seem to have the setup to test build already.

**Comment by WilliamTambellini** [comment]
https://github.com/facebookresearch/flashlight/pull/131
