### ISSUE TITLE
missing logsoftmax operation in example Rnnlm

### ISSUE THREAD

**Issue by qzfnihao** [facebookresearch/flashlight#139]
in example/Rnnlm, we define a class Rnnlm with forward function:
  std::tuple<Variable, Variable, Variable>
  forward(const Variable& input, const Variable& h, const Variable& c) {
    auto output = embed(input);
    Variable ho, co;
    std::tie(output, ho, co) = rnn(output, h, c);

    // Truncate BPTT
    ho.setCalcGrad(false);
    co.setCalcGrad(false);

    output = linear(output);
    return std::make_tuple(output, ho, co);
  }
and use CategoricalCrossEntropy to calc loss, but CategoricalCrossEntropy need logsoftmax as input, so: Maybe this is a bug! 

RnnLm::forward  function ignores operation: logsoftmax, which should use after linear and before return.

**Comment by tlikhomanenko** [comment]
cc @awni

**Comment by awni** [comment]
This does indeed seem to be a bug! Could you submit a PR?

**Comment by WilliamTambellini** [comment]
The example still seems to miss the logsoftmax fwd in the RnnLm model forward:
https://github.com/facebookresearch/flashlight/blob/1a47844ea1afbcbee563b5e8a784a6d32cdb4da8/flashlight/fl/examples/RnnLm.cpp#L109
and indeed, neg/crazy loss as reported in:
https://github.com/facebookresearch/flashlight/issues/137
Retouching that way:
```cpp
    output = linear(output);
    LogSoftmax lsm(0); // max on the main dimension
    output = lsm(output);
    return std::make_tuple(output, ho, co);
```
seems to do the job 
```
$ ./flashlight/fl/examples/RnnLm simple-examples/data/
Vocab size: 10000
Epoch 1 - Train Loss: 5.69 Validation Loss: 5.25 Validation Perplexity: 191 Time per iteration (ms): 10.9
Epoch 2 - Train Loss: 4.96 Validation Loss: 5.01 Validation Perplexity: 150 Time per iteration (ms): 10.8
Epoch 3 - Train Loss: 4.7 Validation Loss: 4.93 Validation Perplexity: 138 Time per iteration (ms): 10.8
Epoch 4 - Train Loss: 4.52 Validation Loss: 4.88 Validation Perplexity: 132 Time per iteration (ms): 10.8
Epoch 5 - Train Loss: 4.26 Validation Loss: 4.8 Validation Perplexity: 121 Time per iteration (ms): 10.7
```
@tlikhomanenko  @awni  Still worth a PR ?

**Comment by WilliamTambellini** [comment]
closable

**Comment by tlikhomanenko** [comment]
Thanks a lot for the PR and catching this!
