### ISSUE TITLE
Could not build with CPU backend

### ISSUE THREAD

**Issue by mitulsaha** [facebookresearch/flashlight#144]
Hi, 

I get this build error, when trying to build flashlight with CPU backend:-

flashlight/tests/nn/NNSerializationTest.cpp: In lambda function:
flashlight/tests/nn/NNSerializationTest.cpp:236:56: error: ‘remove_if’ was not declared in this scope
     str.erase(remove_if(str.begin(), str.end(), isspace), str.end());

Then latter on, I would get these:-
flashlight/tests/nn/NNSerializationTest.cpp: In lambda function:
flashlight/tests/nn/NNSerializationTest.cpp:236:56: error: ‘remove_if’ was not declared in this scope
     str.erase(remove_if(str.begin(), str.end(), isspace), str.end());

Any ideas, how to resolve this?

**Comment by WilliamTambellini** [comment]
https://en.cppreference.com/w/cpp/algorithm/remove
perhaps prepend "std::" in front of remove_if
or if not already done add  #include <algorithm>
Though, remove_if is pretty recent (c++ 17/20) so perhaps your compiler is also perhaps too old. Dont know if the FlashLight cmake build does check for compiler compatibility.

**Comment by mitulsaha** [comment]
Thanks William - That worked!

**Comment by jacobkahn** [comment]
[this was fixed in https://github.com/facebookresearch/flashlight/pull/395 as well -- thanks for reporting!]
