### ISSUE TITLE
how to build offline, namely without automatically downloading gtest & cereal?

### ISSUE THREAD

**Issue by feliiiiicity** [facebookresearch/flashlight#15]
Hi, I'm trying to build flashlight with CPU backend on Ubuntu 16.04. I have already installed cereal and gtest, and the working environment is offline. When I use "make -j4" command, the process simply stuck at git clone (obviously). So what modifications should I do to make the build process work? Thanks.

**Comment by jacobkahn** [comment]
@feliiiiicity — note that we don't officially support an offline build right now (and these instructions may become deprecated in the future). If you want to make this work now, you can do the following:
- Don't build tests (`-DFL_BUILD_TESTS=OFF`)
- If you need or want to build tests, [remove inclusion of BuildGoogleTest.cmake](https://github.com/facebookresearch/flashlight/blob/master/tests/CMakeLists.txt#L4), and add `find_package(GTest REQUIRED)` in its place. You can remove [adding GTest include dirs](https://github.com/facebookresearch/flashlight/blob/master/tests/CMakeLists.txt#L21) and replace it with [`GTEST_INCLUDE_DIRS `](https://cmake.org/cmake/help/v3.0/module/FindGTest.html), and change the [lib link step](https://github.com/facebookresearch/flashlight/blob/master/tests/CMakeLists.txt#L15) to use [`GTEST_BOTH_LIBRARIES`](https://cmake.org/cmake/help/v3.0/module/FindGTest.html).
- For Cereal, replacing [inclusion of BuildCereal.cmake](https://github.com/facebookresearch/flashlight/blob/master/CMakeLists.txt#L88-L101) with `find_package(Cereal REQUIRED)` should be enough.
