### ISSUE TITLE
Cannot compile flashlight with Conan

### ISSUE THREAD

**Issue by picheny-nyu** [facebookresearch/flashlight#150]
### Bug Description
I get this error when trying to compile flashlight per the documentation:

cereal/1.3.0: Retrieving from server 'flashlight' 
cereal/1.3.0: Trying with 'flashlight'...
ERROR: Failed requirement 'cereal/1.3.0' from 'conanfile.py (flashlight/0.1@conan/stable)'
ERROR: cereal/1.3.0 was not found in remote 'flashlight'

#### Reproduction Steps

I issued the following command per the documentation:

 conan install flashlight 0.1@conan/stable -r=flashlight --build flashlight

### Platform and Hardware
GNU Linux 3.10.0-1127.18.2.el7.x86_64 

Thanks
Michael

#### Additional Context
[Add any additional information here]

**Comment by tlikhomanenko** [comment]
cc @jacobkahn

**Comment by jacobkahn** [comment]
@picheny-nyu — since our recent consolidation, the Conan build is a bit broken - I'll get around to fixing it in the next week or so. Sorry about this.

**Comment by picheny-nyu** [comment]
Any workarounds? I tried the manual build instructions and also ran into problems. Otherwise I guess I just have to wait :-(

**Comment by jacobkahn** [comment]
@picheny-nyu — you can give more details on the problems you ran into with the manual build?

We're still getting things in order over the next few days.

**Comment by picheny-nyu** [comment]
In response to 
cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CUDA

I get
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) (Required is at least version "1.10.0")
-- googletest not found - will download and build from source
-- Configuring incomplete, errors occurred!

This is for v0.2 which is per the documentation. Also even though I specify backend as CUDA I do not have NCCL and it tried to look for some distributed stuff anyway. I commented that out and then this error came up. It seemed to have done a partial copy of googletest but never successful compiled it.

**Comment by jacobkahn** [comment]
@picheny-nyu -- what do you want to build? The flashlight core? The ASR components? flashlight libraries? That'll help us figure out what's going on here.

> cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CUDA

`FLASHLIGHT_BACKEND` has been changed to `FL_BACKEND`. This will be reflected in the build documentation soon.

> It seemed to have done a partial copy of googletest but never successful compiled it

You don't need to install GoogleTest yourself - if you don't, the build will download it automatically.

> do not have NCCL and it tried to look for some distributed stuff anyway

For now, even if you're not doing distributed training, you'll still need to install NCCL to build everything.

**Comment by picheny-nyu** [comment]
I did not try to install googletest, the build did not properly download it. 
Is that change (to FL_BACKEND) valid on v0.2 ?
Regarding nccl I have a 10.2 CUDA version with nccl. How do I point to that (it is in a different directory, not sure how it finds CUDA stuff now).

**Comment by tlikhomanenko** [comment]
Please use for now v0.2 and installation from source, conan will be fixed only during several weeks.

Could you send the full log of your CMake command (without any your changes)? W2l can be built only with distributed mode, so please install NCCL and follow all installation instruction. Another option is to use docker image or follow installation steps in the docker file.

**Comment by picheny-nyu** [comment]
OK, luckily I found out that someone has a 10.2 CUDA nccl. How do I tell the build process where to find it?

**Comment by tlikhomanenko** [comment]
Please set env variable NCCL_ROOT_DIR (https://github.com/facebookresearch/flashlight/blob/master/cmake/FindNCCL.cmake#L17)

**Comment by picheny-nyu** [comment]
Thanks. Done. Worked!!

**Comment by tlikhomanenko** [comment]
Closing then for now, because Conan will be supported a bit later (and due to rectructuring we need to fix it anyway).

**Comment by deepwilson** [comment]
I tried installing with vcpkg and it took me a very long time(gave up soon). So looked up for conan. 
Has Conan support been added yet?

**Comment by jacobkahn** [comment]
@deepwilson — vcpkg support is out dated, but I'll be updating it quite soon. https://github.com/flashlight/flashlight/pull/1141 (which is now working completely) was blocking wrapping up https://github.com/microsoft/vcpkg/pull/31844, so expect things to move along soon. I'll be updating the readme, build and install instructions, etc once the vcpkg port is updated.
