### ISSUE TITLE
CUDNN not find

### ISSUE THREAD

**Issue by 943274923** [facebookresearch/flashlight#17]
I have installed cudnn and export in .badhrc.   
also try use cmake .. -DCUDNN_DIR. but  build fail

**Comment by jacobkahn** [comment]
@943274923 — what OS are you using? Where is the cuDNN library located? Can you try specifying `-DCUDNN_ROOT_DIR=[path]` when you build? (it's not an environment variable in this case; it's passed as a flag)

**Comment by jacobkahn** [comment]
Closing for now. You can reopen if you're still having trouble.
