### ISSUE TITLE
std::runtime_error - missing header

### ISSUE THREAD

**Issue by hwpfeil** [facebookresearch/flashlight#175]
Missing header in
  flashlight/lib/common/String.h
  flashlight/lib/text/decoder/lm/LM.h
    generates g++ v10.2 compile error: ‘runtime_error’ is not a member of ‘std’
Fix:
  Add   
    `#include <stdexcept>`
      to the declaration section of both files.

**Comment by tlikhomanenko** [comment]
Thanks for pointing, will send the fix for it!
