### ISSUE TITLE
Cmake Build Issue

### ISSUE THREAD

**Issue by rockiram** [facebookresearch/flashlight#178]
Hi,

I tried setting up flashlight i my ubuntu 18.04 Desktop. But facing following build issue.

Help me in solving this!!

ram@linux:~/flashlight/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DFL_BACKEND=CPU -DFL_LIBRARIES_USE_CUDA=OFF -Wno-dev
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) (Required is at least version "1.10.0")
-- googletest not found - will download and build from source
libraries criterions are not implemented for non-CUDA backends
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: /usr/lib/x86_64-linux-gnu/libiomp5.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_gf_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;/usr/lib/x86_64-linux-gnu/libiomp5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so)
-- FFTW found
-- Looking for KenLM
-- Using kenlm library found in /home/ram/packages/kenlm/build/lib/libkenlm.a
-- Using kenlm utils library found in /home/ram/packages/kenlm/build/lib/libkenlm.a
-- kenlm lm/model.hh found in /home/ram/packages/kenlm/build/lm
-- Found kenlm (include: /home/ram/packages/kenlm, library: /home/ram/packages/kenlm/build/lib/libkenlm.a;/home/ram/packages/kenlm/build/lib/libkenlm_util.a)
-- FL_BACKEND is not CUDA - forcing FL_LIBRARIES_USE_CUDA to OFF
-- ArrayFire found (include: /usr/local/include, library: ArrayFire::afopencl)
-- Could NOT find cereal (missing: cereal_INCLUDE_DIRS) 
-- cereal NOT found. Will download from source
-- MKL found
-- MKLDNN headers not found; please set CMAKE_INCLUDE_PATH or MKLDNN_ROOT, or MKLDNN_INC_DIR
-- MKLDNN library not found; please set CMAKE_LIBRARY_PATH or MKLDNN_ROOT, or MKLDNN_LIB_DIR
-- Using MKL with MKL-DNN
-- MKLDNN found
-- Will build flashlight contrib assets.
-- Gloo found
-- NCCL not found
-- MPI_VERSION found:  3.1
-- MPI_CXX found
-- MPI_CXX compile flags: -pthread
-- MPI_CXX include path: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_CXX LINK flags path: -L/usr/lib -pthread
-- MPI_CXX libraries: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- MPI_C found
-- MPI_C compile flags: -pthread
-- MPI_C include path: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_C LINK flags path: -L/usr/lib -pthread
-- MPI_C libraries: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- GLOG found
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- GFLAGS found
-- OpenMP found
-- Required SndFile dependency Ogg found.
-- Required SndFile dependency Vorbis found.
-- Required SndFile dependency VorbisEnc found.
-- Required SndFile dependency FLAC found.
-- Found libsndfile: (lib: /usr/local/lib/libsndfile.so include: /usr/local/include
-- libsndfile found.
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/ram/flashlight/MKLDNN_INCLUDE_DIR
   used as include directory in directory /home/ram/packages/flashlight
MKLDNN_LIBRARY
    linked by target "flashlight" in directory /home/ram/packages/flashlight

CMake Error in CMakeLists.txt:
  Target "flashlight" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/ram/flashlight/MKLDNN_INCLUDE_DIR-NOTFOUND"

  which is prefixed in the source directory.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by rockiram** [comment]
Hi,

The issue is fixed. I install mkl-dnn library.

Thank you

**Comment by NumanElahii** [comment]
Hi  @rockiram. How did u resolve the other issue. 
From Installing MKL-DNN i fixed other error.
 but these error are now remaning. 

-- gtest found: (include: /usr/local/include, lib: /usr/local/lib/libgtest.so;/usr/local/lib/libgtest_main.so
libraries criterions are not implemented for non-CUDA backends
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /home/numanelahi/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /home/numanelahi/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /home/numanelahi/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: /home/numanelahi/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_intel_thread: /home/numanelahi/intel/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /home/numanelahi/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /home/numanelahi/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /home/numanelahi/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /home/numanelahi/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /home/numanelahi/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_intel_thread: /home/numanelahi/intel/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /home/numanelahi/intel/mkl/lib/intel64/libmkl_core.so
--   Library iomp5: not found
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf_lp64: /home/numanelahi/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /home/numanelahi/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /home/numanelahi/intel/mkl/lib/intel64/libmkl_core.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf_lp64: /home/numanelahi/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_intel_thread: /home/numanelahi/intel/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /home/numanelahi/intel/mkl/lib/intel64/libmkl_core.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: /home/numanelahi/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /home/numanelahi/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /home/numanelahi/intel/mkl/lib/intel64/libmkl_core.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel_lp64: /home/numanelahi/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_intel_thread: /home/numanelahi/intel/mkl/lib/intel64/libmkl_intel_thread.so
--   Library mkl_core: /home/numanelahi/intel/mkl/lib/intel64/libmkl_core.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m]
--   Library mkl_intel: not found
-- Checking for [mkl_gf_lp64 - mkl_sequential - mkl_core - m]
--   Library mkl_gf_lp64: /home/numanelahi/intel/mkl/lib/intel64/libmkl_gf_lp64.so
--   Library mkl_sequential: /home/numanelahi/intel/mkl/lib/intel64/libmkl_sequential.so
--   Library mkl_core: /home/numanelahi/intel/mkl/lib/intel64/libmkl_core.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- MKL library found
-- CBLAS found (include: /home/numanelahi/intel/mkl/include, library: /home/numanelahi/intel/mkl/lib/intel64/libmkl_gf_lp64.so;/home/numanelahi/intel/mkl/lib/intel64/libmkl_sequential.so;/home/numanelahi/intel/mkl/lib/intel64/libmkl_core.so;/usr/lib/x86_64-linux-gnu/libm.so)
-- FFTW found
-- Looking for KenLM
-- Using kenlm library found in /home/numanelahi/kenlm/build/lib/libkenlm.a
-- Using kenlm utils library found in /home/numanelahi/kenlm/build/lib/libkenlm.a
-- kenlm lm/model.hh found in /home/numanelahi/kenlm/lm/model.hh
-- Found kenlm (include: /home/numanelahi/kenlm, library: /home/numanelahi/kenlm/build/lib/libkenlm.a;/home/numanelahi/kenlm/build/lib/libkenlm_util.a)
-- FL_BACKEND is not CUDA - forcing FL_LIBRARIES_USE_CUDA to OFF
-- ArrayFire found (include: /home/numanelahi/arrayfire/include, library: ArrayFire::afcuda)
-- Could NOT find cereal (missing: cereal_INCLUDE_DIRS) 
-- cereal NOT found. Will download from source
-- MKL found
-- A library with BLAS API found.
-- MKLDNN headers found in /usr/local/include
-- Using MKLDNN library found in /usr/local/lib/libmkldnn.so
-- Using MKL with MKL-DNN
-- MKLDNN found
-- Will build flashlight contrib assets.
-- Gloo found
-- NCCL not found
-- MPI_VERSION found:  3.1
-- MPI_CXX found
-- MPI_CXX compile flags: -pthread
-- MPI_CXX include path: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_CXX LINK flags path: -pthread
-- MPI_CXX libraries: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- MPI_C found
-- MPI_C compile flags: -pthread
-- MPI_C include path: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_C LINK flags path: -pthread
-- MPI_C libraries: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- GLOG found
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- GFLAGS found
-- OpenMP found
-- Required SndFile dependency Ogg found.
-- Required SndFile dependency Vorbis found.
-- Required SndFile dependency VorbisEnc found.
-- Required SndFile dependency FLAC found.
-- Found libsndfile: (lib: /usr/lib/x86_64-linux-gnu/libsndfile.so include: /usr/include
-- libsndfile found.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/numanelahi/flashlight/build

**Comment by PeiyuChen1005** [comment]
Here is the CUDA BACKEND ERROR:
```
running install
running bdist_egg
running egg_info
writing flashlight.egg-info/PKG-INFO
writing dependency_links to flashlight.egg-info/dependency_links.txt
writing top-level names to flashlight.egg-info/top_level.txt
package init file 'flashlight/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
reading manifest file 'flashlight.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'flashlight.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
-- -rdynamic supported.
-- The CUDA compiler identification is NVIDIA 11.2.152
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
CMake Error at cmake/CUDAUtils.cmake:12 (message):
  CUDA required to build CUDA backend
Call Stack (most recent call first):
  CMakeLists.txt:100 (include)


-- Configuring incomplete, errors occurred!
See also "/home/pychen/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
See also "/home/pychen/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    setup(
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 105, in build_extensions
    subprocess.check_call(
  File "/home/pychen/anaconda3/envs/fairseq/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/pychen/flashlight', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/pychen/flashlight/bindings/python/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/pychen/anaconda3/envs/fairseq/bin/python3', '-DFL_BUILD_STANDALONE=OFF', '-DBUILD_SHARED_LIBS=ON', '-DFL_BUILD_LIBRARIES=ON', '-DFL_BUILD_CORE=OFF', '-DFL_BUILD_TESTS=OFF', '-DFL_BUILD_EXAMPLES=OFF', '-DFL_BACKEND=CUDA', '-DFL_LIBRARIES_BUILD_FOR_PYTHON=ON', '-DFL_LIBRARIES_USE_CUDA=ON', '-DFL_LIBRARIES_USE_KENLM=ON', '-DFL_LIBRARIES_USE_MKL=ON', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```
