### ISSUE TITLE
make test Failed

### ISSUE THREAD

**Issue by samwellgao** [facebookresearch/flashlight#18]
Test project /home/ls/flashlight/build
    Start 1: AutogradTest
1/7 Test #1: AutogradTest .....................   Passed   22.34 sec
    Start 2: OptimTest
2/7 Test #2: OptimTest ........................   Passed    0.94 sec
    Start 3: ModuleTest
3/7 Test #3: ModuleTest .......................   Passed    2.80 sec
    Start 4: SerializationTest
4/7 Test #4: SerializationTest ................   Passed    5.70 sec
    Start 5: DatasetTest
5/7 Test #5: DatasetTest ......................***Failed    1.30 sec
    Start 6: MeterTest
6/7 Test #6: MeterTest ........................   Passed    0.86 sec
    Start 7: AllReduceTest
7/7 Test #7: AllReduceTest ....................***Exception: Other  0.94 sec

71% tests passed, 2 tests failed out of 7

Total Test time (real) =  34.88 sec

The following tests FAILED:
	  5 - DatasetTest (Failed)
	  7 - AllReduceTest (OTHER_FAULT)
Errors while running CTest
Makefile:127: recipe for target 'test' failed
make: *** [test] Error 8

When I use "make test" command,the DatasetTest was failed.What modifications should I do to make the test process work?

**Comment by jacobkahn** [comment]
@samwellgao — we have some fixes for these ready that we'll send very shortly. What OS are you using to build/run?

**Comment by samwellgao** [comment]
OS：Ubuntu16.04

**Comment by jacobkahn** [comment]
@samwellgao — can you try again, pulling and rebuilding from master? We recently sent some fixes which should disable a flakey test or two. If things are still failing, can you run those test binaries manually (from your build directory, run `./tests/DatasetTest`) so we can see which specific tests are failing?

**Comment by samwellgao** [comment]
5/7 Test #5: DatasetTest ......................   Passed    1.04 sec
Thank you!
