### ISSUE TITLE
Compilation error for StringTest, SystemTest and DictTest

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#183]
### Bug Description
Just a compilation error with some xTest.cpp : 
`[ 12%] Building CXX object lib/test/CMakeFiles/StringTest.dir/common/StringTest.cpp.o
g++  -DFL_LIBRARIES_USE_CUDA -I/usr/local/cuda/include -Irepos/flashlight -Irepos/flashlight/release/googletest/src/gtest/googletest/include -Irepos/flashlight/release/googletest/src/gtest/googlemock/include -Irepos/flashlight/.. -I/usr/include/x86_64-linux-gnu  -O3 -DNDEBUG   -pthread -std=gnu++11 -o CMakeFiles/StringTest.dir/common/StringTest.cpp.o -c repos/flashlight/lib/test/common/StringTest.cpp
flashlight/lib/test/common/StringTest.cpp:11:26: fatal error: glog/logging.h: No such file or directory
 #include <glog/logging.h>
`

#### Reproduction Steps
- Any configurations or custom setup : default ubuntu, glog-dev just not installed in the OS
- Commands to run: cmake && make

### Platform and Hardware
ubuntu 18, gcc6

#### Additional Context
There is a find glog in the asr cmake script:
find_package(GLOG REQUIRED)
but none in 
lib/test/CMakeLists.txt
Adding a find glog there would at least early stop at cmake time warning that unittests do need glog.
That being said, glog does not seem to be needed by StringTest, SystemTest, ... so just removing the include seems to fix this issue.

**Comment by jacobkahn** [comment]
@WilliamTambellini — as far as I can tell, there's no glog stuff being used in `StringTest`. Do you want to send a PR to remove the `include`? If it doesn't compile and glog is used in some way, we should remove it, since we don't want `flashlight/lib` to have any dependencies. Feel free to also remove those things in your PR.

**Comment by WilliamTambellini** [comment]
Fixed by
https://github.com/facebookresearch/flashlight/pull/188
