### ISSUE TITLE
Link failure when FL_BUILD_CONTRIB=OFF

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#185]
### Bug Description
Just a link failure when building SequentialBuilderTest.cpp if FL_BUILD_CONTRIB=OFF
SequentialBuilder.cpp:(.text+0x18a2): undefined reference to `fl::Transformer...
....

#### Reproduction Steps
cmake -DFL_BUILD_CONTRIB=OFF
make

### Platform and Hardware
Linux, gcc6

#### Additional Context
SeqBuilder does need some contribs in flashlight/ext/common/*.cpp which are excluded when FL_BUILD_CONTRIB=OFF
A solution: skip flashlight/ext/test/ meaning SequentialBuilderTest.cpp when FL_BUILD_CONTRIB=OFF

**Comment by tlikhomanenko** [comment]
Thanks for pointing it! Will work on it.

**Comment by WilliamTambellini** [comment]
Fixed by
https://github.com/facebookresearch/flashlight/pull/188

**Comment by tlikhomanenko** [comment]
Thank you so much!
