### ISSUE TITLE
Not clear error message "CUDA required to build CUDA backend" when I try to build with CPU as backend

### ISSUE THREAD

**Issue by manojmsrit** [facebookresearch/flashlight#193]
I am trying to build flashlight with all necessary dependencies on my local machine (macOS). I installed all the necessary dependencies which are mentioned in this link [https://fl.readthedocs.io/en/latest/installation.html]. After all the successful installation of the dependencies, I am not able to build flashlight with the cmake error "CUDA required to build CUDA backend", when I try to build with the command "cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU"

Any suggestions or help is appreciated. Thank you in advance.

![Uploading Screen Shot 2020-10-06 at 10.38.15 AM.png…](Error Screenshot)

**Comment by tlikhomanenko** [comment]
could you point which commit of flashlight are you using?

**Comment by WilliamTambellini** [comment]
@manojmsrit 
CUDAUtils.cmake
searches for cuda with
find_package(CUDA 9.2 QUIET)
which is searching for cuda from the location of nvcc:
if
$ which nvcc
 returned 1
then cuda not normally installed. 
Fix that or perhaps try to set CUDA_TOOLKIT_ROOT_DIR:
https://cmake.org/cmake/help/v3.12/module/FindCUDA.html?highlight=cuda

**Comment by jacobkahn** [comment]
We've changed how the CPU and CUDA backends build/this shouldn't happen anymore. CMake >= 3.10 should also give better warnings as to what's wrong when finding nvcc/CUDA components. Feel free to reopen if there are still problems.
