### ISSUE TITLE
Perceptron example throws error

### ISSUE THREAD

**Issue by paiforsyth** [facebookresearch/flashlight#20]
Hi. Thanks for this library.  I installed flashlight using Arrayfire 3.6.2 in a docker container with ubuntu 18, cudnn7, and Cuda 10. I then built and ran the Perceptron example and got the following error:

/examples/build# ./Perceptron 
ArrayFire v3.6.2 (CUDA, 64-bit Linux, build dc38ef1)
Platform: CUDA Toolkit 10, Driver: 410.48
[0] Quadro P5000, 16279 MB, CUDA Compute 6.1
terminate called after throwing an instance of 'std::invalid_argument'
  what():  tensor for TensorDataset can't be 1-D or empty
Aborted (core dumped)

(My docker container is built from this Dockerfile https://github.com/paiforsyth/bin_fldocker/blob/master/Dockerfile which is based on an image from this Dockerfile   https://github.com/paiforsyth/af_bin_docker/blob/master/Dockerfile  )

**Comment by vineelpratap** [comment]
Hi, 
Thanks for reporting the issue. Fixed it in https://github.com/facebookresearch/flashlight/commit/d63f1043bd771f1c240d108aa86ac5fbd1bd554f
