### ISSUE TITLE
CTC Decoder test

### ISSUE THREAD

**Issue by vishnu-hue** [facebookresearch/flashlight#207]
int compareNoScoreStates(const LexiconDecoderState* node) const {
    int lmCmp = lmState->compare(node->lmState);
    if (lmCmp != 0) {
      return lmCmp > 0 ? 1 : -1;
    } else if (lex != node->lex) {
      return lex > node->lex ? 1 : -1;
    } else if (token != node->token) {
      return token > node->token ? 1 : -1;
    } else if (prevBlank != node->prevBlank) {
      return prevBlank > node->prevBlank ? 1 : -1;
    }
    return 0;}
This is the comparison used  before the merging the same candidates, in this comparison the candidate that end blank and the candidate that end without blank are considered different but for example if there are two labels 'thee' and 'the_' both represents the same word 'the' but as per this comparison they are considered different.This type of comparison will help when the same character has to be repeated to form the word like the repeated character 'e' in the word 'three'. For now i am comparing the output of this decoder with [https://github.com/parlance/ctcdecode](url), the outputs are different. So is there a test for the CTC Decoder.

**Comment by avidov** [comment]
@tlikhomanenko, @xuqiantong will you please comment about this decoder change ?

**Comment by xuqiantong** [comment]
Hey, you link seems to be broken. But you can probably use any of the recipes in https://github.com/facebookresearch/wav2letter/tree/master/recipes/sota/2019/librispeech as ground truth, to test your decoder.
