### ISSUE TITLE
<unk> cause training crash

### ISSUE THREAD

**Issue by zjuturtle** [facebookresearch/flashlight#210]
### Bug Description
In app/asr(previously wav2letter++), when I try to train data with "\<unk\>" token, I'll got crash on [following code](https://github.com/facebookresearch/flashlight/blob/1b6eb18f1747078368c27fcad81e4bb5e338c7fd/app/asr/data/Utils.cpp#L46)
```
//app/asr/data/Utils.cpp

  auto lit = lexicon.find(word);
  if (lit != lexicon.end()) {
    if (lit->second.size() > 1 &&
        targetSamplePct >
            static_cast<float>(std::rand()) / static_cast<float>(RAND_MAX)) {
      return lit->second[std::rand() % lit->second.size()];
    } else {
    // crash here, when encountering word "<unk>". Because lit->second is empty.
      return lit->second[0];
    }
```

After some study, following is what I got:

In .tokens/.lexicon file generation(use `utilities/prepare_librispeech_wp_and_official_lexicon.py` from wav2letter++ repo), we explicitly exclude "\<unk\>", so we do not have "\<unk\>" in .tokens/.lexicon file

And before training, we first load lexicon file, create a LexiconMap object. In [load operation](https://github.com/facebookresearch/flashlight/blob/1b6eb18f1747078368c27fcad81e4bb5e338c7fd/lib/text/dictionary/Utils.cpp#L54), we explicitly add "\<unk\>" to LexiconMap and set its spelling empty. Why set "\<unk\>" spelling to empty?  That's the crash reason. 

```
  // Insert unknown word. Note kUnkToken="<unk>"
  lexicon[kUnkToken] = {};
```

Then we create Dictionary from LexiconMap object, also set Dictionary's defaultIndex to "\<unk\>" index.

So when encountering "\<unk\>", it will just crash. I think set "\<unk\>" spelling to "\<unk\>"  will solve this problem

**Comment by avidov** [comment]
@xuqiantong do you know why we set the <unk> to empty ?

**Comment by zjuturtle** [comment]
Anyone? Got some suggestions or explanation?

**Comment by xuqiantong** [comment]
Yea, indeed, your case is reproducible. But could you tell us why do you want to have exactly <unk> token in the transcriptions? Actually, if you look at the logic right below in https://github.com/facebookresearch/flashlight/blob/1b6eb18f1747078368c27fcad81e4bb5e338c7fd/app/asr/data/Utils.cpp#L51-L66, you can see that we support to either ignore those unknown words or fall back to use letters as their spelling. 

So, why do you want to include <unk> in targets?

**Comment by zjuturtle** [comment]
I got it. So what is your suggestion if we have '<unk>' token in training data? Is it OK just ignore it? Or maybe we should take a special strategy about it?

**Comment by xuqiantong** [comment]
Seems like \<unk\> is not showing up in the comments. :p 

But yea, I think it is OK to simply ignore those tokens, by either removing them completely or keeping them as they are originally in targets. 

Closing for now. Feel free to reopen this issue, when it becomes a major use case.
