### ISSUE TITLE
nvcc fatal: Unsupported gpu architecture 'compute_30'

### ISSUE THREAD

**Issue by go-dockly** [facebookresearch/flashlight#213]
### Bug Description
nvcc fatal   : Unsupported gpu architecture 'compute_30'

How can I pass compute_61 as nvcc flag which should be supported by my card GTX 1050

#### Reproduction Steps
[Steps to reproduce. Please include, if needed for your issue:
- Any configurations or custom setup
master branch
- Commands to run
cmake .. -DCMAKE_BUILD_TYPE=Release -DFL_BACKEND=CUDA -DFL_BUILD_DISTRIBUTED=ON -DFL_BUILD_CONTRIB=OFF -DFL_BUILD_TESTS=OFF -DFL_BUILD_EXAMPLES=OFF -DFL_LIBRARIES_USE_MKL=OFF
make -j4
make install

Error
`[  1%] Building NVCC (Device) object CMakeFiles/fl-libraries-cuda.dir/lib/sequence/criterion/cuda/fl-libraries-cuda_generated_ViterbiPath.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at fl-libraries-cuda_generated_ViterbiPath.cu.o.Release.cmake:220 (message):
  Error generating
  /home/fb/flashlight/build/CMakeFiles/fl-libraries-cuda.dir/lib/sequence/criterion/cuda/./fl-libraries-cuda_generated_ViterbiPath.cu.o`

### Platform and Hardware
Ubuntu 20.2
GeForce GTX 1050 (455.23.05)    
CUDA: 11.1
NVCC: 11.1.74
Cmake: 3.16.3

**Comment by alealv** [comment]
It's an issue because of CUDA 11. Look [here](https://github.com/facebookresearch/flashlight/issues/198)

I need to make the MR with changes.

**Comment by tlikhomanenko** [comment]
@alealv would be happy if you prepare the PR with all your fixes/findings on this.

**Comment by jacobkahn** [comment]
This should be fixed in the aforementioned commits. Feel free to reopen if you're still having problems with CUDA compute versions.
