### ISSUE TITLE
[Transformer and MultiHeadAttention modules]

### ISSUE THREAD

**Issue by lqniunjunlper** [facebookresearch/flashlight#217]
### Feature Description
[Transformer and MultiHeadAttention modules]

#### Use Case
[Transformer-based models]

#### Additional Context
[Add any additional information here]

**Comment by tlikhomanenko** [comment]
we have it here https://github.com/facebookresearch/flashlight/blob/master/flashlight/fl/contrib/modules/Transformer.cpp.

**Comment by lqniunjunlper** [comment]
@tlikhomanenko Thanks!
