### ISSUE TITLE
MPI not found 

### ISSUE THREAD

**Issue by tiru1930** [facebookresearch/flashlight#23]
-- MPI not found
CMake Error at flashlight/distributed/CMakeLists.txt:65 (message):
  MPI_C and MPI_CXX not found; required to build flashlight distributed
Call Stack (most recent call first):
  CMakeLists.txt:229 (include)

-- Configuring incomplete, errors occurred!
See also "/home/epbot/speechtotext/flashlight/build/CMakeFiles/CMakeOutput.log".
See also "/home/epbot/speechtotext/flashlight/build/CMakeFiles/CMakeError.log".

though my system has mpi , 

 mpiexec --version
mpiexec (OpenRTE) 1.10.2

Report bugs to http://www.open-mpi.org/community/help/
#46~16.04.1-Ubuntu SMP
google cloud instance

**Comment by tiru1930** [comment]
sudo apt-get install lam4-dev libmpich-dev libopenmpi-dev

**Comment by Geordy-La-Forge** [comment]
The same issue occured to me again (ArchLinux). I was able to compile with an older version of cmake (3.8.2). I guess the FindOpenMP module got extended and is not backwards compatible.
