### ISSUE TITLE
 CUDNN required to build CUDA backend  But I have installed CUDA

### ISSUE THREAD

**Issue by xwuShirley** [facebookresearch/flashlight#251]
(pytorch-conda) user@mymachine:~/flashlight/build$ sudo cmake .. -DCMAKE_BUILD_TYPE=Release -DCRITERION_BACKEND=CUDA -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda

-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) (Required is at least version "1.10.0")
-- googletest not found - will download and build from source
-- Will build flashlight libraries.
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: not found
-- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf_lp64: not found
-- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_gf - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_gf: not found
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /opt/lib64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: not found
-- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m]
--   Library mkl_intel_lp64: /opt/lib64/libmkl_intel_lp64.so
--   Library mkl_intel_thread: /opt/lib64/libmkl_intel_thread.so
--   Library mkl_core: /opt/lib64/libmkl_core.so
--   Library iomp5: /opt/lib64/libiomp5.so
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
-- MKL library found
-- CBLAS found (include: MKL_INCLUDE_DIR-NOTFOUND, library: /opt/lib64/libmkl_intel_lp64.so;/opt/lib64/libmkl_intel_thread.so;/opt/lib64/libmkl_core.so;/opt/lib64/libiomp5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so)
-- Could NOT find FFTW3 (missing: FFTW3_DIR)
-- FFTW found
-- Looking for KenLM
-- Using kenlm library found in /home/kenlm/build/lib/libkenlm.a
-- Using kenlm utils library found in /home/kenlm/build/lib/libkenlm.a
-- kenlm lm/model.hh found in /home/kenlm/lm/model.hh
-- Found kenlm (include: /home/kenlm, library: /home/kenlm/build/lib/libkenlm.a;/home/kenlm/build/lib/libkenlm_util.a)
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_70,code=compute_70-gencodearch=compute_75,code=compute_75
-- Will build flashlight core and extensions.
-- ArrayFire found (include: /opt/include, library: ArrayFire::afcuda)
-- Found cereal
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- Will build flashlight contrib assets.
CMake Warning (dev) at flashlight/fl/common/CMakeLists.txt:19 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "flashlight" has a relative path.
Call Stack (most recent call first):
  flashlight/fl/CMakeLists.txt:52 (include)
  CMakeLists.txt:235 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at flashlight/fl/autograd/CMakeLists.txt:11 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  An interface source of target "flashlight" has a relative path.
Call Stack (most recent call first):
  flashlight/fl/CMakeLists.txt:55 (include)
  CMakeLists.txt:235 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- CUDNN libname: libcudnn.so;libcudnn.dylib;cudnn64
-- CUDNN not found
CMake Error at flashlight/fl/autograd/CMakeLists.txt:56 (message):
  CUDNN required to build CUDA backend
Call Stack (most recent call first):
  flashlight/fl/CMakeLists.txt:55 (include)
  CMakeLists.txt:235 (include)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/flashlight/MKL_INCLUDE_DIR
   used as include directory in directory /home/flashlight

-- Configuring incomplete, errors occurred!
See also "/home/flashlight/build/CMakeFiles/CMakeOutput.log".
See also "/home/flashlight/build/CMakeFiles/CMakeError.log".

**Comment by tlikhomanenko** [comment]
could you try to build outside your conda env first?

**Comment by alealv** [comment]
Hi [cuDNN](
https://developer.nvidia.com/cudnn) doesn't come with CUDA, you need to install it;
