### ISSUE TITLE
RNN classification example

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#252]
### Feature Description
Would you mind if I add an example of rnn classification similar to : 
https://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial.html
?
#### Use Case
Classification of variable length sequences.

#### Additional Context
There is a rnnlm example but no rnn classification.

**Comment by tlikhomanenko** [comment]
Yep, sure. This would be very helpful!
