### ISSUE TITLE
KENLM_ROOT_DIR doesn't work if it points to the installation directoy

### ISSUE THREAD

**Issue by alealv** [facebookresearch/flashlight#253]
### Bug Description
If the env variable `KENLM_ROOT_DIR` points to the Kenlm installation directory instead of the git working copy it fails to find the required components. This is caused because when installing Kelnm the includes are located in `include/kenlm` (check [here](https://github.com/kpu/kenlm/blob/master/CMakeLists.txt#L107)).
 
#### Reproduction Steps
```sh
# Install other required packages
# Install Kelnm
git clone --recursive --shallow	-submodules --depth 1 https://github.com/kpu/kenlm.git
cd kenlm
cmake -B build -S . -Wno-dev -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="/opt/kenlm" -DCMAKE_POSITION_INDEPENDENT_CODE=ON
cmake --build build -j`nproc`
sudo make -C build install -j`nproc`
cd ..
export KENLM_ROOT_DIR=/opt/kenlm
export MKLROOT=/opt/intel/mkl

# Build flashlight
git clone --recursive --shallow	-submodules --depth 1 https://github.com/facebookresearch/flashlight.git
cd flashlight
cmake -B build -S . -Wno-dev -DCMAKE_BUILD_TYPE="Release" -DCMAKE_INSTALL_PREFIX="/opt/flashlight"
```

**Comment by tlikhomanenko** [comment]
does this commit solve the problem https://github.com/facebookresearch/flashlight/pull/268?

**Comment by alealv** [comment]
> does this commit solve the problem #268?

Yes. It's worth to mention that now the variable is called `KENLM_ROOT`.
