### ISSUE TITLE
Decode Seq2Seq with unexpected  hidden clear

### ISSUE THREAD

**Issue by zjuturtle** [facebookresearch/flashlight#257]
### Bug Description
I noice a [commit](https://github.com/facebookresearch/flashlight/commit/712c9a3fd0a01d1ca7f8b6f49487ea155fa0bcda) try to reduce memory usage by clear preState.hidden in advance. But it will cause unexpected crash in following decode step

https://github.com/facebookresearch/flashlight/blob/712c9a3fd0a01d1ca7f8b6f49487ea155fa0bcda/flashlight/app/asr/criterion/TransformerCriterion.cpp#L387

In normal case, buf->prevStates is a vector of TS2SState. Every TS2SState->hidden should have same size (Maybe 6 in my case?). But sometimes TS2SState->hidden is empty, that will cause crash in decode step(Because in decode step it will concatenate buf->prevStates)

I wrote a little code to demonstrate

```
// flashlight/app/asr/criterion/TransformerCriterion.cpp
      std::stringstream ss;
      for(int ii=0;ii < buf->prevStates.size();ii++) {
          auto &state = buf->prevStates[ii];
          ss<<" "<<state->hidden.size();
      }
      FL_LOG(fl::INFO) << "decode call input.dims ="<<buf->input.dims()<<", ys.size()="<<buf->ys.size()
       <<" prevStates.hidden size =["<< ss.str() << "]prevStates.size()=" <<buf->prevStates.size();

      std::tie(amScores, outStates) = criterion->decodeBatchStep(
          buf->input,
          buf->ys,
          buf->prevStates,
          buf->attentionThreshold,
          buf->smoothingTemperature);
```

The output will be like

```
I1113 09:47:35.609973 82176 TransformerCriterion.cpp:394 decode call input.dims =512 83 1 1, ys.size()=1 prevStates.hidden size =[ 0]prevStates.size()=1
I1113 09:48:48.601410 82176 TransformerCriterion.cpp:394 decode call input.dims =512 83 1 1, ys.size()=4 prevStates.hidden size =[ 6 6 6 6]prevStates.size()=4
I1113 09:48:49.637162 82176 TransformerCriterion.cpp:394 decode call input.dims =512 83 1 1, ys.size()=9 prevStates.hidden size =[ 6 6 6 6 6 6 6 6 6]prevStates.size()=9
I1113 09:48:49.658872 82176 TransformerCriterion.cpp:394 decode call input.dims =512 83 1 1, ys.size()=9 prevStates.hidden size =[ 6 6 6 6 6 6 6 6 6]prevStates.size()=9
I1113 09:48:49.684775 82176 TransformerCriterion.cpp:394 decode call input.dims =512 83 1 1, ys.size()=9 prevStates.hidden size =[ 6 6 6 6 6 6 6 6 6]prevStates.size()=9
I1113 09:48:49.727832 82176 TransformerCriterion.cpp:394 decode call input.dims =512 83 1 1, ys.size()=10 prevStates.hidden size =[ 6 6 6 6 6 6 6 6 6 6]prevStates.size()=10
I1113 09:48:49.759795 82176 TransformerCriterion.cpp:394 decode call input.dims =512 83 1 1, ys.size()=8 prevStates.hidden size =[ 0 0 6 6 6 6 6 6]prevStates.size()=8
F1113 09:48:49.763934 82176 Decode.cpp:655 Exception in thread 0
```

Note the second line from the bottom output `prevStates.hidden size =[ 0 0 6 6 6 6 6 6]`. First two prevStates's hidden vector is empty

Decode is fine in old code

#### Reproduction Steps
Run master code after this commit use decode_transformer_s2s_ngram.cfg

### Platform and Hardware
V100 16G * 8
Ubuntu with Docker

**Comment by tlikhomanenko** [comment]
Hey, thanks for reporting. I have several comments.

Here https://github.com/facebookresearch/flashlight/blob/712c9a3fd0a01d1ca7f8b6f49487ea155fa0bcda/flashlight/app/asr/criterion/TransformerCriterion.cpp#L371 we full the buffer with necessary batch of previous states. Then we call decode https://github.com/facebookresearch/flashlight/blob/712c9a3fd0a01d1ca7f8b6f49487ea155fa0bcda/flashlight/app/asr/criterion/TransformerCriterion.cpp#L384 for the full batch and then we clean up the previous state for which we computed the outputStates https://github.com/facebookresearch/flashlight/blob/712c9a3fd0a01d1ca7f8b6f49487ea155fa0bcda/flashlight/app/asr/criterion/TransformerCriterion.cpp#L398. We don't use the previous state anywhere else. So it should not cause the problem of null pointers for the previous states. However with this fix now you can run with larger beams / larger input sequences.

Could you run with commented part of code on cleaning the previous states? Do you have another behaviour?

Also cc @xuqiantong if I missed something.

**Comment by zjuturtle** [comment]
I dig a little deeper into code. Here's what I found:
The root case is because prevStates.hidden does not has the same dims. Function input parameter rawPrevStates is vector<TS2SState*>. But these TS2SState* seems share the same  pointer. That means, rawPrevStates has a lot identical TS2SState* pointer.(Is this as design or a pointer bug?)

In my case, I got 2 loop here
https://github.com/facebookresearch/flashlight/blob/712c9a3fd0a01d1ca7f8b6f49487ea155fa0bcda/flashlight/app/asr/criterion/TransformerCriterion.cpp#L363

so in the first loop end, we clear hidden
https://github.com/facebookresearch/flashlight/blob/712c9a3fd0a01d1ca7f8b6f49487ea155fa0bcda/flashlight/app/asr/criterion/TransformerCriterion.cpp#L401
will clear more than we expected.

Add a little code to demonstrate here

https://github.com/facebookresearch/flashlight/blob/712c9a3fd0a01d1ca7f8b6f49487ea155fa0bcda/flashlight/app/asr/criterion/TransformerCriterion.cpp#L398

```
for (int i = start; i < end; i++) {
        TS2SState* prevState = static_cast<TS2SState*>(rawPrevStates[i].get());
        if (prevState) {

          if (testFlag) {
            FL_LOG(fl::INFO) <<"Before clear "<<i<< " "<< rawPrevStatesDetail(rawPrevStates);
          }

          prevState->hidden.clear();
          if (testFlag) {
            FL_LOG(fl::INFO) <<"After clear "<<i<<" "<<rawPrevStatesDetail(rawPrevStates);
          }
        }
      }
```

We will get 

```
TransformerCriterion.cpp:439 Before clear 0 [ 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
38368 TransformerCriterion.cpp:444 After clear 0 [ 0 0 0 0 0 0 6 0 6 0 0 0 6 6 6 6 6 6]
```

So in second loop run, we will get `prevStates.hidden size =[ 0 0 6 6 6 6 6 6]`

**Comment by zjuturtle** [comment]
I suggest a fix for this

https://github.com/facebookresearch/flashlight/blob/712c9a3fd0a01d1ca7f8b6f49487ea155fa0bcda/flashlight/app/asr/criterion/TransformerCriterion.cpp#L398

```cpp
      std::unordered_set<TS2SState*> validPrevStateSet;
      for (int i = end;i < rawPrevStates.size();i++){
        validPrevStateSet.insert(static_cast<TS2SState*>(rawPrevStates[i].get()));
      }

      for (int i = start; i < end; i++) {
        TS2SState* prevState = static_cast<TS2SState*>(rawPrevStates[i].get());
        if (prevState && validPrevStateSet.cend() == validPrevStateSet.find(prevState)) {
          prevState->hidden.clear();
        }
      }
```

**Comment by tlikhomanenko** [comment]
Thanks for your detailed investigation, we will have a look and will try to repro and then come back to you =).

**Comment by zjuturtle** [comment]
By the way, I think there's a bug here

https://github.com/facebookresearch/flashlight/blob/75c241bede3e3c1441078c2958338351955fe6e7/flashlight/app/asr/criterion/TransformerCriterion.cpp#L362

`t` will increase during decoding, so if `t` get larger than 999,  `step` will be 0, then the while loop will become infinite loop.

**Comment by xuqiantong** [comment]
Hi @zjuturtle, thanks for spotting the bugs!

1. For the `state.hidden` bug, I think we can simply move https://github.com/facebookresearch/flashlight/blob/master/flashlight/app/asr/criterion/TransformerCriterion.cpp#L398-L403 out of this loop https://github.com/facebookresearch/flashlight/blob/master/flashlight/app/asr/criterion/TransformerCriterion.cpp#L363 and place it at the end.

2. For the `step=0` bug, we should add something like `step = max(step, 1)`. 

Please let me know your thoughts!

**Comment by zjuturtle** [comment]
For `state.hidden` bug, if we just move clear code out of the loop, I think we will lose the opportunity clear hidden in advance in the loop. Add some valid check code, it will not cost much extra time. 

Add following code before loop
https://github.com/facebookresearch/flashlight/blob/94480042ce95f49eb6067253caf39a7e6c2e4d20/flashlight/app/asr/criterion/TransformerCriterion.cpp#L363

```cpp
    // A simple bimap to recode valid clear hidden
    std::map<TS2SState*, int> validClearPtr2Index;
    std::map<int, TS2SState*> validClearIndex2Ptr;
    for (int index=0;index<rawPrevStates.size();index++){
      TS2SState* ptr = static_cast<TS2SState*>(rawPrevStates[index].get());
      auto iter = validClearPtr2Index.find(ptr);

      // Pointer exists in earlier rawPrevStates
      if (iter != validClearPtr2Index.end()){
        validClearIndex2Ptr.erase(iter->second);
        validClearPtr2Index.erase(iter);
      }
      validClearPtr2Index[ptr] = index;
      validClearIndex2Ptr[index] = ptr;
    }
    validClearPtr2Index.clear();
```

Then in the original clear code, 
https://github.com/facebookresearch/flashlight/blob/94480042ce95f49eb6067253caf39a7e6c2e4d20/flashlight/app/asr/criterion/TransformerCriterion.cpp#L398-L403

modify to

```cpp
      // clean the previous state which is not needed anymore
      // to prevent from OOM
      for (int i = start; i < end; i++) {
        auto iter = validClearIndex2Ptr.find(i);
        if (iter != validClearIndex2Ptr.end()) {
          TS2SState* prevState = static_cast<TS2SState*>(rawPrevStates[i].get());
          if (prevState) {
            prevState->hidden.clear();
          }
        }
      }
```

This fix is better than my last suggestion for speed

**Comment by tlikhomanenko** [comment]
Let us discuss your solutions and then I will send the fix (or you could do PR) =) Thanks again for reporting the issue!

**Comment by zjuturtle** [comment]
Unfortunately my computer is not allowed upload to GitHub. So PR is currently unavailable for me.

**Comment by tlikhomanenko** [comment]
@zjuturtle 

Thanks again for reporting/debugging/solving the issue. Here the fix https://github.com/facebookresearch/flashlight/pull/280, could you try it and tell if it works now for you?

**Comment by tlikhomanenko** [comment]
The PR is merged, closing the issue for now.

Feel free to reopen if there is still any problem, and please report if everything works for you now @zjuturtle
