### ISSUE TITLE
Why only MKL

### ISSUE THREAD

**Issue by danpovey** [facebookresearch/flashlight#30]
I am told (by a collaborator who is trying to install this on our grid) that this toolkit requires Intel MKL to work on CPU (while ArrayFire doesn't).  Is this true and if so, why did you make this a requirement?

**Comment by jacobkahn** [comment]
@danpovey — good question. In a nutshell, it isn't an actual dependency, and this is a mistake. I'll remove it as soon as I can given how onerous I know it is to install MKL on a cluster. Here's the full story:
- We want to take advantage of [MKL-DNN](https://github.com/intel/mkl-dnn), which has several fast CPU kernels ([some recent benchmarks](https://user-images.githubusercontent.com/11840728/49036017-8db18a80-f184-11e8-87eb-ec5706e57b77.png) without context) for common operations (convolution, pooling, batchnorm, an RNN implementation, etc). The CPU backend is still technically a work in progress, but it's nearly complete.
- MKL-DNN can be linked to needed BLAS kernels (for gemm) in one of two ways: either [directly with MKL](https://github.com/intel/mkl-dnn/#using-intel-mkl-optional) (which gives better performance on many systems and int8/int16 gemm support in MKL-DNN with MKL >= 2018), or with a standalone library included with MKL-DNN called [`mklml`](https://github.com/intel/mkl-dnn/blob/master/scripts/prepare_mkl.sh). Requiring MKL was a needless, silly way to 'force' people to use MKL over `mklml` when building MKL-DNN for their own benefit — and should definitely be removed. This is firmly a decision best made by the user.

Hope that makes sense. I'll send the change as soon as I can.
