### ISSUE TITLE
Typo in comment

### ISSUE THREAD

**Issue by danpovey** [facebookresearch/flashlight#31]
https://github.com/facebookresearch/flashlight/blob/eba3a300789a19efb6ccbce165349eb242ab56f0/flashlight/autograd/Variable.h#L247

I don't think index should be repeated.

**Comment by jacobkahn** [comment]
Fixed in https://github.com/facebookresearch/flashlight/commit/a6781136086e427402f8c4e7bb081a2b13f7b897 — thanks, @danpovey.
