### ISSUE TITLE
CMake version error during docker build from Dockerfile for wav2letter-inference with local inference-base-latest docker image

### ISSUE THREAD

**Issue by a-doering** [facebookresearch/flashlight#321]
### Bug Description
The CMake version of the wav2letter-inference-base is not high enough for the wav2letter-inference (which builds on it) when building the docker images from Dockerfile.

#### Reproduction Steps
Build wav2letter-inference from Dockerfile:

1. First build the wav2letter-inference-base --> working (`sudo docker build -f Dockerfile-Inference-Base -t wav2letter-inference-base . `)
2. Build wav2letter-inference --> fails  (`sudo docker build -f Dockerfile-Inference -t wav2letter-inference . `)
This happens in step 4/4 where KENLM is setup with Error Message:
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
 CMake 3.10 or higher is required.  You are running version 3.5.1

-- Configuring incomplete, errors occurred!
```
Customization: 
Changed `FROM wav2letter/wav2letter:inference-base-latest`
to `FROM wav2letter-inference-base:latest` in Dockerfile-Inference to build with local inference-base image.

### Platform and Hardware
Ubuntu 18.04.05, AWS p3.2xlarge.

**Comment by tlikhomanenko** [comment]
You need to fix flashlight version to the tag v0.2, the same for w2l (in the docker file) and only then run docker file build. We have refactored the code, so stable version is under tags v0.2. Soon we will publish a new version.
