### ISSUE TITLE
Is there any performance advantage of flashlight compare with pytorch when deploy the model in production-environments?

### ISSUE THREAD

**Issue by innerNULL** [facebookresearch/flashlight#328]
### Question
Is there any performance advantage of flashlight compare with pytorch when deploy the model in production-environments?  
Or do you have any internal performances data to share?

Thanks~

**Comment by jacobkahn** [comment]
@innerNULL — flashlight and PyTorch aren't competing in that sense — they're trying to do different things.

PyTorch supports a huge range of production environments (mobile, specialized hardware/inference accelerators, things with ONNX interoperability, etc), and that's a major strength of the PyTorch platform. Our goal with Flashlight isn't to support those per se. Flashlight and dependencies can be built natively which means that deploying them is a question of whatever you can deploy natively.

We don't have any anecdotes or benchmarks that we're ready to share with respect to Flashlight's performance versus PyTorch. Again, it suffices to say that they do different things well. Flashlight is intentionally built to be hackable and provide a C++-first JITtable environment. It tries to make easy things that require rebuilding your entire framework or adding custom, performant low-level computation might require.

**Comment by innerNULL** [comment]
> @innerNULL — flashlight and PyTorch aren't competing in that sense — they're trying to do different things.
> 
> PyTorch supports a huge range of production environments (mobile, specialized hardware/inference accelerators, things with ONNX interoperability, etc), and that's a major strength of the PyTorch platform. Our goal with Flashlight isn't to support those per se. Flashlight and dependencies can be built natively which means that deploying them is a question of whatever you can deploy natively.
> 
> We don't have any anecdotes or benchmarks that we're ready to share with respect to Flashlight's performance versus PyTorch. Again, it suffices to say that they do different things well. Flashlight is intentionally built to be hackable and provide a C++-first JITtable environment. It tries to make easy things that require rebuilding your entire framework or adding custom, performant low-level computation might require.

@jacobkahn Got it~thank you for reply~
