### ISSUE TITLE
[Install failed]

### ISSUE THREAD

**Issue by sooftware** [facebookresearch/flashlight#347]
### Question

I failed to install flashlight. I'd appreciate it if you told me what I did wrong or how to solve it!

#### Additional Context

- Environment: Linux, CUDA 10.1
- Command:  
```
$ git clone https://github.com/microsoft/vcpkg
$ ./vcpkg/bootstrap-vcpkg.sh
$ ./vcpkg/vcpkg install flashlight-cuda
```
  
- Error Message:
```
...
...
Building package glad[core]:x64-linux...
-- Downloading https://github.com/Dav1dde/glad/archive/de6c39e3040c987323b8ed078c36442f4fb681b3.tar.gz...
-- Extracting source /root/vcpkg/downloads/Dav1dde-glad-de6c39e3040c987323b8ed078c36442f4fb681b3.tar.gz
-- Applying patch encoding.patch
-- Using source at /root/vcpkg/buildtrees/glad/src/2f4fb681b3-78068df8f5.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /root/vcpkg/packages/glad_x64-linux/share/glad/copyright
-- Performing post-build validation
-- Performing post-build validation done
sh: 1: zip: not found
Failed to store binary cache /root/.cache/vcpkg/archives/9b/9bf0bb36beed231c2208916d0081a82e005c0dfe.zip: No such file or directory
Building package glad[core]:x64-linux... done
Installing package glad[core]:x64-linux...
Installing package glad[core]:x64-linux... done
Elapsed time for package glad:x64-linux: 4.319 s
Starting package 82/101: intel-mkl:x64-linux
Building package intel-mkl[core]:x64-linux...
CMake Error at ports/intel-mkl/portfile.cmake:15 (message):
  Could not find MKL.  Before continuing, please download and install MKL
  (20200000 or higher) from:

      https://registrationcenter.intel.com/en/products/download/3178/



  Also ensure vcpkg has been rebuilt with the latest version (v0.0.104 or
  later)
Call Stack (most recent call first):
  scripts/ports.cmake:136 (include)


Error: Building package intel-mkl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: intel-mkl:x64-linux
  Vcpkg version: 2020.11.12-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Comment by jacobkahn** [comment]
The error message is quite helpful! It says `Could not find MKL.  Before continuing, please download and install MKL https://registrationcenter.intel.com/en/products/download/3178/ `. You should do what it says! :)

**Comment by lizezheng** [comment]
I`ve installed mkl via yum
and  "ll /opt/intel/mkl" shows

**Comment by Macsim2** [comment]
Hi I'm facing to same problem..
did you reslove this error?

**Comment by risingsunomi** [comment]
> Hi I'm facing to same problem.. did you reslove this error?
Here is what I did to resolve on my system

OS: Windows 11 [Windows Feature Experience Pack 1000.22000.856.0]
WSL: Ubuntu 20.04.5 LTS
CUDA focused with GCC-10, using vcpkg

- Download the Intel oneAPI Base Tool
https://www.intel.com/content/www/us/en/develop/documentation/installation-guide-for-intel-oneapi-toolkits-linux/top/installation/install-using-package-managers/apt.html

- set the MKLROOT 
`export MKLROOT=/opt/intel/oneapi/mkl/latest`

I then ran 

`vcpkg install flashlight-cuda` 

It worked but I got another error dealing with not finding NVTX so working on that. You might not have that problem.
