### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by danpovey** [facebookresearch/flashlight#35]
The documentation seems to expect the arg and return value to be a single Variable, not a vector.  It would be nice to have the reason why it's a vector explained, and maybe point out that it would normally have one element.

https://github.com/facebookresearch/flashlight/blob/8a64ac776d910f4b20523367c9ddc5c36c22c237/flashlight/nn/modules/Module.h#L117

**Comment by ccnankai** [comment]
This framework is as simple as pytorch, and it is easy for novices to get started. But my foundation is not good, reading the source code is still a little difficult, I would like to read the deep learning framework source code, where to start. Is there a guide to small projects or books?

**Comment by vineelpratap** [comment]
Fixed now !
