### ISSUE TITLE
Training on RTX3090 CUDA 11.1 failed

### ISSUE THREAD

**Issue by zjuturtle** [facebookresearch/flashlight#357]
ArrayFire seems failed to work in current docker environment when using RTX3090

Just update `.docker/Dockerfile-CUDA-Base` base image from `nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04` to `nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04` and update ArrayFire to v3.7.3 will resolve this issue.

Tested.

**Comment by tlikhomanenko** [comment]
Thanks for reporting. We will switch base dockers to CUDA 11 as soon as we test it, this probably happens in upcoming January.

**Comment by tlikhomanenko** [comment]
https://github.com/facebookresearch/flashlight/pull/407

**Comment by tlikhomanenko** [comment]
The new docker images are landed. Closing the task.
