### ISSUE TITLE
Make test does not finish

### ISSUE THREAD

**Issue by hhadian** [facebookresearch/flashlight#37]
After compiling flashlight (with ArrayFire-no-gl-v3.6.2) using CUDA backend, I tried running make test but it takes forever and never finishes the first test. Looking at htop, `AutogradTest` is in state `S` and utilizing 0.0% CPU.

Any suggestions as what might be the issue?
Thanks

**Comment by jacobkahn** [comment]
@hhadian — this sounds like it might be a problem with ArrayFire. Can you try running the ArrayFire tests and see if they pass?

**Comment by hhadian** [comment]
I didn't build Arrayfire.
But anyway, I guess I figured it out. Seems like the prebuilt ArrayFire-no-gl-v3.6.2 was built against a higher cuda version than the one I have installed (which is 9.2). I upgraded nvidia driver to 410.xx and things are running fine now.

**Comment by WilliamTambellini** [comment]
@hhadian  Cool. The upcoming version of AF will check driver versions in order to assert the drivers are recent enough against the cuda verison.

**Comment by jacobkahn** [comment]
@hhadian @WilliamTambellini — good to know. In general, I've discouraged others from using the precompiled libraries because of issues with driver versions; glad to hear there's a fix on the way.
