### ISSUE TITLE
Issue closed without discussion in violation of code of conduct

### ISSUE THREAD

**Issue by scanlime** [facebookresearch/flashlight#376]
### Bug Description

I tried to open an issue about a high-level problem with this project's architecture, and it was closed in an apparent violation of the standards this project strives for in its own code of conduct.

#### Reproduction Steps

- Try to ask a hard question in a computer science crowd
- Notice that it's swept under the rug early monday morning by an engineer who doesn't appear qualified to address ethical or organizational issues

### Platform and Hardware

- Github issues
- Community of humans
- Institutional hubris

#### Additional Context

https://github.com/facebookresearch/flashlight/issues/375

**Comment by JoelMarcey** [comment]
Hi @scanlime. We certainly support your right to any particular viewpoints. On GitHub, however, the Flashlight project should be utilized for project-specific feedback, improvement suggestions and/or problems you are having with the project itself -- we really appreciate the feedback and discussions from the community and respond to anything actionable. We will continue to close out issues that are not project-specific and feel doing so does not violate our own code of conduct.
