### ISSUE TITLE
SGDOptimizer momentum

### ISSUE THREAD

**Issue by liancer** [facebookresearch/flashlight#38]
Hi,
I found logic differences between arrayfire-ml and arrayfire momentum
In arrayfire-ml the update code is
```
af::array &velocity = m_velocities[i];

// Regular momentum
velocity = m_mu * velocity - m_lr * grad;
 if (m_use_nesterov) {
 // Update for nesterov momentum
 data = data + velocity * m_mu  - m_lr * grad;
 } else {
data = data + velocity;
 }
```
but arrayfire change to

```
 af::array& velocity = velocities_[i];

 // Regular momentum
 velocity = mu_ * velocity + grad;
 af::eval(velocity);
 if (useNesterov_) {
 // Update for nesterov momentum
 grad += velocity * mu_;
 } else {
 grad = velocity;
 }
 }
 data = data - lr_ * grad;
```
without Nesterov, the update of data in arrayfire-ml is : 
data + mu * velocity - lr * grad
but arrayfire is 
data  - lr * mu * velocity - lr * grad

I think arrayfire-ml is correct, is herer any other consideration?
Thanks!

**Comment by jcai1** [comment]
The equation used in flashlight matches PyTorch/TensorFlow behavior. The PyTorch source makes a comment about it: https://pytorch.org/docs/stable/_modules/torch/optim/sgd.html
