### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by indifferen** [facebookresearch/flashlight#390]
Scanning dependencies of target NNSerializationTest
[ 60%] Building CXX object flashlight/fl/test/CMakeFiles/NNSerializationTest.dir/nn/NNSerializationTest.cpp.o
[ 60%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/backend/cuda/ConnectionistTemporalClassificationCriterion.cpp.o
/home/xx/flashlight/flashlight/fl/test/nn/NNSerializationTest.cpp: In lambda function:
/home/xx/flashlight/flashlight/fl/test/nn/NNSerializationTest.cpp:254:15: error: ‘remove_if’ was not declared in this scope
     str.erase(**remove_if**(str.begin(), str.end(), isspace), str.end());
               ^~~~~~~~~
/home/xx/flashlight/flashlight/fl/test/nn/NNSerializationTest.cpp:254:15: note: suggested alternative: ‘remove_ws’
     str.erase(**remove_if**(str.begin(), str.end(), isspace), str.end());
               ^~~~~~~~~
               remove_ws
[ 60%] Linking CUDA device code CMakeFiles/AutogradTest.dir/cmake_device_link.o
flashlight/fl/test/CMakeFiles/NNSerializationTest.dir/build.make:62: recipe for target 'flashlight/fl/test/CMakeFiles/NNSerializationTest.dir/nn/NNSerializationTest.cpp.o' failed
make[2]: *** [flashlight/fl/test/CMakeFiles/NNSerializationTest.dir/nn/NNSerializationTest.cpp.o] Error 1
CMakeFiles/Makefile2:2573: recipe for target 'flashlight/fl/test/CMakeFiles/NNSerializationTest.dir/all' failed
make[1]: *** [flashlight/fl/test/CMakeFiles/NNSerializationTest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 60%] Linking CXX executable AutogradTest
[ 60%] Building CXX object CMakeFiles/flashlight-app-lm.dir/flashlight/app/lm/common/Helpers.cpp.o
[ 60%] Linking CUDA device code CMakeFiles/ContribModuleTest.dir/cmake_device_link.o
[ 60%] Building CXX object CMakeFiles/flashlight-app-lm.dir/flashlight/app/lm/data/TextDataset.cpp.o
[ 60%] Linking CUDA device code CMakeFiles/ContribSerializationTest.dir/cmake_device_link.o
[ 60%] Linking CUDA device code CMakeFiles/NNUtilsTest.dir/cmake_device_link.o
[ 61%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/backend/cuda/CriterionUtils.cpp.o
[ 61%] Linking CUDA device code CMakeFiles/ModuleTest.dir/cmake_device_link.o
[ 62%] Linking CXX executable ContribSerializationTest
[ 62%] Linking CXX executable ModuleTest
[ 62%] Linking CXX executable NNUtilsTest
[ 62%] Linking CXX executable ContribModuleTest
[ 62%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/backend/cuda/ForceAlignmentCriterion.cpp.o
[ 62%] Built target NNUtilsTest
[ 62%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/backend/cuda/FullConnectionCriterion.cpp.o
[ 62%] Built target ModuleTest
[ 62%] Built target ContribModuleTest
[ 62%] Built target ContribSerializationTest
[ 62%] Built target AutogradTest
[ 63%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/CriterionUtils.cpp.o
[ 63%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/ConnectionistTemporalClassificationCriterion.cpp.o
[ 63%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/ForceAlignmentCriterion.cpp.o
[ 63%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/Seq2SeqCriterion.cpp.o
[ 63%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/TransformerCriterion.cpp.o
[ 64%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/attention/LocationAttention.cpp.o
[ 64%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/FullConnectionCriterion.cpp.o
[ 64%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/attention/ContentAttention.cpp.o
[ 64%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/attention/MultiHeadAttention.cpp.o
[ 65%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/attention/SoftWindow.cpp.o
[ 65%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/attention/MedianWindow.cpp.o
[ 65%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/attention/SoftPretrainWindow.cpp.o
[ 66%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/criterion/attention/StepWindow.cpp.o
[ 66%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/data/Sound.cpp.o
[ 66%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/data/FeatureTransforms.cpp.o
[ 66%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/data/ListFileDataset.cpp.o
[ 66%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/data/Utils.cpp.o
[ 66%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/decoder/ConvLmModule.cpp.o
[ 67%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/decoder/PlGenerator.cpp.o
[ 67%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/decoder/TranscriptionUtils.cpp.o
[ 67%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/decoder/DecodeUtils.cpp.o
[ 67%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/decoder/DecodeMaster.cpp.o
[ 67%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/runtime/Logger.cpp.o
[ 68%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/runtime/SpeechStatMeter.cpp.o
[ 69%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/runtime/Helpers.cpp.o
[ 69%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/runtime/Optimizer.cpp.o
[ 69%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/augmentation/AdditiveNoise.cpp.o
[ 69%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/augmentation/Reverberation.cpp.o
[ 69%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/augmentation/SoundEffect.cpp.o
[ 69%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/augmentation/SoundEffectConfig.cpp.o
[ 69%] Building CXX object CMakeFiles/flashlight-app-asr.dir/flashlight/app/asr/augmentation/SoundEffectUtil.cpp.o
[ 70%] Linking CXX static library libflashlight-app-asr.a
[ 70%] Built target flashlight-app-asr
[ 70%] Linking CXX static library libflashlight-app-lm.a
[ 70%] Built target flashlight-app-lm
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

ubuntu18.04
d28efbe
CUDA
gcc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
cmake version 3.10.2

**Comment by jacobkahn** [comment]
Can't repro this on this compiler setup, but this seems like a C++ 17 feature that snuck in. Sending a fix shortly.
