### ISSUE TITLE
Unable to perform inference for a long audio

### ISSUE THREAD

**Issue by abhinavkulkarni** [facebookresearch/flashlight#397]
Hi,

I am trying to run model `am_transformer_ctc_stride3_letters_300Mparams.bin` from this [README](https://github.com/facebookresearch/wav2letter/tree/master/recipes/rasr) on the 30s, 60s and 90s, 120s chunks of the same (longer) audio file and I seem to have trouble getting transcriptions for chunks more than 60s in length.

The audio file in question is uploaded [here](https://drive.google.com/file/d/1jArUxe62emNTy0An9xI5OeDg44ra5c95/view?usp=sharing). It's a small 3m audio. It's the audio version of [this](https://www.youtube.com/watch?v=hX6Cp4vNexc&t=32s) YouTube video.

I chop this audio file into multiples of 30s as follows:

```bash
ffmpeg -i cnbc.wav -ar 16000 -ab 256k -ac 1 -t 30s -f flac cnbc-30s.flac
ffmpeg -i cnbc.wav -ar 16000 -ab 256k -ac 1 -t 60s -f flac cnbc-60s.flac
ffmpeg -i cnbc.wav -ar 16000 -ab 256k -ac 1 -t 90s -f flac cnbc-90s.flac
```

I then run the transcription using following command once for 30s, 60s and 90s audio chunks:

```bash
GLOG_logtostderr=1  ./flashlight/build/bin/asr/fl_asr_tutorial_inference_ctc   \
--am_path=./am_transformer_ctc_stride3_letters_300Mparams.bin   \
--tokens_path=./tokens.txt   \
--lexicon_path=./lexicon.txt   \
--lm_path=./lm_common_crawl_small_4gram_prun0-6-15_200kvocab.bin   \
--sample_rate=16000   \
--beam_size=50   \
--beam_size_token=30   \
--beam_threshold=100   \
--lm_weight=1.5   \
--word_score=0   \
--audio_list=audio.lst
```

where `audio.lst` contains full path for `cnbc-30s.flac`, `cnbc-60s.flac`, etc. for each invokation.

I can get transcription for the 30s and 60s chunks, but not for 90s one.

Why is this the case? I have plenty of RAM (16GB) and the forwarding should work for a mere 90s audio.

Thanks!

### Platform and Hardware
Ubuntu 20.04, CUDA 10.1

**Comment by vineelpratap** [comment]
Hi, 
 Note that we use stride 3 for the acoustic models (as we use letters) compared to stride 8 (for sentence piece based models) which results in more frames being processed. Also, since you are using a large transformer network, memory usage grows quadratically to compute self attention. 
 So, this doesn't seem unreasonable. Could you try a smaller architecture ?

**Comment by abhinavkulkarni** [comment]
Hey @vineelpratap,

The memory is not a bottleneck, but perhaps results are suffering due to having to attend over too many frames.

Do you have any idea as to how to transcribe a large audio file? Processing 60s chunk independently one at a time is definitely a solution, but how do you carry context from one chunk to the next?

**Comment by vineelpratap** [comment]
> The memory is not a bottleneck

Oh okk. I misunderstood the question. Yes, the current transformer are trained to deal with max length up to 35 sec I believe. 

> how do you carry context from one chunk to the next

This needs a streaming transformer implementation (for example - https://arxiv.org/abs/2010.10759) ... this is not supported at the moment in the code base...

**Comment by abhinavkulkarni** [comment]
@vineelpratap: Do you have any idea how people were transcribing longer audios with Transformer models in the `wav2letter++` project? I tried searching for the issues but didn't find anything.

**Comment by vineelpratap** [comment]
I don't think we ever supported transcribing longer audios with transformer based models. Because our training data doesn't contain longer audio files, the model may not perform well on longer audios.

However, I would expect convolution based model not have this issue and they will work fine..

**Comment by tlikhomanenko** [comment]
We used 920 context size for the relative positional embedding in each transformer layer. One possible solution is to use sinusoidal positional embedding (we didn't experiment with it) instead of relative positional embedding. In this case you probably need to train on long audio otherwise will be again misrepresentative on positions (or use some works on limiting the context size of transformers for streaming).
