### ISSUE TITLE
Python bindings installation is throwing error

### ISSUE THREAD

**Issue by ngoel17** [facebookresearch/flashlight#399]
### Question
I was able to install flashlight but python bindings installation is throwing an error. The error is listed below. Please advise on how to resolve. Where exactly will -fPIC option be added.

#### Additional Context
    gmake[2]: Leaving directory '/home/ngoel-00171/flashlight/bindings/python/build/temp.linux-x86_64-3.8'
    gmake[2]: Entering directory '/home/ngoel-00171/flashlight/bindings/python/build/temp.linux-x86_64-3.8'
    [ 63%] Building CXX object CMakeFiles/_lib_text_decoder.dir/bindings/python/flashlight/lib/text/_decoder.cpp.o
    [ 64%] Linking CXX shared module ../../flashlight/_lib_text_dictionary.cpython-38-x86_64-linux-gnu.so
    [ 65%] Linking CXX shared module ../../flashlight/_lib_sequence_criterion.cpython-38-x86_64-linux-gnu.so
    [ 67%] Linking CXX shared module ../../flashlight/_lib_audio_feature.cpython-38-x86_64-linux-gnu.so
    gmake[2]: Leaving directory '/home/ngoel-00171/flashlight/bindings/python/build/temp.linux-x86_64-3.8'
    [ 67%] Built target _lib_text_dictionary
    gmake[2]: Entering directory '/home/ngoel-00171/flashlight/bindings/python/build/temp.linux-x86_64-3.8'
    Scanning dependencies of target TokenizerTest
    gmake[2]: Leaving directory '/home/ngoel-00171/flashlight/bindings/python/build/temp.linux-x86_64-3.8'
    gmake[2]: Entering directory '/home/ngoel-00171/flashlight/bindings/python/build/temp.linux-x86_64-3.8'
    [ 68%] Building CXX object flashlight/lib/test/CMakeFiles/TokenizerTest.dir/text/tokenizer/TokenizerTest.cpp.o
    /usr/bin/ld: libfl-libraries.a(ForceAlignmentCriterion.cu.o): warning: relocation against `_ZN87_GLOBAL__N__58_tmpxft_000026d4_00000000_7_ForceAlignmentCriterion_cpp1_ii_3b1c5a11_994714backwardKernelIdEEviiiPKiS2_PKT_PS3_S6_NS_13WorkspacePtrsIS3_EE' in read-only section `.text.startup'
    /usr/bin/ld: libfl-libraries.a(ForceAlignmentCriterion.cu.o): relocation R_X86_64_PC32 against symbol `_ZN87_GLOBAL__N__58_tmpxft_000026d4_00000000_7_ForceAlignmentCriterion_cpp1_ii_3b1c5a11_994713forwardKernelIfEEviiiPKT_PKiS5_S3_PS1_NS_13WorkspacePtrsIS1_EE' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: bad value
    collect2: error: ld returned 1 exit status
    gmake[2]: *** [CMakeFiles/_lib_sequence_criterion.dir/build.make:96: ../../flashlight/_lib_sequence_criterion.cpython-38-x86_64-linux-gnu.so] Error 1
    gmake[2]: Leaving directory '/home/ngoel-00171/flashlight/bindings/python/build/temp.linux-x86_64-3.8'
    gmake[1]: *** [CMakeFiles/Makefile2:219: CMakeFiles/_lib_sequence_criterion.dir/all] Error 2
    gmake[1]: *** Waiting for unfinished jobs....
    [ 69%] Linking CXX executable TokenizerTest
    [ 70%] Linking CXX shared module ../../flashlight/_lib_text_decoder.cpython-38-x86_64-linux-gnu.so
    gmake[2]: Leaving directory '/home/ngoel-00171/flashlight/bindings/python/build/temp.linux-x86_64-3.8'
    [ 70%] Built target TokenizerTest
    gmake[2]: Leaving directory '/home/ngoel-00171/flashlight/bindings/python/build/temp.linux-x86_64-3.8'
    [ 70%] Built target _lib_audio_feature
    gmake[2]: Leaving directory '/home/ngoel-00171/flashlight/bindings/python/build/temp.linux-x86_64-3.8'
    [ 70%] Built target _lib_text_decoder
    gmake[1]: Leaving directory '/home/ngoel-00171/flashlight/bindings/python/build/temp.linux-x86_64-3.8'
    gmake: *** [Makefile:141: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ngoel-00171/flashlight/bindings/python/setup.py", line 102, in <module>
        setup(
      File "/home/ngoel-00171/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/ngoel-00171/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/ngoel-00171/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/ngoel-00171/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ngoel-00171/anaconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/ngoel-00171/anaconda3/lib/python3.8/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/ngoel-00171/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/ngoel-00171/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/ngoel-00171/flashlight/bindings/python/setup.py", line 55, in run
        self.build_extensions()
      File "/home/ngoel-00171/flashlight/bindings/python/setup.py", line 97, in build_extensions
        subprocess.check_call(
      File "/home/ngoel-00171/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ngoel-00171/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/ngoel-00171/flashlight/bindings/python/setup.py'"'"'; __file__='"'"'/home/ngoel-00171/flashlight/bindings/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
(base) ngoel-00171@ngoel-e2e:~/flashlight/bindings/python$

**Comment by jacobkahn** [comment]
@ngoel17 can you give some more info about your platform/OS?

**Comment by ngoel17** [comment]
this one was on ubuntu 20.04 running in google cloud.

**Comment by tlikhomanenko** [comment]
we have improved python bindings and their installation with `python setup.py install` in https://github.com/facebookresearch/flashlight/pull/404 (it is landed). @ngoel17 could you try with latest master?

**Comment by tlikhomanenko** [comment]
Let me know if you still have trouble with recent master on python bindings installation.
