### ISSUE TITLE
Build from source doesn't work with AWS Deep Learning AMIs

### ISSUE THREAD

**Issue by massens** [facebookresearch/flashlight#403]
### Bug Description
Build from source should work out of the box with the standard deep learning AMIs on AWS:

<img width="1318" alt="Screenshot 2021-01-08 at 01 40 41" src="https://user-images.githubusercontent.com/15634635/103960496-8aa26a00-5152-11eb-8c67-14efbf121c1d.png">
<img width="1320" alt="Screenshot 2021-01-08 at 01 40 34" src="https://user-images.githubusercontent.com/15634635/103960505-8d9d5a80-5152-11eb-8128-76368963ad04.png">

Building from source fails with the message: 

```
$ cmake .. -DCMAKE_BUILD_TYPE=Release [options..]
[...]
-- USE_STATIC_NCCL detected. Linking against static NCCL library
CMake Error at /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find NCCL (missing: NCCL_LIBRARIES)
Call Stack (most recent call first):
  /usr/local/lib/python3.6/dist-packages/cmake/data/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindNCCL.cmake:57 (find_package_handle_standard_args)
  flashlight/fl/distributed/CMakeLists.txt:34 (find_package)
  flashlight/fl/CMakeLists.txt:58 (include)
  CMakeLists.txt:243 (include)
[...]
```

#### Reproduction Steps
- Start up one of the mentioned amis 
- Install dependencies
- Build from source 

#### Solution
The respective file is located at `/lib` not `/lib64`
<img width="508" alt="Screenshot 2021-01-08 at 01 50 26" src="https://user-images.githubusercontent.com/15634635/103961063-f5a07080-5153-11eb-93b9-ed7282efaffd.png">

This has worked for me
<img width="1239" alt="Screenshot 2021-01-08 at 01 46 30" src="https://user-images.githubusercontent.com/15634635/103960812-58ddd300-5153-11eb-824b-5dd8675cfe30.png">

Should I open a PR?

**Comment by jacobkahn** [comment]
@massens please do open a PR! It looks like the recent AMIs have changed the location of some things. Thanks for testing!
