### ISSUE TITLE
Run parameters for fl_asr_voice_activity_detection_ctc

### ISSUE THREAD

**Issue by stuta** [facebookresearch/flashlight#415]
### Question

I was able to build Flashlight and examples in OSX with some changes.

What are the run parameters when testing fl_asr_voice_activity_detection_ctc? Can I use it with pre-trained models without any training of my own?

**Comment by tlikhomanenko** [comment]
Yes, please have a look at the tutorial https://github.com/facebookresearch/flashlight/blob/master/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb (or colab https://colab.research.google.com/github/facebookresearch/flashlight/blob/master/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb), the part on vad and alignment, which is done with the transformer model. I am preparing also ASG model (convglu) which can be an alternative for vad to use. Will update as will add ASG model for vad.

**Comment by stuta** [comment]
Using those instructions I was able to call  fl_asr_voice_activity_detection_ctc in OSX. It crashes if I have more than 2 items in a vad list and sometimes even with 2 items. But it does work one file at a time.

My vad list:
```
0	../audio/116-288045-0000.flac	10.65
1	../audio/116-288045-0001.flac	8.635
2	../audio/116-288045-0002.flac	9.625
3	../audio/116-288045-0003.flac	3.66
4	../audio/116-288045-0004.flac	3.72
```

Call:
```
time ./fl_asr_voice_activity_detection_ctc -v=5 \
   --am=../models/am_transformer_ctc_stride3_letters_300Mparams.bin \
   --tokens=../models/tokens.txt \
   --lexicon=../models/lexicon.txt \
   --lm=../models/lm_common_crawl_small_4gram_prun0-6-15_200kvocab.bin \
   --test=../audio/vad.lst \
   --outpath=../vad-result
```
Thanks!

**Comment by tlikhomanenko** [comment]
Sorry, I didn't get when it crashes. Could you explain more/give repro?

**Comment by stuta** [comment]
It crashes with this in vad list:
```
1	../audio/116-288045-0001.flac	8.635
2	../audio/116-288045-0002.flac	9.625
```

It does not crash with:

```
1	../audio/116-288045-0001.flac	8.635
```

It does not crash with:
```
2	../audio/116-288045-0002.flac	9.625
```

**Comment by tlikhomanenko** [comment]
Ok, 

1) could you post here the full output you have with the crash
2) could you try to specify full paths for each audio path in the vad list?

**Comment by tlikhomanenko** [comment]
@stuta any progress?

**Comment by stuta** [comment]
Sorry, very urgent big customer case for at least a week, I'll get back to you.

**Comment by tlikhomanenko** [comment]
Closing for now, feel free to reopen when you have time and repro on the issue
