### ISSUE TITLE
NameError: name 'CriterionType' is not defined

### ISSUE THREAD

**Issue by indifferen** [facebookresearch/flashlight#416]
when i run:
python examples/speech_recognition/infer.py /checkpoint/abaevski/data/speech/libri/10h/wav2vec/raw --task audio_pretraining 
--nbest 1 --path /path/to/model --gen-subset $subset --results-path /path/to/save/results/for/sclite --w2l-decoder kenlm --lm-model /path/to/kenlm.bin --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter

/root/fairseq/examples/speech_recognition/w2l_decoder.py:42: UserWarning: flashlight python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/flashlight/tree/master/bindings/python
  "flashlight python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/flashlight/tree/master/bindings/python"
Traceback (most recent call last):
  File "examples/speech_recognition/infer.py", line 428, in <module>
    cli_main()
  File "examples/speech_recognition/infer.py", line 424, in cli_main
    main(args)
  File "examples/speech_recognition/infer.py", line 284, in main
    generator = build_generator(args)
  File "examples/speech_recognition/infer.py", line 269, in build_generator
    return W2lViterbiDecoder(args, task.target_dictionary)
  File "/root/fairseq/examples/speech_recognition/w2l_decoder.py", line 105, in __init__
    super().__init__(args, tgt_dict)
  File "/root/fairseq/examples/speech_recognition/w2l_decoder.py", line 56, in __init__
  File "examples/speech_recognition/infer.py", line 284, in main
    self.criterion_type = CriterionType.CTC
NameError: name 'CriterionType' is not defined

```
Package                Version         Location
---------------------- --------------- --------------------------------
antlr4-python3-runtime 4.8
cffi                   1.14.4
Cython                 0.29.21
dataclasses            0.8
editdistance           0.5.3
fairseq                1.0.0a0+a9f5741 /root/fairseq
flashlight             0.0.1           /root/flashlight/bindings/python
```

**Comment by tlikhomanenko** [comment]
Could you run in python just `from flashlight.lib.text.decoder import CriterionType`. Is it working for you?

**Comment by indifferen** [comment]
> Could you run in python just `from flashlight.lib.text.decoder import CriterionType`. Is it working for you?

  File "/root/flashlight/bindings/python/flashlight/lib/text/decoder.py", line 9, in <module>
    from flashlight._lib_text_decoder import (
ImportError: libkenlm_util.so: cannot open shared object file: No such file or directory

**Comment by abnerLing** [comment]
I'm having a similar issue, despite flashlight python bindings being installed correctly.

(wav2vec) root@14e6ab22f629:/home/abner/flashlight/bindings/python# pip install -e .
Obtaining file:///home/abner/flashlight/bindings/python
Installing collected packages: flashlight
Running setup.py develop for flashlight
Successfully installed flashlight


INFO:__main__:| decoding with criterion ctc
INFO:__main__:| loading model(s) from ./pretrained/wav2vec_small.pt
INFO:fairseq.data.audio.raw_audio_dataset:loaded 1, skipped 0 samples
INFO:__main__:| ./english_test/text/ test 1 examples
/home/abner/fairseq/examples/speech_recognition/w2l_decoder.py:42: UserWarning: flashlight python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/flashlight/tree/master/bindings/python
  "flashlight python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/flashlight/tree/master/bindings/python"
Traceback (most recent call last):
  File "../speech_recognition/infer.py", line 428, in <module>
    cli_main()
  File "../speech_recognition/infer.py", line 424, in cli_main
    main(args)
  File "../speech_recognition/infer.py", line 284, in main
    generator = build_generator(args)
  File "../speech_recognition/infer.py", line 269, in build_generator
    return W2lViterbiDecoder(args, task.target_dictionary)
  File "/home/abner/fairseq/examples/speech_recognition/w2l_decoder.py", line 105, in __init__
    super().__init__(args, tgt_dict)
  File "/home/abner/fairseq/examples/speech_recognition/w2l_decoder.py", line 56, in __init__
    self.criterion_type = CriterionType.CTC
NameError: name 'CriterionType' is not defined

**Comment by tlikhomanenko** [comment]
The reason that the flashlight is not imported, you have problem with flashlight installation. 

Could you specify on which commit you are installing flashlight and where is your kenlm installation?

**Comment by abnerLing** [comment]
@tlikhomanenko thank you for the response, while I already had kenlm installed it seems to have also installed it at flashlight/bindings/python/build/temp.linux-x86_64-3.6/kenlm/src/kenlm. As for the commit version, I believe its the most recent since I installed yesterday. commit 81c4d8d5ea57e9ceaa6db3b17f0861491fd31383

**Comment by indifferen** [comment]
> The reason that the flashlight is not imported, you have problem with flashlight installation.
> 
> Could you specify on which commit you are installing flashlight and where is your kenlm installation?

flashlight 81c4d8d
kenlm  /root/kenlm

**Comment by tlikhomanenko** [comment]
Some fixes on python bindings in the PR https://github.com/facebookresearch/flashlight/pull/404, but solution for now - do `export KENLM_ROOT=/root/kenlm`, remove build folder in the python binding, and reinstall again.

**Comment by tlikhomanenko** [comment]
https://github.com/facebookresearch/flashlight/pull/404 is landed. @indifferen @abnerLing could you try with the latest flashlight master that bindings are working?

**Comment by indifferen** [comment]
> #404 is landed. @indifferen @abnerLing could you try with the latest flashlight master that bindings are working?

It works. Thanks.

**Comment by abnerLing** [comment]
@tlikhomanenko everything works fine for me too.

**Comment by benam2** [comment]
I am experiencing the same error even though I recently cloned the repository. Any idea what else could be wrong? Thanks~

**Comment by benam2** [comment]
I have installed the flashlight ssucessfully but I get error while running ASR projects

```
 UserWarning: flashlight python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/flashlight/tree/master/bindings/python
  "flashlight python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/flashlight/tree/master/bindings/python"
Traceback (most recent call last):
  File "run_downstream.py", line 203, in <module>
    main()
  File "run_downstream.py", line 198, in main
    runner = Runner(args, config)
  File "/home/ai-labs-sgoudarzvand/conda_envs/sgoudarzvand_base/lib/python3.7/site-packages/s3prl/downstream/runner.py", line 47, in __init__
    self.downstream = self._get_downstream()
  File "/home/ai-labs-sgoudarzvand/conda_envs/sgoudarzvand_base/lib/python3.7/site-packages/s3prl/downstream/runner.py", line 116, in _get_downstream
    **vars(self.args)
  File "/home/ai-labs-sgoudarzvand/conda_envs/sgoudarzvand_base/lib/python3.7/site-packages/s3prl/downstream/asr/expert.py", line 100, in __init__
    self.decoder = get_decoder(decoder_args, self.train_dataset.dictionary)
  File "/home/ai-labs-sgoudarzvand/conda_envs/sgoudarzvand_base/lib/python3.7/site-packages/s3prl/downstream/asr/expert.py", line 37, in get_decoder
    return W2lKenLMDecoder(decoder_args, dictionary)
  File "/home/ai-labs-sgoudarzvand/Desktop/ASR/fairseq/examples/speech_recognition/w2l_decoder.py", line 127, in __init__
    super().__init__(args, tgt_dict)
  File "/home/ai-labs-sgoudarzvand/Desktop/ASR/fairseq/examples/speech_recognition/w2l_decoder.py", line 56, in __init__
    self.criterion_type = CriterionType.CTC
NameError: name 'CriterionType' is not defined
```
Any idea how I can fix this @tlikhomanenko . I appreciate if you can comment on this.

**Comment by Daeun-Yun** [comment]
**maybe fail to import cpuviterbipath blocks  importing criteriotype!**
I solved this error by changing the posion like this --> : 


from flashlight.lib.text.decoder import (
        CriterionType,
        LexiconDecoderOptions,
        KenLM,
        LM,
        LMState,
        SmearingMode,
        Trie,
        LexiconDecoder,
    )
    from flashlight.lib.sequence.criterion import CpuViterbiPath, get_data_ptr_as_bytes
