### ISSUE TITLE
[Is there any examples of myarch.txt for lm training]

### ISSUE THREAD

**Issue by lqniunjunlper** [facebookresearch/flashlight#417]
### Question
[How to define a fl model with arch file? ]

#### Additional Context
[Add any additional information here]

**Comment by tlikhomanenko** [comment]
The doc on this is here https://github.com/facebookresearch/flashlight/tree/master/flashlight/app/asr#writing-architecture-files, check also info under `Here, we describe how to specify different flashlight modules in the architecture files.` in this section.
