### ISSUE TITLE
Want make embeding from single wav fil

### ISSUE THREAD

**Issue by paklau99988** [facebookresearch/flashlight#427]
### Question
Have audio file has 30 seconds, want generate 6 embedings each 5 seconds, how use python no have data loader, just single wav?

**Comment by tlikhomanenko** [comment]
Sorry @paklau99988 I did understand your question. Could you be more specific, maybe with some example/pseudocode.

(Also we have python binding only for ASR featurization and beam-search decoder, not for data loader or training ASR models).

**Comment by paklau99988** [comment]
Want run inference on a single wave file.

**Comment by tlikhomanenko** [comment]
If you train acoustic model in flashlight, then please have a look at this tutorial for CTC model https://github.com/facebookresearch/flashlight/blob/master/flashlight/app/asr/tutorial/notebooks/InferenceAndAlignmentCTC.ipynb (colab link can be found here along with some docs https://github.com/facebookresearch/flashlight/tree/master/flashlight/app/asr/tutorial)

Additional docs on Viterbi WER or beam-search decoding is here https://github.com/facebookresearch/flashlight/tree/master/flashlight/app/asr#beam-search-decoder

If you train model in pytorch /tensorflow/... you can use beam-search decoder as in example here  https://github.com/facebookresearch/flashlight/blob/master/bindings/python/example/decoder_example.py#L207, where emissions are output of your model.

**Comment by tlikhomanenko** [comment]
Let me know if you need further assistance! Closing for now.
