### ISSUE TITLE
cmake failed on CPU backend

### ISSUE THREAD

**Issue by Akatsukis** [facebookresearch/flashlight#43]
Hi,

It's on Ubuntu 18.04 and I have installed ArrayFire.
I got the following errors when I want to install flashlight.

CMake Error at /usr/local/share/ArrayFire/cmake/ArrayFireConfig.cmake:131 (get_property):
  get_property given invalid argument "RELEASE".
Call Stack (most recent call first):
  CMakeLists.txt:63 (find_package)

CMake Error at /usr/local/share/ArrayFire/cmake/ArrayFireConfig.cmake:131 (get_property):
  get_property given invalid argument "RELEASE".
Call Stack (most recent call first):
  CMakeLists.txt:63 (find_package)

-- ArrayFire found (include: /usr/local/include, library: )
CMake Error at CMakeLists.txt:77 (message):
  ArrayFire CPU not found: cannot build CPU backend

-- Configuring incomplete, errors occurred!
See also "/home/akatsuki/flashlight/build/CMakeFiles/CMakeOutput.log".

**Comment by jacobkahn** [comment]
@Akatsukis — my guess is that this is an issue with how you've built ArrayFire, possibly with your specification of `CMAKE_BUILD_TYPE`. Can you paste the CMake command you used to build ArrayFire here, along with the CMake command you're using to build flashlight?

**Comment by Akatsukis** [comment]
I used `cmake .. -DCMAKE_BUILD_TYPE=Release` to build ArrayFire and used `cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU` to build flashlight.

**Comment by jacobkahn** [comment]
Ok — what OS and CMake version are you using?

**Comment by Akatsukis** [comment]
Ubuntu 18.04 and Cmake 3.10.2.

**Comment by jacobkahn** [comment]
Can you try building and installing ArrayFire with an older version of CMake (like 3.6) then try to build flashlight (also with 3.6?)

**Comment by Akatsukis** [comment]
It works. Thank you.
