### ISSUE TITLE
Installing with vcpkg: "MKL 202101 is found but 20200000 is required"

### ISSUE THREAD

**Issue by hmholen** [facebookresearch/flashlight#431]
Hi,
I am trying to install MKL with vcpkg.

I am following the readme for the dependencies.
The link given for MKL goes to the Intel oneAPI download page.
I tried both that one and the [standalone.](https://software.intel.com/content/www/us/en/develop/articles/oneapi-standalone-components.html#onemkl)
Both of them are for MKL version 2021, and I cannot find a download for 2020.

When running `./vcpkg install flashlight-cuda`, I get:

```
Starting package 1/9: intel-mkl:x64-linux
Building package intel-mkl[core]:x64-linux...
CMake Error at ports/intel-mkl/portfile.cmake:30 (message):
  MKL 202101 is found but 20200000 is required.  Please download and install
  a more recent version of MKL from:
      https://registrationcenter.intel.com/en/products/download/3178/
```
(The link leads to a page saying "We are unable to find registrations/downloads matching this request")

I am not sure if I am doing something wrong, or if the installer is not updated to the latest MKL?
Is there anything I should do?

**Comment by tlikhomanenko** [comment]
Here is the version we use in our CI for vcpkg https://github.com/facebookresearch/flashlight/blob/master/.circleci/config.yml#L191. Please give a try with it.

**Comment by hmholen** [comment]
Thanks @tlikhomanenko , that fixed the issue with MKL!

**Comment by benam2** [comment]
@tlikhomanenko I have faced with the same error. I followed your suggestion and checked my script however it is exactly like yours already. do you have any idea what else could be the reason?
Appreciate your help and time.
