### ISSUE TITLE
How to run model after building flashlight with Docker from Source

### ISSUE THREAD

**Issue by MrityunjoyS** [facebookresearch/flashlight#432]
I'm trying to train a model from scratch using flaslight. So I've tried building flaslight using docker from source following this link. 
[flaslight](https://github.com/facebookresearch/flashlight/tree/master/.docker#building-docker-images-from-source)

1. But after the docker is build, how **should I run the docker for further use. Can anyone please instruct**.

**Comment by tlikhomanenko** [comment]
Here is the docs on starting container https://github.com/facebookresearch/flashlight/tree/master/.docker, for example with CUDA backend
```
sudo docker run --runtime=nvidia --rm -itd --ipc=host --name {container name} {built image tag}
```
this starts container and then you can go to bash of the container
```
sudo docker exec -it {container name} bash
```

there you can find flashlight in the `/root/flashlight` with binaries in the `/root/flashlight/build/bin`.

**Comment by MrityunjoyS** [comment]
Hi @tlikhomanenko , thanks for your quick reply. You've been always so helpful with our doubts. I'm actually using flashlight docker with CPU, but I'm able to build it now and I've moved few step forward.
I'm trying to **fork** the  [asr model](https://github.com/facebookresearch/flashlight/tree/master/flashlight/app/asr) with below steps -->
`build/bin/asr/fl_asr_train fork /root/flashlight_explore/am_conformer_ctc_stride3_letters_25Mparams.bin --tokens=/root/flashlight_explore/w2l/am/tokens.txt --arch=/root/flashlight_explore/am_conformer_ctc_stride3_letters_25Mparams.arch --rundir=/root/flashlight_explore/save_model/ --train=/root/flashlight_explore/w2l/lists/train-clean-10.lst --valid=/root/flashlight_explore/w2l/lists/dev-clean-10.lst --batchsize=1 --lexicon=/root/flashlight_explore/w2l/am/lexicon.txt --enable_distributed=false --lr=0.0001 --lrcrit=0.0001 --logtostderr=1`

Getting below error -->

> I0122 12:58:33.029825 12636 Train.cpp:428] [Network Params: 70498735]
> I0122 12:58:33.029917 12636 Train.cpp:429] [Criterion] ConnectionistTemporalClassificationCriterion
> I0122 12:58:33.128959 12636 Train.cpp:462] [Network Optimizer] Adagrad (epsilon=1e-08)
> I0122 12:58:33.128989 12636 Train.cpp:463] [Criterion Optimizer] Adagrad (epsilon=1e-08)
> I0122 12:58:33.203048 12636 Train.cpp:1000] Shuffling trainset
> I0122 12:58:33.203301 12636 Train.cpp:1007] Epoch 1 started!
> F0122 12:58:44.604282 12636 Train.cpp:1089] Loss has NaN values. Samples - train-clean-100-103-1240-0007
> *** Check failure stack trace: ***
>     @     0x7f3fbe6230cd  google::LogMessage::Fail()
>     @     0x7f3fbe624f33  google::LogMessage::SendToLog()
>     @     0x7f3fbe622c28  google::LogMessage::Flush()
>     @     0x7f3fbe625999  google::LogMessageFatal::~LogMessageFatal()
>     @     0x563c5e466124  (unknown)
>     @     0x563c5e46c541  (unknown)
>     @     0x7f3fb22bbbf7  __libc_start_main
>     @     0x563c5e46113a  (unknown)
> Aborted (core dumped)

For audio dataset I'm using librispeech only, and for arch and bin model I'm using **am_conformer_ctc_stride3_letters_25Mparams** arch and bin file. [Conformer](https://github.com/facebookresearch/wav2letter/tree/master/recipes/rasr).

Can you please look into it. Thanks in advance.

**Comment by tlikhomanenko** [comment]
Please add the empty flag `--flagsfile=` to reset it from the forked model

**Comment by MrityunjoyS** [comment]
Thanks for the reply @tlikhomanenko . So I changed my command to this -->

`build/bin/asr/fl_asr_train fork /root/flashlight_explore/am_conformer_ctc_stride3_letters_25Mparams.bin --flagsfile= --tokens=/root/flashlight_explore/w2l/am/tokens.txt --arch=/root/flashlight_explore/am_conformer_ctc_stride3_letters_25Mparams.arch --rundir=/root/flashlight_explore/save_model/ --train=/root/flashlight_explore/w2l/lists/train-clean-10.lst --valid=/root/flashlight_explore/w2l/lists/dev-clean-10.lst --batchsize=1 --lexicon=/root/flashlight_explore/w2l/am/lexicon.txt --enable_distributed=false --lr=0.0001 --lrcrit=0.0001 --logtostderr=1`

Not getting the previous error anymore, but now the code is breaking after giving this message:

> I0124 05:58:27.639622 12682 Train.cpp:428] [Network Params: 27736863]
> I0124 05:58:27.639755 12682 Train.cpp:429] [Criterion] ConnectionistTemporalClassificationCriterion
> I0124 05:58:27.680217 12682 Train.cpp:462] [Network Optimizer] Adagrad (epsilon=1e-09)
> I0124 05:58:27.680240 12682 Train.cpp:463] [Criterion Optimizer] Adam
> I0124 05:58:27.759284 12682 Train.cpp:1000] Shuffling trainset
> I0124 05:58:27.759552 12682 Train.cpp:1007] Epoch 1 started!
> F0124 05:58:34.336992 12682 Train.cpp:1089] Loss has NaN values. Samples - train-clean-100-103-1240-0007
> *** Check failure stack trace: ***
>     @     0x7fdac0b5e0cd  google::LogMessage::Fail()
>     @     0x7fdac0b5ff33  google::LogMessage::SendToLog()
>     @     0x7fdac0b5dc28  google::LogMessage::Flush()
>     @     0x7fdac0b60999  google::LogMessageFatal::~LogMessageFatal()
>     @     0x55e01f31e124  (unknown)
>     @     0x55e01f324541  (unknown)
>     @     0x7fdab47f6bf7  __libc_start_main
>     @     0x55e01f31913a  (unknown)
> Aborted (core dumped)
> 

Is there any error in the flags I'm passing cause I've tried changing files but every time it will show some other file name and will break again. 
Please have a look in this.

**Comment by tlikhomanenko** [comment]
Now the problem that loss is Nan, you need to tweak the optimization parameters, try lower lr for example. Also could you post all log output (where flags are printed)?

**Comment by tlikhomanenko** [comment]
@MrityunjoyS any progress?

**Comment by MrityunjoyS** [comment]
Sorry @tlikhomanenko , actually shifted my work on wav2vec2.0. Have kept this on hold for a while.
