### ISSUE TITLE
11 tests failed out of 18 when using docker image

### ISSUE THREAD

**Issue by Hui-Ling** [facebookresearch/flashlight#435]
### Question

My computer is Ubuntu 18.04.5 LTS with NVidia GeForce RTX 3090. The driver version is 460.32.03 and cuda version is 11.2. Today I pulled the latest docker image (cuda-version) from docker hub and then ran test in the container, but 11 tests failed. 

The followings are the commands that I used:
sudo docker run --runtime=nvidia --rm -itd --ipc=host --name flashlight-20210124 flml/flashlight:cuda-latest
sudo docker exec -it flashlight-20210124 bash
cd /root/flashlight/build && make test

The followings are the messages I got during test:
Running tests...
Test project /root/flashlight/build
      Start  1: AutogradTest
 1/18 Test  #1: AutogradTest .....................***Exception: SegFault205.70 sec
      Start  2: DevicePtrTest
 2/18 Test  #2: DevicePtrTest ....................   Passed    1.22 sec
      Start  3: HistogramTest
 3/18 Test  #3: HistogramTest ....................   Passed    1.80 sec
      Start  4: LoggingTest
 4/18 Test  #4: LoggingTest ......................   Passed    0.75 sec
      Start  5: SerializationTest
 5/18 Test  #5: SerializationTest ................   Passed    0.73 sec
      Start  6: OptimTest
 6/18 Test  #6: OptimTest ........................***Exception: SegFault  1.28 sec
      Start  7: CachingMemoryManagerTest
 7/18 Test  #7: CachingMemoryManagerTest .........***Failed    1.24 sec
      Start  8: MemoryFrameworkTest
 8/18 Test  #8: MemoryFrameworkTest ..............   Passed    1.23 sec
      Start  9: MemoryInitTest
 9/18 Test  #9: MemoryInitTest ...................   Passed    0.79 sec
      Start 10: ModuleTest
10/18 Test #10: ModuleTest .......................***Exception: SegFault922.14 sec
      Start 11: NNSerializationTest
11/18 Test #11: NNSerializationTest ..............***Exception: SegFault206.14 sec
      Start 12: NNUtilsTest
12/18 Test #12: NNUtilsTest ......................***Failed    1.22 sec
      Start 13: DatasetTest
13/18 Test #13: DatasetTest ......................***Exception: SegFault  1.30 sec
      Start 14: DatasetUtilsTest
14/18 Test #14: DatasetUtilsTest .................   Passed    0.76 sec
      Start 15: MeterTest
15/18 Test #15: MeterTest ........................***Failed    1.22 sec
      Start 16: AllReduceTest
16/18 Test #16: AllReduceTest ....................***Exception: SegFault 53.43 sec
      Start 17: ContribModuleTest
17/18 Test #17: ContribModuleTest ................***Exception: SegFault929.90 sec
      Start 18: ContribSerializationTest
18/18 Test #18: ContribSerializationTest .........***Exception: SegFault206.50 sec

39% tests passed, 11 tests failed out of 18

Total Test time (real) = 2537.36 sec

The following tests FAILED:
	  1 - AutogradTest (SEGFAULT)
	  6 - OptimTest (SEGFAULT)
	  7 - CachingMemoryManagerTest (Failed)
	 10 - ModuleTest (SEGFAULT)
	 11 - NNSerializationTest (SEGFAULT)
	 12 - NNUtilsTest (Failed)
	 13 - DatasetTest (SEGFAULT)
	 15 - MeterTest (Failed)
	 16 - AllReduceTest (SEGFAULT)
	 17 - ContribModuleTest (SEGFAULT)
	 18 - ContribSerializationTest (SEGFAULT)
Errors while running CTest
Makefile:106: recipe for target 'test' failed
make: *** [test] Error 8

I don't know what's wrong in the container. Could you please help me to figure out the problem and fix the issue?

Thank you very much.

**Comment by tlikhomanenko** [comment]
Could you run each test individually and post here the output? For example for OptimTest?

**Comment by tlikhomanenko** [comment]
@Hui-Ling any progress on running individual tests?

**Comment by tlikhomanenko** [comment]
Closing due inactivity, please reopen if still support is needed.
