### ISSUE TITLE
Building Python Bindings (Importing flashlight) when using vcpkg

### ISSUE THREAD

**Issue by ahmadsocrat** [facebookresearch/flashlight#437]
### Question
After following your instructions for building flashlight via vcpkg install flashlight-cuda[*], flashlight was successfully built:

Building package flashlight-cuda[asr,core,fl,imgclass,lib,lm]:x64-linux...
-- Downloading https://github.com/facebookresearch/flashlight/archive/81c4d8d5ea57e9ceaa6db3b17f0861491fd31383.tar.gz -> facebookresearch-flashlight-81c4d8d5ea57e9ceaa6db3b17f0861491fd31383.tar.gz...
-- Extracting source /alt/common/vcpkg/downloads/facebookresearch-flashlight-81c4d8d5ea57e9ceaa6db3b17f0861491fd31383.tar.gz
-- Using source at /alt/common/vcpkg/buildtrees/flashlight-cuda/src/491fd31383-af14cb9c8a.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /alt/common/vcpkg/packages/flashlight-cuda_x64-linux/share/flashlight-cuda/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: /home/local/QCRI/aamr/.cache/vcpkg/archives/9c/9ca712676f968e3789761ee8aa4c06fd3b190eca.zip
Building package flashlight-cuda[asr,core,fl,imgclass,lib,lm]:x64-linux... done
Installing package flashlight-cuda[asr,core,fl,imgclass,lib,lm]:x64-linux...
Installing package flashlight-cuda[asr,core,fl,imgclass,lib,lm]:x64-linux... done
Elapsed time for package flashlight-cuda:x64-linux: 12.65 min

Total elapsed time: 1.455 h

The package flashlight-cuda:x64-linux provides CMake targets:

    find_package(flashlight-cuda CONFIG REQUIRED)
    # Note: 1 target(s) were omitted.
    target_link_libraries(main PRIVATE flashlight::flashlight flashlight::fl-libraries flashlight::flashlight-app-lm flashlight::flashlight-app-asr)

However, I am unable to import the flashlight library into python: 

>>> import flashlight
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'flashlight'

Question is, were the python bindings built with vcpkg install? How can I import the library? I tested on both Python 3.6 and Anaconda Python 3.7.

#### Additional Context
[Add any additional information here]

**Comment by tlikhomanenko** [comment]
Vcpkg is using to build flashlight. However python bindings are standalone and can be installed with `python setup.py install`, they are independent of the core flashlight and supports only libs. Please use instructions for python binding installation from here https://github.com/facebookresearch/flashlight/tree/master/bindings/python (also there is all docs on the supported things in python bindings).

**Comment by ahmadsocrat** [comment]
Hi,

Thank you, but the instructions for Python bindings are not very clear. I also would have to prepare all the dependencies again to build them (which I mainly used vcpkg to make my life easier)

And even after building the dependencies, I always get an nvcc error about an unknown option ‘-fopenmp’

**Comment by ahmadsocrat** [comment]
Finally, I could build successfully after declaring variables CMAKE_INCLUDE_PATH and CMAKE_LIBRARY_PATH before running the setup.py:
 
export CMAKE_LIBRARY_PATH=[vcpkg_installation_location]/installed/x64-linux/lib
export CMAKE_INCLUDE_PATH=[vcpkg_installation_location]/installed/x64-linux/include
 
I created a pull request #440  for that.

**Comment by tlikhomanenko** [comment]
Ohh, yep, this the right way to give a path for installation, thanks for the PR! 

At the same time for python bindings you don't need to build all dependencies and full flashlight. But whatever is simple for you. Closing the task and will merge your PR. Thanks again!
