### ISSUE TITLE
Decoder changes after April 30th

### ISSUE THREAD

**Issue by ahmadab** [facebookresearch/flashlight#44]
I have just pull the latest changes since April 30th
I am getting much worse WER and slower decoding after which
Is it possible that there has a bug introduced?

**Comment by xuqiantong** [comment]
Hi, please see the docs https://github.com/facebookresearch/wav2letter/blob/master/docs/data_prep.md and https://github.com/facebookresearch/wav2letter/blob/master/docs/decoder.md, and update your lexicon file accordingly.
