### ISSUE TITLE
Couldn't find the timestamps function in flashlight as it is used to be in wav2letter?

### ISSUE THREAD

**Issue by seantai210** [facebookresearch/flashlight#450]
### Question
In the old wav2letter package (https://github.com/facebookresearch/wav2letter/tree/v0.2), 
timestamps of each recognized word are supported when using simple_streaming_asr_example function, 
like the discussion here (https://github.com/facebookresearch/wav2letter/issues/809).

However, in the flashlight asr package (https://github.com/facebookresearch/flashlight/tree/master/flashlight/app/asr),
I couldn't find the timestamps function or a similar API. Will this useful function be provided in the future?

Thank you for any help you can provide.

**Comment by tlikhomanenko** [comment]
Thanks for the question. For now inference is living still in the wav2letter recipes https://github.com/facebookresearch/wav2letter/tree/a1c74f4d8c9c2ce6a127889f37f779dbfe36b937/recipes/streaming_convnets/inference, for example the function you refer can be found here https://github.com/facebookresearch/wav2letter/blob/a1c74f4d8c9c2ce6a127889f37f779dbfe36b937/recipes/streaming_convnets/inference/inference/examples/AudioToWords.cpp

**Comment by seantai210** [comment]
Got it, thank you, Tatiana! Case closed.
