### ISSUE TITLE
Could NOT find GMock (missing: GMock_DIR)[Your bug title]

### ISSUE THREAD

**Issue by Shridharpawar77** [facebookresearch/flashlight#452]
I am using Ubuntu 18.04

I have installed Gmock using 
sudo apt-get install -y google-mock

But when I am running the cmake command 
it throws error 

-- gtest found: (include: /usr/include, lib: /usr/lib/libgtest.a;/usr/lib/libgtest_main.a
-- Could NOT find GMock (missing: GMock_DIR)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GMock (missing: GMOCK_MAIN_LIBRARY GMOCK_LIBRARIES
  GMOCK_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGMock.cmake:30 (find_package_handle_standard_args)
  cmake/TestUtils.cmake:24 (find_package)
  CMakeLists.txt:104 (include)

-- Configuring incomplete, errors occurred!

**Comment by jacobkahn** [comment]
@Shridharpawar77 — you need `sudo apt install -y libgmock-dev` -- the package you're using doesn't actually have the shared libraries or headers needed to compile. Installing `libgmock-dev` will fix your problem.

**Comment by Recluse58** [comment]
> @Shridharpawar77 — you need `sudo apt install -y libgmock-dev` -- the package you're using doesn't actually have the shared libraries or headers needed to compile. Installing `libgmock-dev` will fix your problem.

> sudo apt install -y libgmock-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libgmock-dev

libgmock-dev is actually not available as a package.

**Comment by jacobkahn** [comment]
@Recluse58 Which OS are you on? It's available in [Ubuntu 20.04](https://packages.ubuntu.com/focal/libgmock-dev) and 18.04.

**Comment by Recluse58** [comment]
> @Recluse58 Which OS are you on? It's available in [Ubuntu 20.04](https://packages.ubuntu.com/focal/libgmock-dev) and 18.04.
> 
> You can also build it from source: https://github.com/google/googletest

 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

Yeah I am also using 18.04. But apt-get simply doesn't locateit.

**Comment by jacobkahn** [comment]
@Recluse58 the Ubuntu 18.04 package only contains the gmock source, and isn't prebuilt (https://packages.ubuntu.com/bionic/i386/google-mock/filelist), so you would still need to build from source. 

If you removed your gtest installation and clear your build directory, Flashlight will also download and build gtest and gmock for you

**Comment by Anyueanne** [comment]
> @Recluse58 the Ubuntu 18.04 package only contains the gmock source, and isn't prebuilt (https://packages.ubuntu.com/bionic/i386/google-mock/filelist), so you would still need to build from source.
> 
> If you removed your gtest installation and clear your build directory, Flashlight will also download and build gtest and gmock for you

I build googletest from source on CentOS and add bin/header into PATH. However, I also get `Could NOT find GMock (missing: Gmock_DIR)`, but it found gtest. WHY?
thanks a lot.
