### ISSUE TITLE
How to set the parameters correctly in the json config file while running the fl_asr_sfx_apply app in order to add the noise to an audio file

### ISSUE THREAD

**Issue by vchagari** [facebookresearch/flashlight#457]
### Question/Issue:
I am getting an error while running the fl_asr_sfx_apply application with a sample audio file. 

Details:
./fl_asr_sfx_apply --input=test.wav --output=output_data --config=sfx_config_filename.json

terminate called after throwing an instance of 'std::runtime_error'
  what():  readSoundEffectConfigFile(filename=sfx_config_filename.json) failed with error={JSON Parsing failed - provided NVP (type) not found}
*** Aborted at 1612510139 (unix time) try "date -d @1612510139" if you are using GNU date ***
PC: @     0x7f042f3effb7 gsignal
*** SIGABRT (@0x3ed00001f2d) received by PID 7981 (TID 0x7f044ec7ea40) from PID 7981; stack trace: ***
    @     0x7f042f3f0040 (unknown)
    @     0x7f042f3effb7 gsignal
    @     0x7f042f3f1921 abort
    @     0x7f042fde4957 (unknown)
    @     0x7f042fdeaae6 (unknown)
    @     0x7f042fdeab21 std::terminate()
    @     0x7f042fdead54 __cxa_throw
    @     0x55566db2a0bf (unknown)
    @     0x55566db23853 (unknown)
    @     0x7f042f3d2bf7 __libc_start_main
    @     0x55566db246aa (unknown)
Aborted (core dumped)

Json Config file details: (Original Config file was taken from the PR of this feature and then modified the parameter names accordingly based on the latest flashlight code. 
{
    "soundEffectChain": [
       {
            "type_": "kReverbEcho",
            "reverbEchoConfig_": {
                "initialMin_": 0.1,
                "initialMax_": 0.5,
                "rt60Min_": 1.0,
                "rt60Max_": 10.0,
                "firstDelayMin_": 0,
                "firstDelayMax_": 10,
                "jitter_": 0.1,
                "randomSeed_": 1234567
            }
        },
        {
            "type_": "kNormalize"
        }
    ]
}

**Comment by yoks** [comment]
You need to remove underscore from names, and k from types, e.g.

`{
    "soundEffectChain": [
        {
            "type": "ReverbEcho",
            "reverbEchoConfig": {
                "proba": 0.5,
                "initialMin": 0.0,
                "initialMax": 0.3,
                "rt60Min": 0.3,
                "rt60Max": 1.3,
                "firstDelayMin": 0.01,
                "firstDelayMax": 0.03,
                "repeat": 3,
                "jitter": 0.1,
                "sampleRate": 16000
            }
        },
        {
            "type": "Normalize",
            "normalizeOnlyIfTooHigh": true
        }
    ]
}`

**Comment by tlikhomanenko** [comment]
cc @avidov to improve docs on the sfx configs.
