### ISSUE TITLE
Small mistake in the Readme file for vcpkg installations

### ISSUE THREAD

**Issue by KacperKubara** [facebookresearch/flashlight#464]
### Bug Description
Hi,

In the Readme file for vcpkg installation you have:
![image](https://user-images.githubusercontent.com/33067446/107404242-5ed62380-6b06-11eb-9f0f-1b48f6790a97.png)

And in the [vcpkg readme file](https://github.com/microsoft/vcpkg#quick-start-unix), the instruction looks like:
![image](https://user-images.githubusercontent.com/33067446/107404406-8b8a3b00-6b06-11eb-96b4-5a79f3efe424.png)

I think you've just missed the binary in the vcpkg folder? If that's the case, I am happy to create a quick cosmetic PR for the Readme :)

**Comment by tlikhomanenko** [comment]
Hi @KacperKubara,

Thanks for pointing this. I think we ca standardize to the way vcpkg instructions do. What do you think @jacobkahn ?

**Comment by jacobkahn** [comment]
@KacperKubara feel free to create a PR! Thanks for catching that.

**Comment by KacperKubara** [comment]
The PR is waiting, please have a look here: https://github.com/facebookresearch/flashlight/pull/487

**Comment by tlikhomanenko** [comment]
PR is merged, closing.
