### ISSUE TITLE
./build/bin/asr/fl_asr_tutorial_inference_ctc: not found[Your bug title]

### ISSUE THREAD

**Issue by Shridharpawar77** [facebookresearch/flashlight#465]
After successfull installation of flashlight I can't find fl_asr_tutorial_inference_ctc

**Comment by tlikhomanenko** [comment]
Can you post what do you have inside build/bin/asr?

**Comment by tlikhomanenko** [comment]
@Shridharpawar77 any update?

**Comment by tlikhomanenko** [comment]
Seems you have the binary, looking at another issue from you https://github.com/facebookresearch/flashlight/issues/467. So closing this one. Feel free to reopen if it is needed.
