### ISSUE TITLE
NO_CUDNN_DESTROY_HANDLE issue

### ISSUE THREAD

**Issue by zxpan** [facebookresearch/flashlight#466]
### Questionin 
in flashlight/fl/autograd/backend/cuda/CudnnUtils.cpp, does the following issue get resolved:

// See https://git.io/fNQnM - sometimes, at exit, the CUDA context
// (or something) is already destroyed by the time a handle gets destroyed
// because of an issue with the destruction order.
#ifdef NO_CUDNN_DESTROY_HANDLE
#else
      CUDNN_CHECK_ERR(cudnnDestroy(handle));
#endif

I can see thee are memory leaks if NO_CUDNN_DESTROY_HANDLE is defined:

==3301== 753,320 (2,160 direct, 751,160 indirect) bytes in 6 blocks are definitely lost in loss record 2,426 of 2,467
==3301==    at 0x4C3017F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3301==    by 0x22437FD7: cudnnCreate (in /vcpkg/installed/x64-linux/lib/libcudnn.so.7.6.0)
==3301==    by 0x38C76E: (anonymous namespace)::Handle::Handle() (CudnnUtils.cpp:24)
==3301==    by 0x38EDFF: std::pair<int const, (anonymous namespace)::Handle>::pair<int const&, 0ul>(std::tuple<int const&>&, std::tuple<>&, std::_Index_tuple<0ul>, std::_Index_tuple<>) (tuple:1652)
==3301==    by 0x38ED09: std::pair<int const, (anonymous namespace)::Handle>::pair<int const&>(std::piecewise_construct_t, std::tuple<int const&>, std::tuple<>) (tuple:1641)
==3301==    by 0x38E927: void __gnu_cxx::new_allocator<std::pair<int const, (anonymous namespace)::Handle> >::construct<std::pair<int const, (anonymous namespace)::Handle>, std::piecewise_construct_t const&, std::tuple<int const&>, std::tuple<> >(std::pair<int const, (anonymous namespace)::Handle>*, std::piecewise_construct_t const&, std::tuple<int const&>&&, std::tuple<>&&) (new_allocator.h:136)
==3301==    by 0x38E4C9: void std::allocator_traits<std::allocator<std::pair<int const, (anonymous namespace)::Handle> > >::construct<std::pair<int const, (anonymous namespace)::Handle>, std::piecewise_construct_t const&, std::tuple<int const&>, std::tuple<> >(std::allocator<std::pair<int const, (anonymous namespace)::Handle> >&, std::pair<int const, (anonymous namespace)::Handle>*, std::piecewise_construct_t const&, std::tuple<int const&>&&, std::tuple<>&&) (alloc_traits.h:475)
==3301==    by 0x38DE89: std::__detail::_Hash_node<std::pair<int const, (anonymous namespace)::Handle>, false>* std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<int const, (anonymous namespace)::Handle>, false> > >::_M_allocate_node<std::piecewise_construct_t const&, std::tuple<int const&>, std::tuple<> >(std::piecewise_construct_t const&, std::tuple<int const&>&&, std::tuple<>&&) (hashtable_policy.h:2066)
==3301==    by 0x38DBC1: std::__detail::_Map_base<int, std::pair<int const, (anonymous namespace)::Handle>, std::allocator<std::pair<int const, (anonymous namespace)::Handle> >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::operator[](int const&) (hashtable_policy.h:725)
==3301==    by 0x38DA64: std::unordered_map<int, (anonymous namespace)::Handle, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, (anonymous namespace)::Handle> > >::operator[](int const&) (unordered_map.h:973)
==3301==    by 0x38D8B2: fl::getCudnnHandle() (CudnnUtils.cpp:345)
==3301==    by 0x409435: fl::batchnorm(fl::Variable const&, fl::Variable const&, fl::Variable const&, fl::Variable&, fl::Variable&, std::vector<int, std::allocator<int> > const&, bool, double, double) (BatchNorm.cpp:113)

**Comment by tlikhomanenko** [comment]
cc @vineelpratap @avidov @xuqiantong @jacobkahn

**Comment by jacobkahn** [comment]
@zxpan unfortunately, freeing the handle on some platforms causes a segfault when globals are destroyed - this leak is inconsequential and happens once at shutdown, so we're not going to make a change. Users also have the flexibility to change the behavior (which is why it's gated behind a macro), so we'll leave it as is. Thanks for reaching out.
