### ISSUE TITLE
ImportError: libfl-libraries.so: undefined symbol: _ZN2lm5ngram6ConfigC1Ev

### ISSUE THREAD

**Issue by apoca909** [facebookresearch/flashlight#468]
>>> from flashlight.lib.text.decoder import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/flashlight/bindings/python/flashlight/lib/text/decoder.py", line 9, in <module>
    from .flashlight_lib_text_decoder import (
ImportError: libfl-libraries.so: undefined symbol: _ZN2lm5ngram6ConfigC1Ev
>>> from flashlight.lib.text.decoder import CriterionType
Segmentation fault (core dumped)

Any ideas?

**Comment by tlikhomanenko** [comment]
what is the output of your `python setup.py install`? Can you remove build/dist folders and run installation again?

**Comment by apoca909** [comment]
> what is the output of your `python setup.py install`? Can you remove build/dist folders and run installation again?
--------------------
yes, i do remove build/dist folders and run installation
install log as follows:

running install
running bdist_egg
running egg_info
writing flashlight.egg-info/PKG-INFO
writing dependency_links to flashlight.egg-info/dependency_links.txt
writing top-level names to flashlight.egg-info/top_level.txt
reading manifest file 'flashlight.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'flashlight.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/flashlight
creating build/lib.linux-x86_64-3.6/flashlight/lib
copying flashlight/lib/__init__.py -> build/lib.linux-x86_64-3.6/flashlight/lib
creating build/lib.linux-x86_64-3.6/flashlight/lib/audio
copying flashlight/lib/audio/feature.py -> build/lib.linux-x86_64-3.6/flashlight/lib/audio
creating build/lib.linux-x86_64-3.6/flashlight/lib/sequence
copying flashlight/lib/sequence/criterion.py -> build/lib.linux-x86_64-3.6/flashlight/lib/sequence
copying flashlight/lib/sequence/criterion_torch.py -> build/lib.linux-x86_64-3.6/flashlight/lib/sequence
creating build/lib.linux-x86_64-3.6/flashlight/lib/text
copying flashlight/lib/text/decoder.py -> build/lib.linux-x86_64-3.6/flashlight/lib/text
copying flashlight/lib/text/dictionary.py -> build/lib.linux-x86_64-3.6/flashlight/lib/text
running build_ext
-- The CXX compiler identification is GNU 6.5.0
-- The C compiler identification is GNU 6.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- -rdynamic supported.
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_75,code=compute_75
-- Will build flashlight libraries.
-- MKL_THREADING = OMP
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - found
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
-- Could NOT find FFTW3 (missing: FFTW3_DIR)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- FindFFTW using pkgconfig: FOUND=1 LIBRARIES=fftw3 LIBRARY_DIRS= LIBDIR=/usr/lib/x86_64-linux-gnu LINK_LIBRARIES=
-- FindFTTW using pkgconfig: INCLUDE_DIRS= INCLUDEDIR=/usr/include
-- Found FFTW3: /root/vcpkg/installed/x64-linux/include  
-- FFTW found
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Looking for KenLM
-- Looking for lzma_auto_decoder in /root/vcpkg/installed/x64-linux/lib/liblzma.a
-- Looking for lzma_auto_decoder in /root/vcpkg/installed/x64-linux/lib/liblzma.a - found
-- Looking for lzma_easy_encoder in /root/vcpkg/installed/x64-linux/lib/liblzma.a
-- Looking for lzma_easy_encoder in /root/vcpkg/installed/x64-linux/lib/liblzma.a - found
-- Looking for lzma_lzma_preset in /root/vcpkg/installed/x64-linux/lib/liblzma.a
-- Looking for lzma_lzma_preset in /root/vcpkg/installed/x64-linux/lib/liblzma.a - found
-- Found LibLZMA: /root/vcpkg/installed/x64-linux/include (found version "5.2.5") 
-- Found BZip2: /root/vcpkg/installed/x64-linux/lib/libbz2.a (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found ZLIB: /root/vcpkg/installed/x64-linux/lib/libz.a (found version "1.2.11") 
-- Using kenlm library found in /root/vcpkg/installed/x64-linux/lib/libkenlm.a
-- Using kenlm utils library found in /root/vcpkg/installed/x64-linux/lib/libkenlm_util.a
-- kenlm model.hh found in /root/vcpkg/installed/x64-linux/include/kenlm/lm
-- Found kenlm: /root/vcpkg/installed/x64-linux/include  
-- Found kenlm (include: /root/vcpkg/installed/x64-linux/include, library: /root/vcpkg/installed/x64-linux/lib/libkenlm.a;/root/vcpkg/installed/x64-linux/lib/libkenlm_util.a;/root/vcpkg/installed/x64-linux/lib/liblzma.a;/root/vcpkg/installed/x64-linux/lib/libbz2.a;/root/vcpkg/installed/x64-linux/lib/libz.a)
-- Found cub: /root/vcpkg/installed/x64-linux/include/cub  
-- Found cub: (include: /root/vcpkg/installed/x64-linux/include/cub)
-- Found PythonInterp: /usr/local/bin/python (found version "3.6.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /root/flashlight/bindings/python/build/temp.linux-x86_64-3.6
Scanning dependencies of target pybind11
[  1%] Creating directories for 'pybind11'
[  3%] Performing download step (git clone) for 'pybind11'
Scanning dependencies of target fl-libraries
[  5%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/CriterionUtils.cpp.o
[  7%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ConnectionistTemporalClassificationCriterion.cpp.o
[  9%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ForceAlignmentCriterion.cpp.o
[ 11%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ViterbiPath.cpp.o
[ 13%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/FullConnectionCriterion.cpp.o
[ 15%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Ceplifter.cpp.o
[ 16%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dct.cpp.o
[ 18%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Derivatives.cpp.o
[ 20%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dither.cpp.o
[ 22%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfcc.cpp.o
[ 24%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfsc.cpp.o
[ 26%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PowerSpectrum.cpp.o
[ 28%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PreEmphasis.cpp.o
[ 30%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/SpeechUtils.cpp.o
[ 32%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/TriFilterbank.cpp.o
[ 33%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Windowing.cpp.o
[ 35%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/String.cpp.o
[ 37%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/System.cpp.o
[ 39%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ConvLM.cpp.o
[ 41%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ZeroLM.cpp.o
[ 43%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/KenLM.cpp.o
[ 45%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconDecoder.cpp.o
[ 47%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconFreeDecoder.cpp.o
[ 49%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconSeq2SeqDecoder.cpp.o
[ 50%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconFreeSeq2SeqDecoder.cpp.o
[ 52%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/Trie.cpp.o
[ 54%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/Utils.cpp.o
[ 56%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/dictionary/Dictionary.cpp.o
[ 58%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/dictionary/Utils.cpp.o
[ 60%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/tokenizer/PartialFileReader.cpp.o
[ 62%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/tokenizer/Tokenizer.cpp.o
[ 64%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o
[ 66%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/ForceAlignmentCriterion.cu.o
[ 67%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/FullConnectionCriterion.cu.o
[ 69%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/ViterbiPath.cu.o
[ 71%] Linking CUDA device code CMakeFiles/fl-libraries.dir/cmake_device_link.o
[ 73%] Linking CXX shared library ../lib.linux-x86_64-3.6/libfl-libraries.so
[ 73%] Built target fl-libraries
Submodule path 'tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
[ 75%] Performing update step for 'pybind11'
[ 77%] No patch step for 'pybind11'
[ 79%] No configure step for 'pybind11'
[ 81%] No build step for 'pybind11'
[ 83%] No install step for 'pybind11'
[ 84%] Completed 'pybind11'
[ 84%] Built target pybind11
Scanning dependencies of target flashlight_lib_audio_feature
Scanning dependencies of target flashlight_lib_text_dictionary
Scanning dependencies of target flashlight_lib_text_decoder
[ 86%] Building CXX object CMakeFiles/flashlight_lib_text_dictionary.dir/bindings/python/flashlight/lib/text/_dictionary.cpp.o
[ 88%] Building CXX object CMakeFiles/flashlight_lib_audio_feature.dir/bindings/python/flashlight/lib/audio/_feature.cpp.o
[ 90%] Building CXX object CMakeFiles/flashlight_lib_text_decoder.dir/bindings/python/flashlight/lib/text/_decoder.cpp.o
Scanning dependencies of target flashlight_lib_sequence_criterion
[ 92%] Building CXX object CMakeFiles/flashlight_lib_sequence_criterion.dir/bindings/python/flashlight/lib/sequence/_criterion.cpp.o
[ 94%] Linking CXX shared module ../lib.linux-x86_64-3.6/flashlight/lib/text/flashlight_lib_text_dictionary.cpython-36m-x86_64-linux-gnu.so
[ 96%] Linking CXX shared module ../lib.linux-x86_64-3.6/flashlight/lib/sequence/flashlight_lib_sequence_criterion.cpython-36m-x86_64-linux-gnu.so
[ 98%] Linking CXX shared module ../lib.linux-x86_64-3.6/flashlight/lib/text/flashlight_lib_text_decoder.cpython-36m-x86_64-linux-gnu.so
[100%] Linking CXX shared module ../lib.linux-x86_64-3.6/flashlight/lib/audio/flashlight_lib_audio_feature.cpython-36m-x86_64-linux-gnu.so
[100%] Built target flashlight_lib_text_dictionary
[100%] Built target flashlight_lib_sequence_criterion
[100%] Built target flashlight_lib_audio_feature
[100%] Built target flashlight_lib_text_decoder
-- -rdynamic supported.
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_75,code=compute_75
-- Will build flashlight libraries.
-- MKL_THREADING = OMP
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
-- Could NOT find FFTW3 (missing: FFTW3_DIR)
-- FindFFTW using pkgconfig: FOUND=1 LIBRARIES=fftw3 LIBRARY_DIRS= LIBDIR=/usr/lib/x86_64-linux-gnu LINK_LIBRARIES=
-- FindFTTW using pkgconfig: INCLUDE_DIRS= INCLUDEDIR=/usr/include
-- FFTW found
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Looking for KenLM
-- Using kenlm library found in /root/vcpkg/installed/x64-linux/lib/libkenlm.a
-- Using kenlm utils library found in /root/vcpkg/installed/x64-linux/lib/libkenlm_util.a
-- kenlm model.hh found in /root/vcpkg/installed/x64-linux/include/kenlm/lm
-- Found kenlm (include: /root/vcpkg/installed/x64-linux/include, library: /root/vcpkg/installed/x64-linux/lib/libkenlm.a;/root/vcpkg/installed/x64-linux/lib/libkenlm_util.a;/root/vcpkg/installed/x64-linux/lib/liblzma.a;/root/vcpkg/installed/x64-linux/lib/libbz2.a;/root/vcpkg/installed/x64-linux/lib/libz.a)
-- Found cub: (include: /root/vcpkg/installed/x64-linux/include/cub)
-- Configuring done
-- Generating done
-- Build files have been written to: /root/flashlight/bindings/python/build/temp.linux-x86_64-3.6
[  1%] Performing update step for 'pybind11'
[ 71%] Built target fl-libraries
[ 73%] No configure step for 'pybind11'
[ 75%] No build step for 'pybind11'
[ 77%] No install step for 'pybind11'
[ 79%] Completed 'pybind11'
[ 84%] Built target pybind11
[ 88%] Built target flashlight_lib_sequence_criterion
[ 92%] Built target flashlight_lib_audio_feature
[ 96%] Built target flashlight_lib_text_decoder
[100%] Built target flashlight_lib_text_dictionary
-- -rdynamic supported.
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_75,code=compute_75
-- Will build flashlight libraries.
-- MKL_THREADING = OMP
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
-- Could NOT find FFTW3 (missing: FFTW3_DIR)
-- FindFFTW using pkgconfig: FOUND=1 LIBRARIES=fftw3 LIBRARY_DIRS= LIBDIR=/usr/lib/x86_64-linux-gnu LINK_LIBRARIES=
-- FindFTTW using pkgconfig: INCLUDE_DIRS= INCLUDEDIR=/usr/include
-- FFTW found
-- Looking for KenLM
-- Using kenlm library found in /root/vcpkg/installed/x64-linux/lib/libkenlm.a
-- Using kenlm utils library found in /root/vcpkg/installed/x64-linux/lib/libkenlm_util.a
-- kenlm model.hh found in /root/vcpkg/installed/x64-linux/include/kenlm/lm
-- Found kenlm (include: /root/vcpkg/installed/x64-linux/include, library: /root/vcpkg/installed/x64-linux/lib/libkenlm.a;/root/vcpkg/installed/x64-linux/lib/libkenlm_util.a;/root/vcpkg/installed/x64-linux/lib/liblzma.a;/root/vcpkg/installed/x64-linux/lib/libbz2.a;/root/vcpkg/installed/x64-linux/lib/libz.a)
-- Found cub: (include: /root/vcpkg/installed/x64-linux/include/cub)
-- Configuring done
-- Generating done
-- Build files have been written to: /root/flashlight/bindings/python/build/temp.linux-x86_64-3.6
[  1%] Performing update step for 'pybind11'
[ 71%] Built target fl-libraries
[ 73%] No configure step for 'pybind11'
[ 75%] No build step for 'pybind11'
[ 77%] No install step for 'pybind11'
[ 79%] Completed 'pybind11'
[ 84%] Built target pybind11
[ 88%] Built target flashlight_lib_text_dictionary
[ 92%] Built target flashlight_lib_text_decoder
[ 96%] Built target flashlight_lib_audio_feature
[100%] Built target flashlight_lib_sequence_criterion
-- -rdynamic supported.
-- CUDA found (library: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so include: /usr/local/cuda/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_75,code=compute_75
-- Will build flashlight libraries.
-- MKL_THREADING = OMP
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/libdl.so)
-- Could NOT find FFTW3 (missing: FFTW3_DIR)
-- FindFFTW using pkgconfig: FOUND=1 LIBRARIES=fftw3 LIBRARY_DIRS= LIBDIR=/usr/lib/x86_64-linux-gnu LINK_LIBRARIES=
-- FindFTTW using pkgconfig: INCLUDE_DIRS= INCLUDEDIR=/usr/include
-- FFTW found
-- Looking for KenLM
-- Using kenlm library found in /root/vcpkg/installed/x64-linux/lib/libkenlm.a
-- Using kenlm utils library found in /root/vcpkg/installed/x64-linux/lib/libkenlm_util.a
-- kenlm model.hh found in /root/vcpkg/installed/x64-linux/include/kenlm/lm
-- Found kenlm (include: /root/vcpkg/installed/x64-linux/include, library: /root/vcpkg/installed/x64-linux/lib/libkenlm.a;/root/vcpkg/installed/x64-linux/lib/libkenlm_util.a;/root/vcpkg/installed/x64-linux/lib/liblzma.a;/root/vcpkg/installed/x64-linux/lib/libbz2.a;/root/vcpkg/installed/x64-linux/lib/libz.a)
-- Found cub: (include: /root/vcpkg/installed/x64-linux/include/cub)
-- Configuring done
-- Generating done
-- Build files have been written to: /root/flashlight/bindings/python/build/temp.linux-x86_64-3.6
[  1%] Performing update step for 'pybind11'
[ 71%] Built target fl-libraries
[ 73%] No configure step for 'pybind11'
[ 75%] No build step for 'pybind11'
[ 77%] No install step for 'pybind11'
[ 79%] Completed 'pybind11'
[ 84%] Built target pybind11
[ 88%] Built target flashlight_lib_sequence_criterion
[ 96%] Built target flashlight_lib_text_dictionary
[ 96%] Built target flashlight_lib_text_decoder
[100%] Built target flashlight_lib_audio_feature
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/flashlight
creating build/bdist.linux-x86_64/egg/flashlight/lib
copying build/lib.linux-x86_64-3.6/flashlight/lib/__init__.py -> build/bdist.linux-x86_64/egg/flashlight/lib
creating build/bdist.linux-x86_64/egg/flashlight/lib/audio
copying build/lib.linux-x86_64-3.6/flashlight/lib/audio/feature.py -> build/bdist.linux-x86_64/egg/flashlight/lib/audio
copying build/lib.linux-x86_64-3.6/flashlight/lib/audio/flashlight_lib_audio_feature.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/flashlight/lib/audio
creating build/bdist.linux-x86_64/egg/flashlight/lib/sequence
copying build/lib.linux-x86_64-3.6/flashlight/lib/sequence/criterion.py -> build/bdist.linux-x86_64/egg/flashlight/lib/sequence
copying build/lib.linux-x86_64-3.6/flashlight/lib/sequence/criterion_torch.py -> build/bdist.linux-x86_64/egg/flashlight/lib/sequence
copying build/lib.linux-x86_64-3.6/flashlight/lib/sequence/flashlight_lib_sequence_criterion.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/flashlight/lib/sequence
creating build/bdist.linux-x86_64/egg/flashlight/lib/text
copying build/lib.linux-x86_64-3.6/flashlight/lib/text/decoder.py -> build/bdist.linux-x86_64/egg/flashlight/lib/text
copying build/lib.linux-x86_64-3.6/flashlight/lib/text/dictionary.py -> build/bdist.linux-x86_64/egg/flashlight/lib/text
copying build/lib.linux-x86_64-3.6/flashlight/lib/text/flashlight_lib_text_dictionary.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/flashlight/lib/text
copying build/lib.linux-x86_64-3.6/flashlight/lib/text/flashlight_lib_text_decoder.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/flashlight/lib/text
copying build/lib.linux-x86_64-3.6/libfl-libraries.so -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/audio/feature.py to feature.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/sequence/criterion.py to criterion.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/sequence/criterion_torch.py to criterion_torch.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/text/decoder.py to decoder.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/flashlight/lib/text/dictionary.py to dictionary.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying flashlight.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying flashlight.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying flashlight.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying flashlight.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying flashlight.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/flashlight-1.0.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing flashlight-1.0.0-py3.6-linux-x86_64.egg
removing '/usr/local/lib/python3.6/dist-packages/flashlight-1.0.0-py3.6-linux-x86_64.egg' (and everything under it)
creating /usr/local/lib/python3.6/dist-packages/flashlight-1.0.0-py3.6-linux-x86_64.egg
Extracting flashlight-1.0.0-py3.6-linux-x86_64.egg to /usr/local/lib/python3.6/dist-packages
flashlight 1.0.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.6/dist-packages/flashlight-1.0.0-py3.6-linux-x86_64.egg
Processing dependencies for flashlight==1.0.0
Finished processing dependencies for flashlight==1.0.0

show symbols(parts):

> nm -D libfl-libraries.so

![image](https://user-images.githubusercontent.com/4969897/108581167-9005ed80-7369-11eb-99dd-b721bbed6229.png)

**Comment by apoca909** [comment]
remove build/dist folders and libfl-libraries.so*, then run installation the issue solved

**Comment by HuangZiliAndy** [comment]
Hi, can you tell me more about how you solve this issue? I am facing the same problem. And I try to remove build/dist folders and reinstall but still the same. Thanks!

**Comment by HuangZiliAndy** [comment]
Okay, I think I figure out what is my problem. When I first install this, it report some dependency issues for KENLM. So I follow some suggestions to add 
            `"-DCMAKE_INCLUDE_PATH="+"/export/c12/hzili1/tools/kenlm",
            "-DKENLM_LIB="+"/export/c12/hzili1/tools/kenlm",
            "-DKENLM_UTIL_LIB="+"/export/c12/hzili1/tools/kenlm/util",
            "-DKENLM_INC="+"/export/c12/hzili1/tools/kenlm/lm"`
to setup.py. In the end, it seems that these are not needed. You just need to export KENLM_ROOT=your path.
