### ISSUE TITLE
Make test fails on CPU backend

### ISSUE THREAD

**Issue by SYnchronYSe** [facebookresearch/flashlight#47]
Hi
I was encountering a number of errrors in 'make test' after compilation on CPU backend.
As suggested in other threads, I ran the individual tests one by one, and noted the errors thrown by each. I also ran arrayfire tests, where only one failed out of 123. I've mentioned that output in the end too. 

FLASHLIGHT
```
50% tests passed, 5 tests failed out of 10

Total Test time (real) =  38.68 sec

The following tests FAILED:
	  1 - AutogradTest (Failed)
	  3 - ModuleTest (Failed)
	  4 - SerializationTest (Failed)
	  8 - AllReduceTest (OTHER_FAULT)
	  9 - ContribModuleTest (Failed)
Errors while running CTest
```
When I ran the tests one by one, the following outputs were recorded: 
AutogradTest
```
[  PASSED  ] 51 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] AutogradTest.WeightNormConv
[  FAILED  ] AutogradTest.Rnn
[  FAILED  ] AutogradTest.Lstm
[  FAILED  ] AutogradTest.Gru
```

ModuleTest
```
[  PASSED  ] 13 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ModuleTest.RNNFwd
```

SerializationTest
```
[  PASSED  ] 13 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SerializationTest.LeNet
```

AllReduceTest
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Asynchronous allReduce not yet supported for Gloo backend
```

ContribModuleTest
```
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ModuleTest.ResidualFwd
```

The types of messages thrown with the errors were:
 1. AutogradTest, ModuleTest and SerializationTest :
```
unknown file: Failure
C++ exception with description "rnn not yet implemented on CPU" thrown in the test body.
```
2. AllReduceTest: 
```
unknown file: Failure
C++ exception with description "Asynchronous allReduce not yet supported for Gloo backend" thrown in the test body.
```
3. ContribModuleTest:
```
unknown file: Failure
C++ exception with description "BatchNorm CPU backend doesn't support momentum." thrown in the test body.
```

ARRAYFIRE
```
The following tests FAILED:
	  1 - spdlog-utests (Not Run)
	 79 - test_pinverse_cpu (Failed)

```
The first one was not present in the directory. I ran the second one separately to get the following output:	
```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] Pinverse/3.Large, where TypeParam = af::af_cdouble
```

Clearly, most of the errrors are occurring because a number of models are not supported on CPU backend. Does it imply that I can continue with my wav2letter installation and expect correct results?

[I'm installing flashlight as a dependency to wav2letter]

**Comment by jacobkahn** [comment]
@SYnchronYSe — you're correct; those tests that failed with those exceptions failed because those particular features aren't supported. Assuming your w2l model doesn't use those features (which you'd know if you got an exception when you started training), everything should be consistent.
