### ISSUE TITLE
using pytorch models in flashlight

### ISSUE THREAD

**Issue by OfekShochat** [facebookresearch/flashlight#474]
hello, I make a chess engine in c++ and want to use flashlight for the nn. libtorch's overhead is killing me with 2700 predictions a second on a 4 layer net. 
can I use pytorch models or onnx models (easily convertible from pytorch) to flashlight? is it just loading it? or is https://github.com/facebookresearch/flashlight/issues/62 the answer with loading with pytorch, getting state dict (which I don't know if I can in c++ but probably yes)(this isn't preferable for obvious reasons)?
also, I would like it to be cross platform, is this confirmed only working on Linux? (so platform info doesn't matter, not a bug)
thanks aot.

**Comment by tlikhomanenko** [comment]
You need to do proper loading each parameter into fl model, using the https://github.com/facebookresearch/flashlight/blob/master/flashlight/fl/nn/modules/Module.h#L105 function. You can have a look at this script I did for reading the ConvLM model from pytorch fairseq into flashlight https://github.com/facebookresearch/wav2letter/tree/master/recipes/utilities/convlm_serializer. So if you have the layers listed there you can reuse this script to convert model or hack it a bit to load your model.

One important thing to remember is that arrayfire/flashlight has column major arrays (fortran) while pytorch/tensorflow - row major arrays.
