### ISSUE TITLE
Colab record_audio - error (eg in InferenceAndAlignCTC.ipynb)

### ISSUE THREAD

**Issue by nmstoker** [facebookresearch/flashlight#477]
### Bug Description
I have been trying two of the Colabs that use the record_audio button, as handled here: 
https://github.com/facebookresearch/flashlight/blob/c1bdf0b0735d191e5734c4389f360d316908b665/scripts/colab/record.py#L122
It occurs in this Colab: InferenceAndAlignCTC.ipynb
When I run the cell with the "Press to start recording" buttons and then press the green button, the cell causes a Python error (see below)

#### Reproduction Steps
- Open InferenceAndAlignCTC.ipynb
- Run through the initial parts of the Colab as normal
- Once you get to the "Let's record" section (under Inference Step 1) you'll see there's the button for recording your own audio
- Run the cell
- Click on the button when green in an attempt to trigger recording of audio
- When you've spoken, click the (now) blue button to stop record
- Error appears with the trace below:

``` python

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-10-3739163234d1> in <module>()
      1 from flashlight.scripts.colab.record import record_audio
----> 2 record_audio("recorded_audio")

/content/flashlight/scripts/colab/record.py in record_audio(filename)
    120     display(HTML(AUDIO_HTML))
    121     data = eval_js("data")
--> 122     binary = b64decode(data.split(",")[1])
    123 
    124     process = (

IndexError: list index out of range

```

### Platform and Hardware
- Regular Google Colab, using GPU
- It's saved to my Google Drive but no changes were made (it's exactly like the original it was copied from just earlier this evening)
- Accessing it via Google Chrome

#### Additional Context
- Nothing else obvious stands out as being a likely cause.
-  I did check there wasn't some microphone permission pop-up that I'd missed but I cannot see one and I temporarily set Colabs to be able to access the mic w/o asking.
- Is it possible something about Chrome changed since the fixes from December to this code?
- Or is there maybe something I've overlooking? (I don't _think_ I've missed anything, as I've been careful but it's always possible!) Let me know if there's anything else useful I should check to help diagnose this.

**Comment by tlikhomanenko** [comment]
I have tested in Chrome Version 88.0.4324.192 (Official Build) (x86_64), it is working for me. Could you provide your version and if you can try with the version I have?

**Comment by nmstoker** [comment]
Thanks for checking into this.  I guess you must be on a Mac.
I've got 88.0.4324.182 (Official Build) (64-bit)
(ie the latest version on Linux [as per here](https://www.whatismybrowser.com/guides/the-latest-version/chrome))

My suspicion is that rather than the version (given we're on very near point releases) maybe it is more likely to be some permission relating to the microphone or some other difference.

**Comment by nmstoker** [comment]
Ah, just saw your edit.  I'll have to try that tomorrow morning.  From memory aren't those the instructions that run just earlier in the notebook?

**Comment by tlikhomanenko** [comment]
Yep, they are from above cells. Just to avoid all deps installation, as you need only several things to make recording (to avoid 15 min waiting on full fl build).

**Comment by tlikhomanenko** [comment]
Yes, I am using Mac. So cannot test somewhere else. If you can figure out the fix for your machine - really appreciate PR for it!

**Comment by nmstoker** [comment]
Hi @tlikhomanenko - I've got some good news.... It now seems to be working, although it's a pity because I don't think I'll be able figure out what was causing my problem with it because there was no clear change in anything apart from it just working.

I did this sequence:

1. I opened Chrome and opened the Colab and got it connected.
2. Scrolled down to the cell with the code and pasted the git clone command into the cell where the sox and ffmpeg installs were, ran that (completed fine)
3. Went to try the record button and it gave me the same error but this time did show the red "saving... please wait button" which I hadn't seen before.
4. Then I confirmed that the OS was seeing my mic (I could see the sound level moving in the system tray sound panel)
5. I went into chrome://settings/content/siteDetails?site=https%3A%2F%2Fcolab.research.google.com%2F&search=site+se to confirm I did definitely still have Mic permission (it was indeed remembered from the prior session, it was set to "Allow")
6. I returned to the cell and ran it again, and for no obvious reason it then worked when I clicked the green button waited a moment, then said something, clicked the blue button to stop and then after a moment it did save the audio with that red button appearing with a message of "output_file: recorded_audio_1.wav already exists and will be overwritten on build"

The audio is then playable through the widget that shows up now.  The only minor oddity is that the red button with "saving please wait" message remains there permanently (it's not a big deal, just seems like a minor bug, given that it now succeeds in saving)

It's a pity as I really can't see what was different to what I tried last time!

Now that it's working, I then went back to switch the Colab setting for the mic in Chrome back to "Ask" (just to be sensible) and then when I went back to the colab I reloaded the page, tried the recording cell again and this time it popped up with the usual kind of mic permission that Chrome gives (Allow/Block) and when I accepted that, it again worked.  This hadn't show up last time either..

Anyway, many thanks for your help and sorry to have wasted your time somewhat.
