### ISSUE TITLE
The GPU must be Tesla when build container with docker image-gpu?

### ISSUE THREAD

**Issue by 5iding** [facebookresearch/flashlight#478]
### Question
[A clear, concise description of your setup and question]
When I create the container from the docker image (GPU version), always failed. I was wondering if the GPU must be Tesla or not?
#### Additional Context
[Add any additional information here]

**Comment by tlikhomanenko** [comment]
There is no restriction on GPU type. But you need to have cuda driver 11.1. If you have lower version - you can rebuild base image with necessary cuda.

**Comment by 5iding** [comment]
Thank you for your reply. That works.
