### ISSUE TITLE
Benefit over Pytorch C++ API

### ISSUE THREAD

**Issue by pfeatherstone** [facebookresearch/flashlight#48]
What is the benefit of using flashlight over the Pytorch C++ API? Both are made by facebook, both have roughly the same API and both are quite heavy (the ArrayFire .SO file is > 750MB). The name "flashlight" would indicate it is a lightweight Pytorch ... I love the idea of a complete C++ neural network library but don't know why one should use this over Pytorch. I think I read somewhere they were going to deprecate Caffe in favour of Pytorch which lead me to believe that Facebook were going to focus their efforts on Pytorch. 
I appreciate this isn't an issue but a question.

**Comment by jacobkahn** [comment]
https://github.com/facebookresearch/flashlight/issues/1

**Comment by narfanar** [comment]
I don't think the answer to #1 is technically up to date :T

Perhaps instead of asking for current differences, we'd want to know:

**How do the plans for Flashlight differ from what PyTorch C++ aims to provide?**

**Comment by pfeatherstone** [comment]
It would be nice if there was a cpu only, lightweight inference engine that didn’t have a billion dependencies. I think people will always use a python library for training. Inference on the other hand is difficult at the edge these days. Though tencent‘s ncnn library is getting there

**Comment by narfanar** [comment]
So PyTorch for research, Flashlight for deployment? Hmm..

Flashlight does support CUDA and it mentions plans for OpenCL, so it seems its intended coverage is a bit higher than PyTorch.

**Comment by jacobkahn** [comment]
OpenCL is indeed on our roadmap. We expect to roll this out at most a few months after the ArrayFire 3.7 release.

**Comment by mrdvince** [comment]
@jacobkahn Any update on the OpenCL support? the fact that this could reduce dependence on nvidia specific cards would make this pretty awesome.
Stumbled across this while looking for something I could use to train on an AMD card.

**Comment by jacobkahn** [comment]
@mrdvince — the update here is that we're adding back OpenCL support via ArrayFire and oneDNN over the next 6-8 weeks.
