### ISSUE TITLE
[compiler error] nvcc fatal   : Unknown option 'fopenmp'

### ISSUE THREAD

**Issue by Gavin90s** [facebookresearch/flashlight#488]
$python setup.py install
running install
running bdist_egg
running egg_info
writing flashlight.egg-info/PKG-INFO
writing dependency_links to flashlight.egg-info/dependency_links.txt
writing top-level names to flashlight.egg-info/top_level.txt
package init file 'flashlight/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
reading manifest file 'flashlight.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'flashlight.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/flashlight
creating build/lib.linux-x86_64-3.6/flashlight/lib
copying flashlight/lib/__init__.py -> build/lib.linux-x86_64-3.6/flashlight/lib
creating build/lib.linux-x86_64-3.6/flashlight/lib/audio
copying flashlight/lib/audio/feature.py -> build/lib.linux-x86_64-3.6/flashlight/lib/audio
creating build/lib.linux-x86_64-3.6/flashlight/lib/sequence
copying flashlight/lib/sequence/criterion_torch.py -> build/lib.linux-x86_64-3.6/flashlight/lib/sequence
copying flashlight/lib/sequence/criterion.py -> build/lib.linux-x86_64-3.6/flashlight/lib/sequence
creating build/lib.linux-x86_64-3.6/flashlight/lib/text
copying flashlight/lib/text/decoder.py -> build/lib.linux-x86_64-3.6/flashlight/lib/text
copying flashlight/lib/text/dictionary.py -> build/lib.linux-x86_64-3.6/flashlight/lib/text
running build_ext
-- The CXX compiler identification is GNU 5.2.0
-- The C compiler identification is GNU 5.2.0
-- Check for working CXX compiler: /usr/local/bin/c++
-- Check for working CXX compiler: /usr/local/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- -rdynamic supported.
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Check for working CUDA compiler: /disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/bin/nvcc
-- Check for working CUDA compiler: /disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CUDA found (library: /disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib64/libcudart_static.a;-lpthread;dl;/usr/lib64/librt.so include: /disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/include)
-- CUDA architecture flags: -gencodearch=compute_30,code=sm_30-gencodearch=compute_35,code=sm_35-gencodearch=compute_50,code=sm_50-gencodearch=compute_52,code=sm_52-gencodearch=compute_60,code=sm_60-gencodearch=compute_61,code=sm_61-gencodearch=compute_70,code=sm_70-gencodearch=compute_75,code=sm_75-gencodearch=compute_75,code=compute_75
-- Will build flashlight libraries.
-- MKL_THREADING = OMP
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_intel_lp64: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so
--   Library mkl_gnu_thread: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so
--   Library mkl_core: /opt/intel/mkl/lib/intel64/libmkl_core.so
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib64/libpthread.so
--   Library m: /usr/lib64/libm.so
--   Library dl: /usr/lib64/libdl.so
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - found
-- MKL library found
-- CBLAS found (include: /opt/intel/mkl/include, library: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib64/libpthread.so;/usr/lib64/libm.so;/usr/lib64/libdl.so)
-- FFTW found
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Looking for KenLM
-- Looking for lzma_auto_decoder in /usr/lib64/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib64/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib64/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib64/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib64/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib64/liblzma.so - found
-- Found LibLZMA: /usr/include (found version "5.2.2") 
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Using kenlm library found in /usr/local/lib/libkenlm.a
-- Using kenlm utils library found in /usr/local/lib/libkenlm_util.a
-- kenlm model.hh found in /usr/local/include/kenlm/lm
-- Found kenlm: /usr/local/include  
-- Found kenlm (include: /usr/local/include, library: /usr/local/lib/libkenlm.a;/usr/local/lib/libkenlm_util.a;/usr/lib64/liblzma.so;/usr/lib64/libbz2.so;/usr/lib64/libz.so)
-- Could NOT find cub (missing: cub_INCLUDE_DIRS) 
-- Could not find cub - will download from source
-- Found PythonInterp: /disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/bin/python (found version "3.6.12") 
-- Found PythonLibs: /disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/libpython3.6m.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /disk4/zhuozhu.zz/flashlight/bindings/python/build/temp.linux-x86_64-3.6
Scanning dependencies of target CUB
Scanning dependencies of target pybind11
[  1%] Creating directories for 'CUB'
[  3%] Creating directories for 'pybind11'
[  4%] Performing download step (git clone) for 'CUB'
[  6%] Performing download step (git clone) for 'pybind11'
Cloning into 'CUB'...
Cloning into 'pybind11'...
fatal: unable to access 'https://github.com/NVlabs/cub.git/': TCP connection reset by peer
Cloning into 'CUB'...
Note: checking out '9a19306fbf30642ca331d0ec88e7da54a96860f9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 9a19306... bump version to 2.2.4
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'tools/clang'
Cloning into '/disk4/zhuozhu.zz/flashlight/bindings/python/build/temp.linux-x86_64-3.6/pybind11/src/pybind11/tools/clang'...
Submodule path 'tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
[  8%] No patch step for 'pybind11'
[  9%] Performing update step for 'pybind11'
[ 11%] No configure step for 'pybind11'
[ 13%] No build step for 'pybind11'
[ 14%] No install step for 'pybind11'
[ 16%] Completed 'pybind11'
[ 16%] Built target pybind11
-- Had to git clone more than once:
          2 times.
Note: checking out 'c3cceac115c072fb63df1836ff46d8c60d9eb304'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c3cceac1... update readme to 1.8.0
[ 19%] Performing update step for 'CUB'
[ 19%] No patch step for 'CUB'
[ 21%] No configure step for 'CUB'
[ 22%] No build step for 'CUB'
[ 24%] No install step for 'CUB'
[ 26%] Completed 'CUB'
[ 26%] Built target CUB
Scanning dependencies of target fl-libraries
[ 31%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ForceAlignmentCriterion.cpp.o
[ 31%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/CriterionUtils.cpp.o
[ 32%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/FullConnectionCriterion.cpp.o
[ 31%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ConnectionistTemporalClassificationCriterion.cpp.o
[ 34%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cpu/ViterbiPath.cpp.o
[ 36%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Ceplifter.cpp.o
[ 37%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dct.cpp.o
[ 39%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Derivatives.cpp.o
[ 40%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Dither.cpp.o
[ 42%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfcc.cpp.o
[ 44%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Mfsc.cpp.o
[ 45%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PowerSpectrum.cpp.o
[ 47%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/PreEmphasis.cpp.o
[ 49%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/SpeechUtils.cpp.o
[ 50%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/TriFilterbank.cpp.o
[ 52%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/audio/feature/Windowing.cpp.o
[ 54%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/String.cpp.o
[ 55%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/common/System.cpp.o
[ 57%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ConvLM.cpp.o
[ 59%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/ZeroLM.cpp.o
[ 60%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/lm/KenLM.cpp.o
[ 62%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconDecoder.cpp.o
[ 63%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconFreeDecoder.cpp.o
[ 65%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconSeq2SeqDecoder.cpp.o
[ 67%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/LexiconFreeSeq2SeqDecoder.cpp.o
[ 68%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/Trie.cpp.o
[ 70%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/decoder/Utils.cpp.o
[ 72%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/dictionary/Dictionary.cpp.o
[ 73%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/dictionary/Utils.cpp.o
[ 75%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/tokenizer/PartialFileReader.cpp.o
[ 77%] Building CXX object CMakeFiles/fl-libraries.dir/flashlight/lib/text/tokenizer/Tokenizer.cpp.o
[ 78%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/CriterionUtils.cu.o
[ 80%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/ForceAlignmentCriterion.cu.o
[ 81%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/FullConnectionCriterion.cu.o
[ 83%] Building CUDA object CMakeFiles/fl-libraries.dir/flashlight/lib/sequence/criterion/cuda/ViterbiPath.cu.o
[ 85%] Linking CUDA device code CMakeFiles/fl-libraries.dir/cmake_device_link.o
nvcc fatal   : Unknown option 'fopenmp'
gmake[2]: *** [CMakeFiles/fl-libraries.dir/cmake_device_link.o] Error 1
gmake[1]: *** [CMakeFiles/fl-libraries.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 135, in <module>
    python_requires=">=3.6",
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 110, in build_extensions
    ["cmake", "--build", "."] + build_args, cwd=self.build_temp
  File "/disk4/zhuozhu.zz/tops/anaconda3/envs/torch1.15py3.6/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
(torch1.15py3.6)

**Comment by Gavin90s** [comment]
anybody can help me? nvcc fatal : Unknown option 'fopenmp'

**Comment by tlikhomanenko** [comment]
Can you give more details on your system, cuda version, etc. and repro steps for the observed error?

**Comment by tlikhomanenko** [comment]
Feel free to reopen if issue is still not solved, closing for now due to inactivity.

**Comment by lizezheng** [comment]
came across the same error.
