### ISSUE TITLE
ONNX import/export

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#5]
Hello, 
Congrats for this lib. 
Any plan to import and/or export ONNX files ?
https://onnx.ai/
Cheers
W.

**Comment by vineelpratap** [comment]
Hi, 
 Thanks ! At the moment, we don't have plans for ONNX integration. We may re-evaluate this in future.

**Comment by neelakanth** [comment]
> Hi,
> Thanks ! At the moment, we don't have plans for ONNX integration. We may re-evaluate this in future.

Any update on converting flashlight trained models to ONNX or Tensorflow?

**Comment by tlikhomanenko** [comment]
> > Hi,
> > Thanks ! At the moment, we don't have plans for ONNX integration. We may re-evaluate this in future.
> 
> Any update on converting flashlight trained models to ONNX or Tensorflow?

Not for now yet.
