### ISSUE TITLE
The module BinaryCrossEntropy and the function binaryCrossEntropy behave differently

### ISSUE THREAD

**Issue by krishnap25** [facebookresearch/flashlight#50]
Hello, 

The function `binaryCrossEntropy` performs no reduction whereas the module `BinaryCrossEntropy` performs a mean reduction. It would be good to have a flag with the default of mean reduction. I am on commit `6ec9dc7e9f57400801794b2e2f02317031883268`.

Please see the example below. 

Thanks,
Krishna

```
#include <iostream>
#include <arrayfire.h>
#include "flashlight/flashlight.h"


int main(){
    auto x = fl::Variable(af::randu(100), false);
    auto y = fl::Variable(af::randu(100), false);

    auto loss_1 = fl::binaryCrossEntropy(x, y).array();
    std::cout << loss_1.dims(0) << std::endl; 
    // => 100

    auto loss_fn = fl::BinaryCrossEntropy();
    auto loss_2 = loss_fn(x, y).array();
    std::cout << loss_2.dims(0) << std::endl;
    // => 1
}
```

**Comment by tlikhomanenko** [comment]
Hi @krishnap25,

Thanks for reporting the issue. We will think how to do this in a best way.

**Comment by vineelpratap** [comment]
Hi @krishnap25 , 
  That makes sense. It might be good to have a `ReduceMode`  param for functions  `binaryCrossEntropy` and `categoricalCrossEntropy`. Do you mind sending PR ?
