### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by krishnap25** [facebookresearch/flashlight#51]
Please see [here](https://fl.readthedocs.io/en/latest/modules.html#serialization), where the sections on Serialization, Utils and DistributedUtils are missing.

EDIT: It appears the docs have been moved [here](https://fl.readthedocs.io/en/latest/serial.html).

**Comment by tlikhomanenko** [comment]
Hi @krishnap25,

thanks for pointing this! We will fix docs shortly.
