### ISSUE TITLE
Upsampling layer, 1d layers

### ISSUE THREAD

**Issue by pfeatherstone** [facebookresearch/flashlight#54]
Missing upsampling layer and 1d convolutions

**Comment by tlikhomanenko** [comment]
Hi @pfeatherstone, 

For 1d conv you can use 2d conv layer with providing kernel size = 1 for the second spatial dimension. Any obstacles to do this?

**Comment by pfeatherstone** [comment]
Yep that will work for conv layers. It looks like the same applies to pooling layers. 
It would be great if there were some interpolation layers, particularly using bicubic and sinc filters

**Comment by pfeatherstone** [comment]
Is this repository still actively developed or has everyone decided to focus on the Pytorch C++ api ?

**Comment by jacobkahn** [comment]
#1

**Comment by pfeatherstone** [comment]
Arrayfire supports interpolation through the approx functions. If i write a custom module that uses the arrayfire function will autograd take care of back-propagating gradients in the backward call?

**Comment by jacobkahn** [comment]
@pfeatherstone — you'll have to write your own custom backwards function that operates on the `Variable` you create as a result of the operation, since we don't have custom operators defined through ArrayFire functions.

Pool2D (https://git.io/fjPSn) gives a simple example of how this might look with `gradFunc`. Let me know if you have any questions.

**Comment by pfeatherstone** [comment]
> @pfeatherstone — you'll have to write your own custom backwards function that operates on the `Variable` you create as a result of the operation, since we don't have custom operators defined through ArrayFire functions.
> 
> Pool2D (https://git.io/fjPSn) gives a simple example of how this might look with `gradFunc`. Let me know if you have any questions.

That only seems to be a CUDNN implemenation

**Comment by pfeatherstone** [comment]
Ok i just realised there is a CPU version in the backends/cpu folder

**Comment by pfeatherstone** [comment]
Seems fiddly. I'll wait. Or use Pytorch C++ api
