### ISSUE TITLE
How to turn off training mode?

### ISSUE THREAD

**Issue by minty99** [facebookresearch/flashlight#55]
My test code is here:
```
fl::Variable cell_input(af::randn(af::dim4(768, 1, 1)), false);
fl::RNN attention_rnn(768, 1024, 1, fl::RnnMode::LSTM);
attention_rnn.eval();
attention_rnn.zeroGrad();
fl::Variable hx(af::randn(af::dim4(1024, 1)), false), cx(af::randn(af::dim4(1024, 1)), false);
for(int i = 0; i < 100; i++)
{
    auto result = attention_rnn.forward(cell_input, hx, cx);
    fl::Variable output, hidden_state, cell_state;
    std::tie(output, hidden_state, cell_state) = result;
}
```

I want to turn off training mode, but It seems not working. I profiled this code by `Nsight Systems` and I saw that CuDNN::RNNForwardTraining is always called.

How to turn off training mode?

**Comment by awni** [comment]
Hi @minty99, you are in fact correctly turning off training mode. The current RNN implementation in flashlight still calls the `RNNForwardTraining` even in `eval` mode. This is something we should fix soon.

**Comment by minty99** [comment]
Thanks for your reply!
How to turn off training mode, exactly? only `eval()` call is sufficient?

**Comment by vineelpratap** [comment]
@minty99  - `eval()` call should be sufficient.
