### ISSUE TITLE
squeeze and unsqueeze?

### ISSUE THREAD

**Issue by ThisIsIsaac** [facebookresearch/flashlight#56]
Is there an equivalent of `torch.squeeze` and `torch.unsqueeze`?

If not, we'll give it a shot implementing. It would be great if you could guide us where to get started. Thanks

**Comment by vineelpratap** [comment]
@ThisIsIsaac - You should be able to achieve similar behavior using `fl::moddims()` - https://github.com/facebookresearch/flashlight/blob/master/flashlight/autograd/Functions.h#L441
