### ISSUE TITLE
Caching cuDNN kernel choices

### ISSUE THREAD

**Issue by ThisIsIsaac** [facebookresearch/flashlight#57]
Pytorch as a functionality to cache the chosen cuDNN kernels when the input dimensions are identical to previous calls:
```
torch.backend.cudnn.benchmark = True
```

This improves throughput of a network by 30~40% (again, when the input dimensions of the network do not change).

Here is where the caching is implemented in Aten:
https://github.com/pytorch/pytorch/blob/358fb51e773b8ad509ec270caee5ec1c51d82f38/aten/src/ATen/native/cudnn/Conv.cpp#L340

Do you have any plans to add similar functionality? It would greatly improve throughput of our DNN engines built with Flashlight.

Thanks

**Comment by vineelpratap** [comment]
@ThisIsIsaac  - Thanks for the suggestion. Yes, this is in our plans and we would like to support it.

**Comment by ThisIsIsaac** [comment]
@vineelpratap  Thanks for the reply. Do you know approximately when it will be coming? I'd love to contribute and help expedite the process.

**Comment by vineelpratap** [comment]
If you want this early, it might be better if you work on it and send us a PR. Here is the code pointer where we choose the cuDNN algorithm - https://github.com/facebookresearch/flashlight/blob/master/flashlight/autograd/backend/cuda/Conv2D.cpp#L79

**Comment by ThisIsIsaac** [comment]
Thanks. I'll take a look.

**Comment by ThisIsIsaac** [comment]
@vineelpratap  I'm going to use huge portions of code from Pytorch's Aten. According to their [license](https://github.com/pytorch/pytorch/blob/master/LICENSE) it seems like we can use it.

**Comment by ThisIsIsaac** [comment]
@vineelpratap Is there a reason why only 2D convs use cudnn, and not others?

**Comment by ThisIsIsaac** [comment]
@vineelpratap 
ping!

**Comment by vineelpratap** [comment]
Hi, 
1. Currently, we don’t have modules for ConvNd in the framework. 
2. No, we don’t have it set. I think it would be easy to implement after we have a flag for ‘cudnn.benchmark’

**Comment by ThisIsIsaac** [comment]
@vineelpratap 

1. How do I test for correctness?

2. how do I set `benchmark = true`? Currently, I am testing by giving it as a parameter in `conv2d` but this probably shouldn't be the way it is actually implemented, as you would have to pass `true` to every call of `conv2d`.

**Comment by vineelpratap** [comment]
Hi,
 Thanks for taking care of this ! Regarding your questions - 

> How do I test for correctness and throughput? Any internal code available? or should I just go with my simple profiling code?

Here are some code pointers. You might have to adapt them for your use case. 

For correctness - https://git.io/fjQvF, https://git.io/fjQvb
For throughput - https://git.io/fjQvA


> how do I set benchmark = true? Currently, I am testing by giving it as a parameter in conv2d but this probably shouldn't be the way it is actually implemented, as you would have to pass true to every call of conv2d.

We can have a function in `fl::cuda` namespace similar to https://git.io/fjQv1 called `void setCudnnBenchmark(bool val)`. You can also check the implementation details for `af::setMemStepSize(...)`, `af::setSeed(FLAGS_seed)`, `af::setFFTPlanCacheSize(...)` in https://github.com/arrayfire/arrayfire/ for inspiration.

**Comment by ThisIsIsaac** [comment]
1. How do I concurrently use 2 different versions of flashlight? I have a reference copy of flashlight at `/home/isaac/flashlight` and a development copy at `/home/isaac/flashlight_dev`. Let's say I want to compile the built-in examples first using the reference copy and then using the development copy. How would I do this without having to build from scratch every time?

2. From taking look at [tests/CMakeLists.txt](https://github.com/facebookresearch/flashlight/blob/master/tests/CMakeLists.txt), [Benchmark.cpp](https://github.com/facebookresearch/flashlight/blob/master/tests/nn/Benchmark.cpp#L83-L100) was not being built on `make test`. In fact, Benchmark.cpp seemed to be not part of any default builds. So I am going to add:

```
build_test(${FLASHLIGHT_TEST_DIR}/nn/Benchmark.cpp)
```

to `tests/CMakeLists.txt`. Let me know if there is a better way done internally.

**Comment by ThisIsIsaac** [comment]
@vineelpratap ping!

**Comment by vineelpratap** [comment]
Hi, 
Regarding your questions
1 - Not sure if it is possible. @jacobkahn do you have any ideas how to accomplish it ?
2 - We don't want to include in `tests` as this is not a unit test. It is just a benchmarking tool that we use for performance tuning.

**Comment by jacobkahn** [comment]
@ThisIsIsaac — some of the things in #72 accomplish this: https://github.com/facebookresearch/flashlight/pull/72/files#diff-f7a8e4a67d72800f1f92fac76935d2e6. We're still discussing how to make this implementation cleaner, but I think this will make a nice performance difference.

**Comment by jacobkahn** [comment]
@ThisIsIsaac — we've decided to remove the performance auditing framework in #72 for now, but this is something we want to add and make general. If it's still on your radar, we'd welcome a PR!

**Comment by jacobkahn** [comment]
The ability to do this was added in https://github.com/facebookresearch/flashlight/pull/187.
