### ISSUE TITLE
loading layer weights

### ISSUE THREAD

**Issue by ThisIsIsaac** [facebookresearch/flashlight#62]
Is there something equivalent to Pytorch's:

```python
torch.nn.Module.load_state_dict()
```

that automatically deserializes weights and loads them to correct layers?

I have read [DataLoading](https://fl.readthedocs.io/en/latest/data_loading.html) and [Serialization Library](https://fl.readthedocs.io/en/latest/serial.html) but they seem to lack the functionality of automatically loading the weights to the correct layer.

**Comment by vineelpratap** [comment]
We provide [.params()](https://github.com/facebookresearch/flashlight/blob/master/flashlight/nn/modules/Module.cpp#L66-L68) functions which returns the parameters of the entire Module. Also, if the module is a container, you can access a specific module using [.module(int id)](https://github.com/facebookresearch/flashlight/blob/master/flashlight/nn/modules/Container.cpp#L25-L31)

Would that work for your use case ?

**Comment by ThisIsIsaac** [comment]
We are trying to load Pytorch's weights to Flashlight. I know that this is not supported, so we are also trying to internally implement this. 

Setting weight of each layer in `Module` individually using :

```cpp
setParams(Variable& var, int position)
```

is to inefficient simply because a single `Module` can contain tens or hundreds of parameters, and mapping each parameter to a layer would be too burdensome.

In Pytorch, weights -- or parameters -- of a `nn.Module` is saved in a dictionary-like structure where each parameter holds a string that uniquely maps it to a layer. If I can map the name of each Pytorch parameter to a unique identifier of each layer in flashlight's `Module`, I can write a scrip that automatically reads and parses Pytorch's map and loads to each layer in flashlight's `Module`.

What do you think about this? Could you recommend where to get started from here?

**Comment by minty99** [comment]
@vineelpratap - I want to load weight, bias tensors to fl::RNN (LSTM mode).

In PyTorch, Variables of LSTM are these: weight_ih, weight_hh, bias_ih, bias_hh.
I read [RNN.cpp](https://github.com/facebookresearch/flashlight/blob/master/flashlight/nn/modules/RNN.cpp#L35) and found only `w` is inserted to params. How can I pass these variables to Flashlight?
Flashlight have .param() function, but there is no description for parameter index - variable mapping for layers.

Linear, Conv2D have constructors demanding weight (and bias, if needed), but RNN's only consturctor doesn't demand weight or bias.

**Comment by awni** [comment]
The fl::RNN takes the weights as a single unrolled parameter vector which gets translated into the four individual params by CuDNN. You should be able unroll and concatenate all four of the LSTM weight matrices into a single vector to get this to work (I am not sure on the order, you can see what PyTorch does). The order will be the same between pytorch and flashlight since we both use cudnn under the hood.
