### ISSUE TITLE
Support for fp16 & tensor core

### ISSUE THREAD

**Issue by minty99** [facebookresearch/flashlight#67]
Currently, flashlight doesn't support fp16 type; so it does not use tensor core. When do you plan to support this?

**Comment by jacobkahn** [comment]
@minty99 — fp32 will still work with Volta Tensor Cores, so we're using them. fp16 with `cuDNN` is on our roadmap, but we don't yet know the affects of using fp16 on convergence, so this is something we're yet to explore. If you're interested in trying it for yourself, it shouldn't be terribly difficult to implement.

**Comment by WilliamTambellini** [comment]
With AF master, the user can now turn on TensorCore cublas math mode:
https://github.com/arrayfire/arrayfire/pull/2584
Notes:
- dont know if flashlight compiles with AF master
- the accuracy of cublas is known to be lower when TC math mode is on

**Comment by minty99** [comment]
@jacobkahn @WilliamTambellini 
Now, AF master supports fp16 well. If FL won't support fp16 soon, I want to implement this myself.
Is there ongoing development for fp16?

**Comment by ThisIsIsaac** [comment]
@jacobkahn Would love to contribute enabling fp16 for FL with @minty99. Could you give a general director on where to get started, or how you were planning on implementing?

**Comment by vineelpratap** [comment]
Hi @ThisIsIsaac , @minty99, 
  Thanks for your interest. Since Arrayfire abstracts array types under the hood, most of the flashlight operations including autograd (https://git.io/Jeswi, https://git.io/Jesw6) should work right away. 

First thing, we need to start with is modifying the accelerator code for Conv, RNN, BatchNorm etc... inside - https://git.io/JeswP . We might have to make minor modifications to distributed API -  https://git.io/JeswX, https://git.io/Jesw1

Also, it looks like Arrayfire has not made an official release for fp16 yet - https://github.com/arrayfire/arrayfire/releases . 

@WilliamTambellini - do you know if it going to happen soon ?

**Comment by WilliamTambellini** [comment]
fp16 will be indeed part of Arrayfire 3.7.0 which is indeed not yet released: as agreed with Umar, the last change for 3.7.0 should be the MemManager plugin :
https://github.com/arrayfire/arrayfire/pull/2461
by @jacobkahn 
Now @ThisIsIsaac , this does not prevent you to try f16 in flashlight right now :
- build afcuda master with CudaCompute 7.x and cuda 10
- build flashlight using your local build of af
- try to use the new af f16 datatype now available

**Comment by jacobkahn** [comment]
@minty99 @ThisIsIsaac — there's been some outstanding recent work from @mtmd on Automatic Mixed Precision (AMP) support on the wav2letter side that we'll also be looking to add to this integration. Keep an eye out in the next few weeks for this.

In the mean time, those AMP changes are primarily on the CUDA/cuDNN side, and we still want to be fp16 end-to-end (including in ArrayFire), so thinking about how to integrate that into `fl::Variable` in such a way that the API is consistent is still something that needs thought; we'd welcome contributions here too!

**Comment by ThisIsIsaac** [comment]
@jacobkahn That's a lovely news!

> thinking about how to integrate that into the underlying af::arrays inside fl::Variable in such a way that the API is consistent is still something that needs thought

FP16 on array fire is supported. Does integrating AMP require further modifications of `af::array`, assuming that FP16 is supported on `af::array`?

**Comment by jacobkahn** [comment]
@ThisIsIsaac turns out the changes in #72 will probably cover almost everything related to `Variable`. `af::array` will natively support an `af::dtype::f16` now, yes.

**Comment by jacobkahn** [comment]
Added in #176, #192, etc. Fully-supported now. Closing.
