### ISSUE TITLE
Alternative to MKL-DNN (arm / iOS / Android support)

### ISSUE THREAD

**Issue by jamislike** [facebookresearch/flashlight#74]
Just wondering if there is any scope for an alternative to MKL-DNN that might allow flashlight to be built and used on a non Intel CPU with the CPU backend. Or could this be provided via the in progress open cl backend?

**Comment by WilliamTambellini** [comment]
The computation backend of flashlight is arrayfire meaning you should better ask that question on the AF github page.

**Comment by jacobkahn** [comment]
@jamislike — there's currently work in progress to integrate MiOpen primitives with the OpenCL backend, but these won't have native CPU support.

We've tried integrating the ArrayFire OpenCL backend with MKL-DNN but have had trouble with `cl::Buffer`-pointer interoperability. We may revisit this in the future, but it's unclear.
