### ISSUE TITLE
(Real) build failure

### ISSUE THREAD

**Issue by tarnh** [facebookresearch/flashlight#77]
I'm trying to create a CPU build of flashlight:
`cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU -DUSE_MPI=ON`

The build fails with TONS of errors aginst mkl-dnn, which I'm using as recommended:
https://pastebin.com/a4a0SUg1

**Comment by jacobkahn** [comment]
@tarnh MKL-DNN has unfortunately made a lot of breaking changes to their API in v1 :(

If you check out a v0 MKL-DNN version, that API will work. I've also made sure the docs reflect this: https://fl.readthedocs.io/en/latest/installation.html#cpu-backend-dependencies. Thanks for the catch.
