### ISSUE TITLE
use existing cereal

### ISSUE THREAD

**Issue by tbenst** [facebookresearch/flashlight#79]
I'd like to use an existing cereal installation rather than install from git, which requires internet access and is impure. Previously, this was possible: https://github.com/facebookresearch/flashlight/blob/a1349e84c9be19ecbbdc28d2d5a8eeeaaaa06273/CMakeLists.txt#L95.

This precludes packaging flashlight on OSes like NixOS that require no internet access during build for reproducibility purposes.

**Comment by jacobkahn** [comment]
@tbenst — this should be doable via the command line when running `cmake` by setting `-D cereal_INCLUDE_DIRS =[path to headers]` as per https://git.io/JvLH6. Let me know if that doesn't work and I can add way to make this work.

**Comment by avidov** [comment]
Otherwise setting [CEREAL_INCLUDE_DIR](https://github.com/facebookresearch/flashlight/blob/804c5a9cdb003e514ae537f6746e12097e8804cc/cmake/Findcereal.cmake#L8) 
or [CEREAL_ROOT](https://github.com/facebookresearch/flashlight/blob/804c5a9cdb003e514ae537f6746e12097e8804cc/cmake/Findcereal.cmake#L11) should work.

**Comment by tbenst** [comment]
@jacobkahn @avidov thanks, I tried these but still I see:
```
Scanning dependencies of target cereal
[  1%] Creating directories for 'cereal'
[  2%] Performing download step (git clone) for 'cereal'
Cloning into 'cereal'...
fatal: unable to access 'https://github.com/USCiLab/cereal.git/': Could not resolve host: github.com
```
[full output](https://gist.github.com/tbenst/288e89566a72a56ad36001ad5ebe8c8b)

Here's my cereal include dir:
```
❯ ls /nix/store/z0c9k988kzbls1kci90ljq928h1xqza7-cereal-1.3.0/include/cereal/
access.hpp  archives  cereal.hpp  details  external  macros.hpp  specialize.hpp  types  version.hpp
```

Does the git clone always happen due to https://github.com/facebookresearch/flashlight/blob/f1f7ba8dd729e44581f9466a597b46c9d4185e2a/CMakeLists.txt#L88 ?

**Comment by jacobkahn** [comment]
Ah yep @tbenst - that's a good point - the clone will always occur even if you provide a local include directory for cereal. One of us will add a simple gating mechanism for this today.

**Comment by tbenst** [comment]
@jacobkahn thanks so much for looking into this. Unfortunately, the problem remains. I've tried setting CEREAL_INCLUDE_DIR and CEREAL_ROOT_DIR in my environment, as well as passing `-Dcereal_INCLUDE_DIRS=${cereal}/include` or `-Dcereal_INCLUDE_DIRS=${cereal}/include/cereal` or `-DCEREAL_INCLUDE_DIR=${cereal}/include` or `-DCEREAL_INCLUDE_DIR=${cereal}/include` where `$cereal` evaluates to the correct cereal root path. Each time, I get:

```
-- Could NOT find cereal (missing: cereal_INCLUDE_DIRS) 
-- cereal NOT found. Will download from source
```
later followed by a git clone

**Comment by avidov** [comment]
Please refresh your repo (git pull) and ensure you have commit: https://github.com/facebookresearch/flashlight/commit/cd535bf887ca1763f30e9a7c2480c48a8abe25e5

**Comment by tbenst** [comment]
@avidov yes I’m using that commit

**Comment by jacobkahn** [comment]
@tbenst — sorry you're still having trouble. Can you try setting `export CEREAL_ROOT_DIR=[$DIR]` where `$DIR` is the directory that contains the `cereal.hpp` file before building? I can't seem to repro the build not finding the right file.

**Comment by tbenst** [comment]
@jacobkahn aha! setting `CEREAL_ROOT_DIR="${cereal}/include/cereal"` worked! I wasn't including the `/include/cereal` part of the path before
