### ISSUE TITLE
got an error when make LayerNorm.cpp

### ISSUE THREAD

**Issue by thcktw** [facebookresearch/flashlight#80]
error: implicit instantiation of undefined template 'std::__1::array<int, 4>'
  std::array<int, AF_MAX_DIMS> reorderDims;
                               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__tuple:223:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
1 error generated.
make[2]: *** [CMakeFiles/flashlight.dir/flashlight/nn/modules/LayerNorm.cpp.o] Error 1
make[1]: *** [CMakeFiles/flashlight.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Note: checking out '2fe3bd994b3189899d93f1d5a881e725e046fdc2'.

**Comment by jacobkahn** [comment]
@thcktw — I'm guessing you're building on MacOS; the Xcode llvm toolchain doesn't always implicitly include some needed headers (e.g. `<array>`). The fix above should resolve the issue.
