### ISSUE TITLE
ArrayFire user group meeting at next GTC

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#86]
Hello, 
I know this is not the best place to ask but is anyone from the Flashlight team going to the next GTC in March ?
Kind
WT

**Comment by jacobkahn** [comment]
@WilliamTambellini — some of us should be at GTC in March, yes! There may or may not be a talk about wav2letter/flashlight as well :) . An ArrayFire user group meeting sounds great as well.
