### ISSUE TITLE
Help support build as subdirectory in another project

### ISSUE THREAD

**Issue by kriswuollett** [facebookresearch/flashlight#87]
Currently flashlight is using CMake variables that are not compatible with including the project as a subdirectory in another. I believe that to accommodate this some variables just need to be updated. I see that currently CMake 3.5.1 is required which should be recent enough to update:

- `CMAKE_SOURCE_DIR` -> `CMAKE_CURRENT_LIST_DIR` or `PROJECT_SOURCE_DIR` where appropriate
- `${ArrayFire_INCLUDE_DIRS}` -> `$<BUILD_INTERFACE:${ArrayFire_INCLUDE_DIRS}>`

And also:

- don't also don't download googletest if that project/target already exists

The context is I am using CMake 3.15.3 and would like to use the [`FetchContent`](https://cmake.org/cmake/help/v3.15/module/FetchContent.html) module which was introduced in [CMake 3.11](https://cmake.org/cmake/help/v3.11/release/3.11.html) to include flashlight in my build. These changes are working for me so far to try some some examples/tutorials.

**Comment by kriswuollett** [comment]
It would be helpful for someone more experienced with CMake to comment on how to make the library build flexible enough to either be used in `ExternalProject`, `FetchContent`, simple git submodule, or already installed in system configurations.

I'm not as confident that the build interface generator function would not affect existing builds. I think some recent patterns is to try to define targets in find package scripts instead of raw paths? But at the very least avoiding `CMAKE_SOURCE_DIR` (anything that refers to the top-level project in a tree) would be nice.

**Comment by avidov** [comment]
> Currently flashlight is using CMake variables that are not compatible with including the project as a subdirectory in another

I think that it is compatible with including the project as a subdirectory in another since it exports [flashlightConfig.cmake ](https://github.com/facebookresearch/flashlight/blob/master/CMakeLists.txt#L275)
file that allow you to use find_package() see: 
https://cmake.org/cmake/help/v3.12/command/install.html#installing-exports

**Comment by jacobkahn** [comment]
@kriswuollett — not sure if you've had a chance to pull/rebase on top of master, but we've made a bunch of these changes, purged `CMAKE_SOURCE_DIR`, and improved how we download external projects (we don't anymore if those deps are present). Feel free to let us know how else we can improve the build experience.
