### ISSUE TITLE
Roadmap for OpenCL / Windows support

### ISSUE THREAD

**Issue by danielwinkler** [facebookresearch/flashlight#88]
Thanks for your nice efforts! I will start using this library for a small project.

Unfortunately I am currently limited to a windows workstation with a CUDA gpu and a MacBook Pro with an external GPU.
This means though that I have currently no option to use GPU acceleration for flashlight.
Do you have rough estimates by when you want to support either windows or OpenCL?

**Comment by avidov** [comment]
Hi Daniel, 
What are the issues you are facing with the HW that you are using ?

**Comment by danielwinkler** [comment]
hi gilad @avidov ,

thanks for your reply.
actually the hardware is not the problem, but the software/OS policy I have to follow.

my options for hardware acceleration :
- windows build is not supported
- cuda docker is not supported on windows host
- mac os only supports amd, but opencl is not yet implemented

i am currently working with cpu backend, but would be curious if one of the above will be supported in the near future

thanks a lot for your efforts!

**Comment by avidov** [comment]
Support for diffrent backend is already in the pipeline, including for AMD, however release date is not set yet.

**Comment by danielwinkler** [comment]
Thanks for the info.
