### ISSUE TITLE
AutogradTest failed and throw unknown exception

### ISSUE THREAD

**Issue by WeiLi233** [facebookresearch/flashlight#92]
I compiled flashlight with the commit 050bd2a and  with the GPU backend,  after I ran `make test`, AutogradTest failed, with running `build/test/AutogradTest`, the log info was:

> [==========] Running 55 tests from 1 test case.
> [----------] Global test environment set-up.
> [----------] 55 tests from AutogradTest
> [ RUN      ] AutogradTest.AfRefCountBasic
> [       OK ] AutogradTest.AfRefCountBasic (1629 ms)
> [ RUN      ] AutogradTest.AfRefCountModify
> [       OK ] AutogradTest.AfRefCountModify (0 ms)
> [ RUN      ] AutogradTest.AfRefCountGradient
> [       OK ] AutogradTest.AfRefCountGradient (0 ms)
> [ RUN      ] AutogradTest.AfArrBackwardNoMutate
> [       OK ] AutogradTest.AfArrBackwardNoMutate (135 ms)
> [ RUN      ] AutogradTest.Multiply
> [       OK ] AutogradTest.Multiply (264 ms)
> [ RUN      ] AutogradTest.BasicOps
> [       OK ] AutogradTest.BasicOps (7515 ms)
> [ RUN      ] AutogradTest.OperatorParenthesis
> [       OK ] AutogradTest.OperatorParenthesis (853 ms)
> [ RUN      ] AutogradTest.MultiplyAdd
> [       OK ] AutogradTest.MultiplyAdd (603 ms)
> [ RUN      ] AutogradTest.NoCalcGrad
> [       OK ] AutogradTest.NoCalcGrad (2 ms)
> [ RUN      ] AutogradTest.MultiplySub
> [       OK ] AutogradTest.MultiplySub (481 ms)
> [ RUN      ] AutogradTest.DivideAdd
> [       OK ] AutogradTest.DivideAdd (529 ms)
> [ RUN      ] AutogradTest.MultiplyAddScalar
> [       OK ] AutogradTest.MultiplyAddScalar (393 ms)
> [ RUN      ] AutogradTest.Exp
> [       OK ] AutogradTest.Exp (133 ms)
> [ RUN      ] AutogradTest.Sigmoid
> [       OK ] AutogradTest.Sigmoid (271 ms)
> [ RUN      ] AutogradTest.Tanh
> [       OK ] AutogradTest.Tanh (268 ms)
> [ RUN      ] AutogradTest.Concatenate
> [       OK ] AutogradTest.Concatenate (302 ms)
> [ RUN      ] AutogradTest.Split
> [       OK ] AutogradTest.Split (705 ms)
> [ RUN      ] AutogradTest.TileAs
> [       OK ] AutogradTest.TileAs (284 ms)
> [ RUN      ] AutogradTest.TileAs2
> [       OK ] AutogradTest.TileAs2 (144 ms)
> [ RUN      ] AutogradTest.Tile
> [       OK ] AutogradTest.Tile (1 ms)
> [ RUN      ] AutogradTest.Clamp
> [       OK ] AutogradTest.Clamp (972 ms)
> [ RUN      ] AutogradTest.SumAs
> [       OK ] AutogradTest.SumAs (365 ms)
> [ RUN      ] AutogradTest.SumAs2
> [       OK ] AutogradTest.SumAs2 (145 ms)
> [ RUN      ] AutogradTest.Sum
> [       OK ] AutogradTest.Sum (0 ms)
> [ RUN      ] AutogradTest.Log1p
> [       OK ] AutogradTest.Log1p (276 ms)
> [ RUN      ] AutogradTest.Sqrt
> [       OK ] AutogradTest.Sqrt (274 ms)
> [ RUN      ] AutogradTest.Mean
> [       OK ] AutogradTest.Mean (290 ms)
> [ RUN      ] AutogradTest.Variance
> /**/flashlight/tests/autograd/AutogradTest.cpp:485: Failure
> Value of: allClose(calculated_var.array(), expected_var)
>   Actual: false
> Expected: true
> [  FAILED  ] AutogradTest.Variance (395 ms)
> [ RUN      ] AutogradTest.Norm
> [       OK ] AutogradTest.Norm (274 ms)
> [ RUN      ] AutogradTest.Indexing
> [       OK ] AutogradTest.Indexing (873 ms)
> [ RUN      ] AutogradTest.Convolve
> [       OK ] AutogradTest.Convolve (8244 ms)
> [ RUN      ] AutogradTest.ConvolveFilterGroups
> [       OK ] AutogradTest.ConvolveFilterGroups (4954 ms)
> [ RUN      ] AutogradTest.ConvolveDilation
> [       OK ] AutogradTest.ConvolveDilation (2613 ms)
> [ RUN      ] AutogradTest.Padding
> [       OK ] AutogradTest.Padding (137 ms)
> [ RUN      ] AutogradTest.Pooling
> [       OK ] AutogradTest.Pooling (2 ms)
> [ RUN      ] AutogradTest.Softmax
> [       OK ] AutogradTest.Softmax (554 ms)
> [ RUN      ] AutogradTest.LogSoftmax
> [       OK ] AutogradTest.LogSoftmax (295 ms)
> [ RUN      ] AutogradTest.BinaryCrossEntropy
> [       OK ] AutogradTest.BinaryCrossEntropy (135 ms)
> [ RUN      ] AutogradTest.CrossEntropy
> [       OK ] AutogradTest.CrossEntropy (456 ms)
> [ RUN      ] AutogradTest.Reorder
> [       OK ] AutogradTest.Reorder (269 ms)
> [ RUN      ] AutogradTest.Glu
> [       OK ] AutogradTest.Glu (413 ms)
> [ RUN      ] AutogradTest.Linear
> unknown file: Failure
> C++ exception with description "ArrayFire Exception (Internal error:998):
> In function af_err af_matmul(void**, af_array, af_array, af_mat_prop, af_mat_prop)
> In file src/api/c/blas.cpp:269
> 
> 
>  0# af_matmul in /usr/local/lib/libafcuda.so.3
>  1# af::matmul(af::array const&, af::array const&, af_mat_prop, af_mat_prop) in /usr/local/lib/libafcuda.so.3
>  2# 0x0000555880B469CB in ./tests/AutogradTest
>  3# 0x0000555880B16396 in ./tests/AutogradTest
>  4# 0x0000555880B17B59 in ./tests/AutogradTest
>  5# 0x0000555880B22157 in ./tests/AutogradTest
>  6# 0x0000555880CA175A in ./tests/AutogradTest
>  7# 0x0000555880C97D2E in ./tests/AutogradTest
>  8# 0x0000555880C981CD in ./tests/AutogradTest
>  9# 0x0000555880C983CD in ./tests/AutogradTest
> 10# 0x0000555880C99269 in ./tests/AutogradTest
> 11# 0x0000555880C99555 in ./tests/AutogradTest
> 12# 0x0000555880B0AFAF in ./tests/AutogradTest
> 13# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
> 14# 0x0000555880B152AA in ./tests/AutogradTest
> 
> In function af::array af::matmul(const af::array&, const af::array&, af::matProp, af:" thrown in the test body.
> [  FAILED  ] AutogradTest.Linear (474 ms)
> [ RUN      ] AutogradTest.WeightNormLinear
> 

the GPU related info was :
 NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.1

**Comment by jacobkahn** [comment]
@WeiLi233 — there was an issue with the ArrayFire binary installer and BLAS functions that was recently fixed in the last few days. If you try rebuilding/reinstalling ArrayFire then rebuilding flashlight, that's likely to fix your issue. Feel free to reopen if you're still having trouble.

**Comment by xiaosdawn** [comment]
Hi, I had met ERROR. It seems to be relevant to this issue.
I used 8*V100(32GB) to train transformer_s2s by the flashlight.  It had trained normally until 95 epochs.  At the time of the 96th epoch, the error occurred. Log details as:
'''
I1029 17:45:57.743314  3585 Train.cpp:578] Epoch 95 started!
I1029 22:00:06.912845  3585 Train.cpp:351] epoch:       95 | nupdates:      3878090 | lr: 0.030000 | lrcriterion: 0.030000 | runtime: 04:06:14 | bch(ms): 358.30 | smp(ms): 0.59 | fwd(ms): 73.51 | crit-fwd(ms): 7.26 | bwd(ms): 225.69 | optim(ms): 48.29 | loss:   22.27160 | train-TER:  6.36 | train-WER: 11.03 | dev-all-loss:    4.49804 | dev-all-TER:  2.14 | dev-all-WER:  5.02 | dev-clean-loss:    5.62497 | dev-clean-TER:  1.29 | dev-clean-WER:  3.32 | dev-other-loss:    8.85458 | dev-other-TER:  4.29 | dev-other-WER:  8.64 | avg-isz: 1169 | avg-tsz: 022 | max-tsz: 173 | hrs: 4288.03 | thrpt(sec/sec): 1044.83
Memory Manager Stats
Type: CachingMemoryManager
Device: 0, Capacity: 31.74 GiB, Allocated: 28.21 GiB, Cached: 26.08 GiB
Total native calls: 1744(mallocs), 709(frees)
I1029 22:00:16.349804  3585 Train.cpp:571] Shuffling trainset
I1029 22:00:16.380712  3585 Train.cpp:578] Epoch 96 started!
terminate called after throwing an instance of 'af::exception'
  what():  ArrayFire Exception (Internal error:998):
In function af_err af_matmul(void**, af_array, af_array, af_mat_prop, af_mat_prop)
In file src/api/c/blas.cpp:254


 0# af_matmul in /usr/local/lib/libafcuda.so.3
 1# af::matmulNT(af::array const&, af::array const&) in /usr/local/lib/libafcuda.so.3
 2# 0x000055B916FF9726 in flashlight/build/Train
 3# 0x000055B916FF8B75 in flashlight/build/Train
 4# 0x000055B917006ADA in flashlight/build/Train
 5# 0x000055B916FEA335 in flashlight/build/Train
 6# 0x000055B916FE5A51 in flashlight/build/Train
 7# 0x000055B916FE5B4C in flashlight/build/Train
 8# 0x000055B916FE5CB1 in flashlight/build/Train
 9# 0x000055B916CEAD34 in flashlight/build/Train
10# 0x000055B916CEFBE5 in flashlight/build/Train
11# __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
12# 0x000055B916CE79CA in flashlight/build/Train

In function af::array af::matmulNT(const af::array&, const af::array&)
In file src/api/cpp/blas.cpp:24
*** Aborted at 1604021224 (unix time) try "date -d @1604021224" if you are using GNU date ***
PC: @     0x7f65e0767e97 gsignal
*** SIGABRT (@0xe07) received by PID 3591 (TID 0x7f66256e3380) from PID 3591; stack trace: ***
    @     0x7f661e8e4890 (unknown)
    @     0x7f65e0767e97 gsignal
    @     0x7f65e0769801 abort
    @     0x7f65e115c957 (unknown)
    @     0x7f65e1162ab6 (unknown)
    @     0x7f65e1162af1 std::terminate()
    @     0x7f65e1162d24 __cxa_throw
    @     0x7f6601bd1c92 af::matmulNT()
    @     0x55b916ff9726 fl::matmulNT()
    @     0x55b916ff8b75 _ZZN2fl6matmulERKNS_8VariableES2_ENKUlRSt6vectorIS0_SaIS0_EES2_E_clES6_S2_
    @     0x55b917006ada _ZNSt17_Function_handlerIFvRSt6vectorIN2fl8VariableESaIS2_EERKS2_EZNS1_6matmulES7_S7_EUlS5_S7_E_E9_M_invokeERKSt9_Any_dataS5_S7_
    @     0x55b916fea335 std::function<>::operator()()
    @     0x55b916fe5a51 fl::Variable::calcGradInputs()
    @     0x55b916fe5b4c fl::Variable::backward()
    @     0x55b916fe5cb1 fl::Variable::backward()
    @     0x55b916cead34 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_INS0_3app3asr17SequenceCriterionEES_INS4_7DatasetEES_INS0_19FirstOrderOptimizerEESA_ddblE3_clES2_S6_S8_SA_SA_ddbl
    @     0x55b916cefbe5 main
    @     0x7f65e074ab97 __libc_start_main
    @     0x55b916ce79ca _start
*** Aborted at 1604021225 (unix time) try "date -d @1604021225" if you are using GNU date ***
PC: @     0x7ffdd8fedb62 ([vdso]+0xb61)
*** SIGTERM (@0x55ee8e790280) received by PID 3589 (TID 0x7fb7d73a3380) from PID 18446744071804879488; stack trace: ***
    @     0x7fb792427f20 (unknown)
    @     0x7ffdd8fedb62 ([vdso]+0xb61)
    @     0x7fb792519ea6 __clock_gettime
    @     0x7fb77903d70e (unknown)
    @     0x7fb779116837 (unknown)
    @     0x7fb778fdeb6c (unknown)
    @     0x7fb778f14f4f (unknown)
    @     0x7fb779099259 cuMemFree_v2
    @     0x7fb77a50ff94 (unknown)
    @     0x7fb77a547b81 (unknown)
    @     0x7fb77a379ae9 (unknown)
    @     0x7fb77a37a031 (unknown)
    @     0x7fb7b30ad191 cuda::matmul<>()
    @     0x7fb7b355a890 af_sparse_matmul()
    @     0x7fb7b355cf23 af_matmul
    @     0x7fb7b3891d59 af::matmulTN()
    @     0x55ee8c5aad80 _ZZN2fl9embeddingERKNS_8VariableES2_ENKUlRSt6vectorIS0_SaIS0_EES2_E_clES6_S2_
    @     0x55ee8c5b2e1e _ZNSt17_Function_handlerIFvRSt6vectorIN2fl8VariableESaIS2_EERKS2_EZNS1_9embeddingES7_S7_EUlS5_S7_E_E9_M_invokeERKSt9_Any_dataS5_S7_
    @     0x55ee8c595335 std::function<>::operator()()
    @     0x55ee8c590a51 fl::Variable::calcGradInputs()
    @     0x55ee8c590b4c fl::Variable::backward()
    @     0x55ee8c590cb1 fl::Variable::backward()
    @     0x55ee8c295d34 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_INS0_3app3asr17SequenceCriterionEES_INS4_7DatasetEES_INS0_19FirstOrderOptimizerEESA_ddblE3_clES2_S6_S8_SA_SA_ddbl
    @     0x55ee8c29abe5 main
    @     0x7fb79240ab97 __libc_start_main
    @     0x55ee8c2929ca _start
*** Aborted at 1604021225 (unix time) try "date -d @1604021225" if you are using GNU date ***
PC: @     0x7fffb83c8b62 ([vdso]+0xb61)
*** SIGTERM (@0x557f4992c100) received by PID 3586 (TID 0x7f0ee5066380) from PID 1234354432; stack trace: ***
    @     0x7f0ea00eaf20 (unknown)
    @     0x7fffb83c8b62 ([vdso]+0xb61)
    @     0x7f0ea01dcea6 __clock_gettime
    @     0x7f0e86d0070e (unknown)
    @     0x7f0e86dd9837 (unknown)
    @     0x7f0e86ca1b6c (unknown)
    @     0x7f0e86bd7f4f (unknown)
    @     0x7f0e86d5c259 cuMemFree_v2
    @     0x7f0e881d2f94 (unknown)
    @     0x7f0e8820ab81 (unknown)
    @     0x7f0e8803cae9 (unknown)
    @     0x7f0e8803d031 (unknown)
    @     0x7f0ec0d70191 cuda::matmul<>()
    @     0x7f0ec121d890 af_sparse_matmul()
    @     0x7f0ec121ff23 af_matmul
    @     0x7f0ec1554d59 af::matmulTN()
    @     0x557f47b4cd80 _ZZN2fl9embeddingERKNS_8VariableES2_ENKUlRSt6vectorIS0_SaIS0_EES2_E_clES6_S2_
    @     0x557f47b54e1e _ZNSt17_Function_handlerIFvRSt6vectorIN2fl8VariableESaIS2_EERKS2_EZNS1_9embeddingES7_S7_EUlS5_S7_E_E9_M_invokeERKSt9_Any_dataS5_S7_
    @     0x557f47b37335 std::function<>::operator()()
    @     0x557f47b32a51 fl::Variable::calcGradInputs()
    @     0x557f47b32b4c fl::Variable::backward()
    @     0x557f47b32cb1 fl::Variable::backward()
    @     0x557f47837d34 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_INS0_3app3asr17SequenceCriterionEES_INS4_7DatasetEES_INS0_19FirstOrderOptimizerEESA_ddblE3_clES2_S6_S8_SA_SA_ddbl
    @     0x557f4783cbe5 main
    @     0x7f0ea00cdb97 __libc_start_main
    @     0x557f478349ca _start
*** Aborted at 1604021225 (unix time) try "date -d @1604021225" if you are using GNU date ***
PC: @     0x7ffead7bbb62 ([vdso]+0xb61)
*** SIGTERM (@0x55a340fe70f0) received by PID 3585 (TID 0x7faef8285380) from PID 1090416880; stack trace: ***
    @     0x7faeb3309f20 (unknown)
    @     0x7ffead7bbb62 ([vdso]+0xb61)
    @     0x7faeb33fbea6 __clock_gettime
    @     0x7fae99f1f70e (unknown)
    @     0x7fae99ff8837 (unknown)
    @     0x7fae99ec0b6c (unknown)
    @     0x7fae99df6f4f (unknown)
    @     0x7fae99f7b259 cuMemFree_v2
    @     0x7fae9b3f1f94 (unknown)
    @     0x7fae9b429b81 (unknown)
    @     0x7fae9b25bae9 (unknown)
    @     0x7fae9b25c031 (unknown)
    @     0x7faed3f8f191 cuda::matmul<>()
    @     0x7faed443c890 af_sparse_matmul()
    @     0x7faed443ef23 af_matmul
    @     0x7faed4773d59 af::matmulTN()
    @     0x55a33e560d80 _ZZN2fl9embeddingERKNS_8VariableES2_ENKUlRSt6vectorIS0_SaIS0_EES2_E_clES6_S2_
    @     0x55a33e568e1e _ZNSt17_Function_handlerIFvRSt6vectorIN2fl8VariableESaIS2_EERKS2_EZNS1_9embeddingES7_S7_EUlS5_S7_E_E9_M_invokeERKSt9_Any_dataS5_S7_
    @     0x55a33e54b335 std::function<>::operator()()
    @     0x55a33e546a51 fl::Variable::calcGradInputs()
    @     0x55a33e546b4c fl::Variable::backward()
    @     0x55a33e546cb1 fl::Variable::backward()
    @     0x55a33e24bd34 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_INS0_3app3asr17SequenceCriterionEES_INS4_7DatasetEES_INS0_19FirstOrderOptimizerEESA_ddblE3_clES2_S6_S8_SA_SA_ddbl
    @     0x55a33e250be5 main
    @     0x7faeb32ecb97 __libc_start_main
    @     0x55a33e2489ca _start
*** Aborted at 1604021225 (unix time) try "date -d @1604021225" if you are using GNU date ***
PC: @     0x7ffdcd8e2b62 ([vdso]+0xb61)
*** SIGTERM (@0x200d3f440) received by PID 3588 (TID 0x7f3c44a48380) from PID 13890624; stack trace: ***
    @     0x7f3bffaccf20 (unknown)
    @     0x7ffdcd8e2b62 ([vdso]+0xb61)
    @     0x7f3bffbbeea6 __clock_gettime
    @     0x7f3be66e270e (unknown)
    @     0x7f3be67bb837 (unknown)
    @     0x7f3be6683b6c (unknown)
    @     0x7f3be65b9f4f (unknown)
    @     0x7f3be673e259 cuMemFree_v2
    @     0x7f3be7bb4f94 (unknown)
    @     0x7f3be7becb81 (unknown)
    @     0x7f3be7a1eae9 (unknown)
    @     0x7f3be7a1f031 (unknown)
    @     0x7f3c20752191 cuda::matmul<>()
    @     0x7f3c20bff890 af_sparse_matmul()
    @     0x7f3c20c01f23 af_matmul
    @     0x7f3c20f36d59 af::matmulTN()
    @     0x5633d6010d80 _ZZN2fl9embeddingERKNS_8VariableES2_ENKUlRSt6vectorIS0_SaIS0_EES2_E_clES6_S2_
    @     0x5633d6018e1e _ZNSt17_Function_handlerIFvRSt6vectorIN2fl8VariableESaIS2_EERKS2_EZNS1_9embeddingES7_S7_EUlS5_S7_E_E9_M_invokeERKSt9_Any_dataS5_S7_
    @     0x5633d5ffb335 std::function<>::operator()()
    @     0x5633d5ff6a51 fl::Variable::calcGradInputs()
    @     0x5633d5ff6b4c fl::Variable::backward()
    @     0x5633d5ff6cb1 fl::Variable::backward()
    @     0x5633d5cfbd34 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_INS0_3app3asr17SequenceCriterionEES_INS4_7DatasetEES_INS0_19FirstOrderOptimizerEESA_ddblE3_clES2_S6_S8_SA_SA_ddbl
    @     0x5633d5d00be5 main
    @     0x7f3bffaafb97 __libc_start_main
    @     0x5588c90979ca _start
*** Aborted at 1604021225 (unix time) try "date -d @1604021225" if you are using GNU date ***
PC: @     0x7ffdff691b62 ([vdso]+0xb61)
*** SIGTERM (@0x55fd4415b970) received by PID 3592 (TID 0x7fde0eaac380) from PID 1142274416; stack trace: ***
    @     0x7fddc9b30f20 (unknown)
    @     0x7ffdff691b62 ([vdso]+0xb61)
    @     0x7fddc9c22ea6 __clock_gettime
    @     0x7fddb074670e (unknown)
    @     0x7fddb081f837 (unknown)
    @     0x7fddb06e7b6c (unknown)
    @     0x7fddb061df4f (unknown)
    @     0x7fddb07a2259 cuMemFree_v2
    @     0x7fddb1c18f94 (unknown)
    @     0x7fddb1c50b81 (unknown)
    @     0x7fddb1a82ae9 (unknown)
    @     0x7fddb1a83031 (unknown)
    @     0x7fddea7b6191 cuda::matmul<>()
    @     0x7fddeac63890 af_sparse_matmul()
    @     0x7fddeac65f23 af_matmul
    @     0x7fddeaf9ad59 af::matmulTN()
    @     0x55fd41982d80 _ZZN2fl9embeddingERKNS_8VariableES2_ENKUlRSt6vectorIS0_SaIS0_EES2_E_clES6_S2_
    @     0x55fd4198ae1e _ZNSt17_Function_handlerIFvRSt6vectorIN2fl8VariableESaIS2_EERKS2_EZNS1_9embeddingES7_S7_EUlS5_S7_E_E9_M_invokeERKSt9_Any_dataS5_S7_
    @     0x55fd4196d335 std::function<>::operator()()
    @     0x55fd41968a51 fl::Variable::calcGradInputs()
    @     0x55fd41968b4c fl::Variable::backward()
    @     0x55fd41968cb1 fl::Variable::backward()
    @     0x55fd4166dd34 _ZZ4mainENKUlSt10shared_ptrIN2fl6ModuleEES_INS0_3app3asr17SequenceCriterionEES_INS4_7DatasetEES_INS0_19FirstOrderOptimizerEESA_ddblE3_clES2_S6_S8_SA_SA_ddbl
    @     0x55fd41672be5 main
    @     0x7fddc9b13b97 __libc_start_main
    @     0x55fd4166a9ca _start
--------------------------------------------------------------------------
mpirun noticed that process rank 6 with PID 0 on node 6ae622cf394f exited on signal 6 (Aborted).
--------------------------------------------------------------------------
'''
the GPU related info was : NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2
The flashlight was built at 30/09/2020 (sorry for the specific commit). 
BTW, before training this model, I had trained transformer_s2s using librispeech successfully. Current model uses 2500 hours, of which 1500h is my own data and 1000 is librispeech. In my own data, each audio clip does not exceed 36 seconds.
So, any help will be appreciated. Thanks.

**Comment by tlikhomanenko** [comment]
What does happen if you continue training after crash? It could be some bad batch probably, not sure. As soon as trained before for 95 epochs (could you confirm it is epochs not updates) this looks really weird.

**Comment by xiaosdawn** [comment]
I did nothing, the error just occured during the 96th epoch. When I continued training, it crashed mostly like the 96th epoch not updates. After all, the 96th epoch has errors. It is weird for me too. I haven't found a solution yet.

**Comment by tlikhomanenko** [comment]
could you specify your config file, arrayfire version, hash commit for fl and w2l, cudnn version?
