### ISSUE TITLE
 examples/Mnist error: Can't find MNIST file 

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#97]
Just a small filename error:
$ examples/Mnist /home/wtambellini/Downloads/mnist
terminate called after throwing an instance of 'af::exception'
  what():  [mnist:load_data] Can't find MNIST file  /home/wtambellini/Downloads/mnist/train-images-idx3-ubyte

See that the example src searches for train-images-idx3-ubyte
but the file in the gz 
http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
is named "train-images.idx3-ubyte"

wget http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
gzip -l train-images-idx3-ubyte.gz 
         compressed        uncompressed  ratio uncompressed_name
            9912422            47040016  78.9% train-images-idx3-ubyte

**Comment by tlikhomanenko** [comment]
Hi @WilliamTambellini,

Thanks for pointing this (and for future users if they face the same problem)! However, there is the note that one should extract files before running the example https://github.com/facebookresearch/flashlight/blob/master/examples/Mnist.cpp#L14.

Will think to have better docs for this later.

**Comment by WilliamTambellini** [comment]
Hi @tlikhomanenko  I ve of course extracted but wont fix FL trying to open with the wrong filenames.

**Comment by tlikhomanenko** [comment]
Sorry, then I didn't understand what is the error you get? Does it fail when you specify data directory (which is extracted data)?

**Comment by WilliamTambellini** [comment]
Hi @tlikhomanenko 
>  then I didn't understand what is the error you get?
what(): [mnist:load_data] Can't find MNIST file
> Does it fail when you specify data directory (which is extracted data)?
yes
FL searches for train-images-idx3-ubyte (as expected)
but the file extracted by ubuntu archive manager is (strangely) named "train-images.idx3-ubyte"  (dash replaced by dot). Probably a bug in ubuntu. Anyway, Tks

**Comment by tlikhomanenko** [comment]
Ohh, got it. Let me check what I have on my system.

**Comment by tlikhomanenko** [comment]
OK, for me on MacOS and Ubuntu 18.04 it works fine:
```
gunzip train-images-idx3-ubyte.gz
```
gives 
```
$ ls train-images-idx3-ubyte
train-images-idx3-ubyte
```
