### ISSUE TITLE
Add an option to link with the cudnn static lib

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#98]
Hi
As today FL master links with the shared CUDNN lib : 
~/repos/flashlight/release (master) $ ldd tests/AllReduceTest 
...
	libcudnn.so.7 => /tmp/cudnn/cuda/lib64/libcudnn.so.7 (0x00007f3c86144000)
...

because of FindCUDNN.cmake file : 
...
find_library(CUDNN_LIBRARY
  NAMES libcudnn.so${__cudnn_ver_suffix} libcudnn${__cudnn_ver_suffix}.dylib ${__cudnn_lib_win_name}
  PATHS $ENV{LD_LIBRARY_PATH} ${__libpath_cudart} ${CUDNN_ROOT_DIR} ${PC_CUDNN_LIBRARY_DIRS} ${CMAKE_INSTALL_PREFIX}
  PATH_SUFFIXES lib lib64 bin
  DOC "CUDNN library." )

Without entering into too many details, there are advantages to link statically as now done in AF:
https://github.com/arrayfire/arrayfire/pull/2785

Would you mind if I add a cmake option to link FL with static CUDNN (similar to USE_STATIC_NCCL) ? 

Kind
W.

**Comment by jacobkahn** [comment]
@WilliamTambellini — we would welcome that PR - I saw that change for several other CUDA dependency libs too.

I think we still want to make this configurable -- cuDNN is a large lib, and statically linking makes moving a compiled flashlight lib around more difficult.

**Comment by WilliamTambellini** [comment]
Hi @jacobkahn  Cool, I m on it.
Could you please check on your machines/CI servers the name of the static libs for macos and windows (if any are available) ?
Did nt see any hints overthere:
https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html

**Comment by jacobkahn** [comment]
@WilliamTambellini — we don't support a Windows build/MSVC compatibility at the moment, so no need to dive into that.

Re MacOS, from the [cuDNN download page](https://developer.nvidia.com/rdp/cudnn-download), it doesn't seem there's a specific way to install for macOS - it seems that it's the same as Linux, so the libs should have the same name (`libcudnn_static`?)

**Comment by WilliamTambellini** [comment]
ok tks, I m reluctant to add support for something that I cannot verify that it works (MacOS).
Would you mind if I add support for static cudnn only for Linux at the moment ?
IF ($ENV{USE_STATIC_CUDNN})
  if (! ${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
    MESSAGE(FATAL "USE_STATIC_CUDNN only supported on Linux")
  endif()

**Comment by jacobkahn** [comment]
@WilliamTambellini — that sounds absolutely fine for now (Linux only, not macOS) is best. I think `UNIX AND NOT APPLE` is also a good way to check OS type.

**Comment by WilliamTambellini** [comment]
https://github.com/facebookresearch/flashlight/pull/101
